### DISCUSSION TITLE
3rd Party SMTP not working.

### DISCUSSION THREAD

**Discussion by vinitchopra12** [pimcore/pimcore#10175] [Q&A / Support]
Hello,

I am working on Pimcore v10. I need to configured the AWS SES SMTP details with TLS for sending emails. But unfortunately, it's not working with the pimcore default config.

```
framework:
    mailer:
        transports:
           main: smtp://<username>:<password>@<host>:<port>
```

When, I try to send test email from admin it gives the error. See below screenshot.

![image](https://user-images.githubusercontent.com/14720025/131001021-3a05e381-9973-43ca-b346-585a1be54b30.png)

Additionally, I have installed the symfony/amazon-mailer package also, but not working. Wondering, if the above config remain same. I tried with ses+smtp://...
