### DISCUSSION TITLE
Generate custom sitemap

### DISCUSSION THREAD

**Discussion by valentin-** [pimcore/pimcore#10295] [Q&A / Support]
Hi, I'm trying to generate a product sitemap according to https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/Sitemaps.html#page_Creating-a-custom-generator

This is the config:
```
pimcore:
  sitemaps:
      generators:
        products:
          enabled: true
          priority: 50
          generator_id: App\Website\Sitemap\ProductSitemapGenerator
```

It's working so far, but the section/filename is empty. 
![image](https://user-images.githubusercontent.com/90033/132829011-2ba0be9f-13e4-4313-b888-dda58bacaf98.png)

Trying to pass the section using `presta:sitemaps:dump --section=products` results in an error, because $matches is an empty array: https://github.com/prestaconcept/PrestaSitemapBundle/blob/3.x/src/Service/Dumper.php#L184

I'm not sure if theres an error, I would have expected the namespace (products) being used as filename.

Any ideas?

Thanks!
