### DISCUSSION TITLE
Is it possible to use the doctrine:migrations:diff command

### DISCUSSION THREAD

**Discussion by aurelienl-acelys** [pimcore/pimcore#10948] [Q&A / Support]
Hi everyone, I am a new Pimcore user / developer and this is my first post on GitHub ! (so sorry if i go wrong ;) ) 

I would like to know if it is possible to generate an automatic migration for custom entities.

I have created my entities, the entity manager works if I manually created my tables in my database.

But I would like to be able to use the `php doctrine:migrations:diff` command to have Symfony automatically generate migrations for me, as I usually do on my Symfony projects.

Currently I have the following error:
**The schema provider is not available**

Here is part of my config.yaml file : 

```
doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
```

Is there a configuration specific to Pimcore to set up to be able to use the generation of migration?

Thanking you for your help.
