### DISCUSSION TITLE
Pimcore X and Redis

### DISCUSSION THREAD

**Discussion by zangab** [pimcore/pimcore#10971] [Q&A / Support]
Hi,
I installed & configured the redis-server on my digitalocean (DO) droplet.
The server is running on localhost with the default port (6379).

Afterwards, I changed the following settings in the php.ini file:
```
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379?"
```

In addition, I installed `php-redis` (as stated in another discussion, due to predis error).
I did restart the redis-server and the apache but if I access `/admin` I get the following error:
`Cannot call default session handler`.

It's PHP 8, Pimcore 10.1.4 on Ubuntu 20.

I copied the redis config from the docs, so I updated the `config.yaml` as following:

```yaml
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 31536000  # 1 year
                adapter: pimcore.cache.adapter.redis_tag_aware
                provider: 'redis://localhost:6379'
```

The cli system-check prints "warning" on Redis.
`bin/console pimcore:system:requirements:check`

Any ideas?
Thanks.
🙇
