### DISCUSSION TITLE
Asset workflow Neither the property "marking" nor one of the methods

### DISCUSSION THREAD

**Discussion by betterapp** [pimcore/pimcore#11210] [Q&A / Support]
Hello

I try to use Workflow for Asset.

I have configured it like this:

```
BasicImage:
            enabled: true
            priority: 1
            label: 'Basic image workflow'
            initial_place: Uploaded
            type: state_machine
            audit_trail:
                enabled: false
            marking_store:
                type: single_state
            supports:
                - \Pimcore\Model\Asset\Image
            places:
                Uploaded:
                    label: Uploaded
                    title: Uploaded
                    color: '#cccccc'
                    visibleInHeader: true
                Verified:
                    label: Verified
                    title: Verified
                    color: '#48b821'
                    visibleInHeader: true
            transitions:
                Verify:
                    from:
                        - Uploaded
                    to:
                        - Verified
                    options:
                        changePublishedState: no_change
                        notes:
                            commentEnabled: false
                            additionalFields: {  }
                            commentRequired: false
                            type: 'Status update'
                    name: Verify
            globalActions: {  }
```

and when I upload Image to the Asset I got error:

`Neither the property "marking" nor one of the methods "getMarking()", "marking()", "isMarking()", "hasMarking()", "__get()" exist and have public access in class "Pimcore\Model\Asset\Image".`

Do You know why ?
