### DISCUSSION TITLE
After Update to 10.3.1 - Invalid configuration for path "framework.mailer": "dsn" and "transports" cannot be used together.

### DISCUSSION THREAD

**Discussion by Stefan-JustMe69-SQ** [pimcore/pimcore#11473] [Q&A / Support]
I created Issue #11471 

How can I fix this issue and find the misconfigured values?

Even going back to version 10.3.0 is showing this error and pimcore is not working anymore.

Any help apreciated.

**Comment by Stefan-JustMe69-SQ** [comment]
under config/packages is an auto-generated mailer.yml, which causes the error:
```
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
```
why does this have to be auto-generated?

After removing this, there's the next-error:
```
"The service "session" has a dependency on a non-existent service "session.storage". Did you mean this: "session.storage.factory.native"?
```
In the file config/packages/framework.yaml I see:
```
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```
How to fix this error?
