### DISCUSSION TITLE
Migrating Existing Storage Bucket within a new PIMCORE Installation

### DISCUSSION THREAD

**Discussion by solverat** [pimcore/pimcore#11541] [Ideas]
If you're dealing with an existing remote storage like AWS S3 within a new PIMCORE installation, you need to initially populate asset references in your database. 

For that, you may want to implement a simple adapter for Flysystem:

```yaml
flysystem:
    storages:
        pimcore_local:
            adapter: 'App\Flysystem\PimcoreLocalAdapter'

        pimcore.sync_asset.storage.source:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: 'MY_BUCKET'
                prefix: 'PREFIX'

        pimcore.sync_asset.storage.target:
            adapter: 'pimcore_local'
            visibility: public

services:
    pimcore_local:
        autowire: true
        class: 'App\Flysystem\PimcoreLocalAdapter'
```

```php
<?php

namespace App\Flysystem;

use League\Flysystem\Config;
use League\Flysystem\FileAttributes;
use League\Flysystem\FilesystemAdapter;
use Pimcore\Db\Connection;
use Pimcore\Model\Asset;
use Pimcore\Model\Asset\Service;

class PimcoreLocalAdapter implements FilesystemAdapter
{
    protected Connection $connection;

    public function __construct(Connection $connection)
    {
        $this->connection = $connection;
    }

    public function writeStream(string $path, $contents, Config $config): void
    {
        if ($path === '') {
            return;
        }

        $dirName = dirname($path);
        $fileName = basename($path);

        $assetParent = Service::createFolderByPath($dirName);

        $fileInfo = new \finfo(FILEINFO_MIME_TYPE);
        $mimeType = $fileInfo->buffer(stream_get_contents($contents));

        $type = Asset::getTypeFromMimeMapping($mimeType, $path);

        $asset = new Asset();
        $asset->setType($type);
        $asset->setParent($assetParent);
        $asset->setMimeType($mimeType);
        $asset->setKey($fileName);
        $asset->setDataChanged(false); // we don't want to callback to remote

        $asset->save();
    }

    public function fileExists(string $path): bool
    {
        $dirName = dirname($path);
        $fileName = basename($path);

        return $this->connection->fetchRow(
                'SELECT id FROM assets WHERE path = :path AND `filename` = :key',
                [
                    'path' => sprintf('/%s/', $dirName),
                    'key'  => $fileName
                ]
            ) !== false;
    }

    public function write(string $path, string $contents, Config $config): void
    {
        throw new \Exception('Not implemented');
    }

    public function read(string $path): string
    {
        throw new \Exception('Not implemented');
    }

    public function readStream(string $path)
    {
        throw new \Exception('Not implemented');
    }

    public function delete(string $path): void
    {
        throw new \Exception('Not implemented');
    }

    public function deleteDirectory(string $path): void
    {
        throw new \Exception('Not implemented');
    }

    public function createDirectory(string $path, Config $config): void
    {
        throw new \Exception('Not implemented');
    }

    public function setVisibility(string $path, string $visibility): void
    {
        throw new \Exception('Not implemented');
    }

    public function visibility(string $path): FileAttributes
    {
        throw new \Exception('Not implemented');
    }

    public function mimeType(string $path): FileAttributes
    {
        throw new \Exception('Not implemented');
    }

    public function lastModified(string $path): FileAttributes
    {
        throw new \Exception('Not implemented');
    }

    public function fileSize(string $path): FileAttributes
    {
        throw new \Exception('Not implemented');
    }

    public function listContents(string $path, bool $deep): iterable
    {
        throw new \Exception('Not implemented');
    }

    public function move(string $source, string $destination, Config $config): void
    {
        throw new \Exception('Not implemented');
    }

    public function copy(string $source, string $destination, Config $config): void
    {
        throw new \Exception('Not implemented');
    }
}
```

Now execute `bin/console pimcore:migrate:storage sync_asset -v` 

Hope this helps someone out there!
