### DISCUSSION TITLE
PimcoreOpenIdConnectBundle throws "Uncaught SyntaxError: Unexpected token '<'"

### DISCUSSION THREAD

**Discussion by MStumpp** [pimcore/pimcore#12067] [Q&A / Support] [answered]
Pimcore: 10.2.9
PimcoreOpenIdConnectBundle: version not shown

With enabled PimcoreOpenIdConnectBundle bundle, I get the following error (see console output in screenshot) and i am unable to login using OpenId (login form doesn't show up).

![Bildschirmfoto 2022-05-09 um 11 34 13](https://user-images.githubusercontent.com/1505314/167383149-e6bc9291-45dd-4c61-b7a3-75b2aa6c2822.png)

**Comment by fashxp** [comment]
could you please check if some requests fail when loading the login page and provide the error message? 
or any error messages in the log file?

**Comment by MStumpp** [comment, marked as answer]
Thanks

Snapshot of network connections:

![Bildschirmfoto 2022-05-09 um 12 59 05](https://user-images.githubusercontent.com/1505314/167397124-3b4fb090-4755-4b2c-806b-571c5164e812.png)

Notice status code 302 for `/script?perspective=`

**Reply by fashxp** [reply]
hmm, can you activate dev mode and have a more detailed look what happens? 
any error message? any error in log?
seems that the route to `/oidc/script` is not handled properly? maybe the bundle is not installed correctly or symfony container not rebuilt properly?

**Reply by MStumpp** [reply]
With dev mode, no errors show up in /var/log/dev.log (or in any of the other log files) or in application logger.
Bundle has been (re)installed several times, without success.
I can see a container in /var/cache/-stage-/Container******. Just in case, how to trigger a rebuild of the container?

**Reply by fashxp** [reply]
and what is the response of the `/oidc/script` request (which has the 302) in dev-mode? 

rebuilding container can be done via `bin/console cache:clear`

**Reply by MStumpp** [reply]
Response is actually empty. Header looks as follows:
![Bildschirmfoto 2022-05-09 um 18 41 22](https://user-images.githubusercontent.com/1505314/167457825-cca693aa-f47d-4f56-a045-e3d6a9a2224d.png)

I usually clear cache via admin portal (Cache => Clear Cache => All Caches) and did that several times.

**Reply by fashxp** [reply]
hmm ... just tried with a fresh installation with Pimcore 10.2.9 and it worked without any problems. 
Did you modify your `security.yaml`? Actually it must not redirect to `/auth/login` when calling `/oidc/script`

**Reply by MStumpp** [reply]
Used https://github.com/pimcore/skeleton as a starting point. 
security.yaml (https://github.com/pimcore/skeleton/blob/10.x/config/packages/security.yaml) looks as follows (just added portal_engine firewall settings on top of skeleton template):

```
security:
    providers:
        pimcore_admin:
            id: Pimcore\Bundle\AdminBundle\Security\User\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Pimcore WebDAV HTTP basic // DO NOT CHANGE!
        pimcore_admin_webdav:
            pattern: ^/admin/asset/webdav
            provider: pimcore_admin
            http_basic: ~

        # Pimcore admin form login // DO NOT CHANGE!
        pimcore_admin:
            anonymous: ~
            pattern: ^/admin(/.*)?$
            # admin firewall is stateless as we open the admin
            # session on demand for non-blocking parallel requests
            stateless: true
            provider: pimcore_admin
            logout:
                path:   /admin/logout
                target: /admin/login
                success_handler: Pimcore\Bundle\AdminBundle\Security\LogoutSuccessHandler
            guard:
                entry_point: Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator
                authenticators:
                    - Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator
            two_factor:
                auth_form_path: /admin/login/2fa                   # Path or route name of the two-factor form
                check_path: /admin/login/2fa-verify                # Path or route name of the two-factor code check
                default_target_path: /admin            # Where to redirect by default after successful authentication
                always_use_default_target_path: false  # If it should always redirect to default_target_path
                auth_code_parameter_name: _auth_code   # Name of the parameter for the two-factor authentication code
                trusted_parameter_name: _trusted       # Name of the parameter for the trusted device option
                multi_factor: false                    # If ALL active two-factor methods need to be fulfilled (multi-factor authentication)

        portal_engine: '%pimcore_portal_engine.firewall_settings%'

    access_control:
        # Pimcore admin ACl  // DO NOT CHANGE!
        - { path: ^/admin/settings/display-custom-logo, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/2fa-verify, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS}
        - { path: ^/admin/login/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS}
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/(login|lostpassword|deeplink|csrf-token)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_PIMCORE_USER }

    role_hierarchy:
        # Pimcore admin  // DO NOT CHANGE!
        ROLE_PIMCORE_ADMIN: [ROLE_PIMCORE_USER]
```
