### DISCUSSION TITLE
[E-commerce] Product filter for multiselect object brick field

### DISCUSSION THREAD

**Discussion by pzeglemon** [pimcore/pimcore#12156] [Q&A / Support]
Hello, 

```
# base-ecommerce.yaml
pimcore_ecommerce_framework:
    index_service:
        tenants:
            default:
                config_id: App\Ecommerce\IndexService\Config\MySqlConfig
                worker_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\DefaultMysql
                attributes:        
                    color:
                        type: varchar(255)
                        filter_group: multiselect
```

The code above is my attribute definition for multiselect type field. How this attribute definition will look like if the color field will be placed in object brick? 

Here is my object brick definition:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/93587923/169108413-7c0572b7-6648-4abc-8724-5d85de62bfc2.png">

<img width="712" alt="image" src="https://user-images.githubusercontent.com/93587923/169107943-c8460acf-9368-47f6-b71b-2d50b49e52a8.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/93587923/169107995-1b992fc6-fda3-41f2-b61c-3f9d35574a45.png">
