### DISCUSSION TITLE
what is the adapter name for azure blob storage?

### DISCUSSION THREAD

**Discussion by bluebrown** [pimcore/pimcore#12879] [Q&A / Support]
Hi, I am trying to configure flysystem for azure blob storage.

I ran `composer require league/flysystem-azure-blob-storage microsoft/azure-storage-blob` and then I added the below config, but I cannot figure out what is the name of the adapter.  When I run console commands, I get the following error. I have tried several variations for the name. Is there some documentation on what name belongs there?

```console
The service "pimcore.asset.storage" has a dependency on a non-existent service "azure".
```

```yaml
services:
    blobtest:
        class: 'MicrosoftAzure\Storage\Blob\BlobRestProxy'
        arguments:
            # the connection string for azurite
            - UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://blobstorage

flysystem:
    storages:
        pimcore.asset.storage:
            adapter: "azure"
            visibility: public
            options:
                client: "blobtest"
                bucket: "assets"
                prefix: assets
```

**Comment by dpfaffenbauer** [comment]
This is how we use it:

```
parameters:
    azure.storage.dsn: '%env(AZURE_STORAGE_DSN)%'
    azure.storage.cdn: '%env(AZURE_STORAGE_CDN)%'

services:
    azure.client.storage:
        class: MicrosoftAzure\Storage\Blob\BlobRestProxy
        factory: [ MicrosoftAzure\Storage\Blob\BlobRestProxy, createBlobService ]
        arguments:
            - '%azure.storage.dsn%'

    flysystem.adapter.azure.admin:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'admin'

    flysystem.adapter.azure.asset_cache:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'asset-cache' # underscores are not allowed in container names

    flysystem.adapter.azure.asset:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'asset'

    flysystem.adapter.azure.recycle_bin:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'recycle-bin' # underscores are not allowed in container names

    flysystem.adapter.azure.thumbnail:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'thumbnail'

    flysystem.adapter.azure.version:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'version'

    flysystem.adapter.azure.email:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'email'

flysystem:
    storages:
        pimcore.admin.storage:
            adapter: 'flysystem.adapter.azure.admin'
            visibility: private
        pimcore.asset.storage:
            adapter: 'flysystem.adapter.azure.asset'
            visibility: public
        pimcore.asset_cache.storage:
            adapter: 'flysystem.adapter.azure.asset_cache'
            visibility: private
        pimcore.recycle_bin.storage:
            adapter: 'flysystem.adapter.azure.recycle_bin'
            visibility: private
        pimcore.thumbnail.storage:
            adapter: 'flysystem.adapter.azure.thumbnail'
            visibility: public
        pimcore.version.storage:
            adapter: 'flysystem.adapter.azure.version'
            visibility: private
        pimcore.version.email:
            adapter: 'flysystem.adapter.azure.email'
            visibility: private


pimcore:
    assets:
        frontend_prefixes:
            source: '%azure.storage.cdn%/asset'
            thumbnail: '%azure.storage.cdn%/thumbnail'
```

.env

```
AZURE_STORAGE_DSN=DefaultEndpointsProtocol=https;AccountName=*****;AccountKey=*****;EndpointSuffix=core.windows.net
AZURE_STORAGE_CDN="https://*****.blob.core.windows.net"
```

**Reply by bluebrown** [reply]
Hi, thanks. 

We arrived at a similar config. I think the only difference is that we use only 2 container and then subdirectories within the containers. One for private things and one for public things.

The syntax feels a bit clunky IMO.

```yaml
services:
  blob-proxy:
    class: 'MicrosoftAzure\Storage\Blob\BlobRestProxy'
    factory:
      - 'MicrosoftAzure\Storage\Blob\BlobRestProxy'
      - createBlobService
    arguments:
      - "%env(AZURE_STORAGE_CONNECTION_STRING)%"

  blob-adapter-asset:
    class: 'League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter'
    arguments:
      - "@blob-proxy"
      - public
      - asset

  blob-adapter-asset_cache:
    class: 'League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter'
    arguments:
      - "@blob-proxy"
      - private
      - asset_cache

  blob-adapter-thumbnail:
    class: 'League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter'
    arguments:
      - "@blob-proxy"
      - public
      - thumbnail

  blob-adapter-version:
    class: 'League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter'
    arguments:
      - "@blob-proxy"
      - private
      - version

  blob-adapter-recycle_bin:
    class: 'League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter'
    arguments:
      - "@blob-proxy"
      - private
      - recycle_bin

  blob-adapter-admin:
    class: 'League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter'
    arguments:
      - "@blob-proxy"
      - private
      - admin

flysystem:
  storages:
    pimcore.asset.storage:
      adapter: blob-adapter-asset
      visibility: public

    pimcore.asset_cache.storage:
      adapter: blob-adapter-asset_cache
      visibility: private

    pimcore.thumbnail.storage:
      adapter: blob-adapter-thumbnail
      visibility: public

    pimcore.version.storage:
      adapter: blob-adapter-version
      visibility: private

    pimcore.recycle_bin.storage:
      adapter: blob-adapter-recycle_bin
      visibility: private

    pimcore.admin.storage:
      adapter: blob-adapter-admin
      visibility: private

pimcore:
  assets:
    frontend_prefixes:
      source: http://localhost:8080/devstoreaccount1/public/asset
      thumbnail: http://localhost:8080/devstoreaccount1/public/thumbnail
      thumbnail_deferred: /deferred-thumbnail
```


Seems also that you have an extra key: `pimcore.version.email` while missing the one for the `recycle_bin`.

I am also not sure what the purpose of `thumbnail_deferred` is.
