### DISCUSSION TITLE
NFS or SMB mount for assets storage

### DISCUSSION THREAD

**Discussion by revolution10** [pimcore/pimcore#12976] [Q&A / Support]
Hi,

we would like to have our assets separatelly from the server in a NAS. Is supported to mount a NFS or SMB share as a asset storage for Pimcore?

thank you

**Comment by BlackbitDevs** [comment]
Yes, this is possible. To PHP mounted remote volumes like NFS and SMB look the same as real local files. So you can either mount the remote volume under `<Pimcore root>/public/var/assets` or alternatively mount it somewhere else and change 
```yaml
flysystem:
    storages:
        pimcore.asset.storage:
            options:
                directory: /path/to/mounted/nfs/dir
``` 
in `/config/config.yaml`.
