### DISCUSSION TITLE
Testing Pimcore DataObject + REST API with Codeception

### DISCUSSION THREAD

**Discussion by Pimconaut** [pimcore/pimcore#13773] [Q&A / Support]
Hello,

I'm really new here and trying to understand, how can I use Codeception in my Pimcore Project. I have a no frontend, only the REST API and Pimcore DataObjects. Is it possible to test these sections with Codeecption?

I'm using the following packages:
`pimcore/pimcore`: 10.5.12
`codeception/codeception`: 4.2.2
`codeception/module-symfony`: 1.6.0
`codeception/module-rest`: 2.02

I have the following files:

*tests/codeception.yml* 
```yaml
namespace: Tests
actor:     Tester
bootstrap: _bootstrap.php
paths:
  tests:   .
  output:  ./_output
  data:    ./_data
  support: ./_support
  envs:    ./_envs
settings:
  colors: true
params:
  - ../.env.test
extensions:
  enabled:
    - Codeception\Extension\RunFailed
```

*Model.suite.yml*
```yaml
actor: ModelTester
modules:
  enabled:
    - \Pimcore\Tests\Helper\Model
    - \Pimcore\Tests\Helper\Pimcore:
        connect_db:   true
        cache_router: false
    - \Pimcore\Tests\Helper\ClassManager
```

*composer.json*
```json
{
...
"autoload-dev": {
    "psr-4": {
      "Tests\\Api\\": "tests/Api",
      "Tests\\Unit\\": "tests/Unit",
      "Tests\\Functional\\": "tests/Functional",
      "Tests\\Model\\": "tests/Model"
    }
}
```

I'm getting an exception on run: 

```bash
$ docker-compose exec php bash -c 'APP_ENV="test" PIMCORE_TEST_DB_DSN="mysql://root:ROOT@db:3306/pimcore_test" vendor/bin/codecept run -c tests/codeception.yml'
```

<img width="919" alt="Bildschirm­foto 2022-12-09 um 10 37 28" src="https://user-images.githubusercontent.com/120173064/206671658-ca961cf5-f951-4d74-a653-ed5d64f02530.png">

---
That would be really nice if someone could show me a real example on a real project, because there is no any info in internet, how can I test:

a) Pimcore DataObjects
b) REST API (using JWT authentication for Pimcore DataObject)

Thank you a lot

Best regards
