### DISCUSSION TITLE
how to implement Customer Save Handlers?

### DISCUSSION THREAD

**Discussion by BjBue** [pimcore/pimcore#13819] [Q&A / Support]
Hello Ladies and Gentlemen,

i try to implement the CMF (CustomerManagementFramework) and want to use the inbuild saveHandlers.
But poorly i do not understand how.
I configured the cmf.yaml like the demo-project but with my own needs.
I use the customer->save()-Method, but the preSave or postSave method is never called.
I was looking in the demoproject if there is a hint but i do not find anything.
Does anybody has an idea where i find a demo how to implement the preSave or postSave method in the customer-save workflow and how to implement the validations before saving a customer?
Thank you a lot

**Comment by mattamon** [comment]
Hey @BjBue,

The CMF uses event listeners. 

Here are some basics for [EventListeners](https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Event_API_and_Event_Manager.html)

The import thing is to register an event to your EventListener.
```yaml
services:
    App\EventListener\TestListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onPreUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onPostUpdate }
```

In the example above there are two events the preUpdate -> preSave and the postUpdate -> postSave
All data object events you can find [here](https://github.com/pimcore/pimcore/blob/10.5/lib/Event/DataObjectEvents.php)

Be aware that the event listener is called for every object so you have to make sure that you only operate e.g. on the Customer Object.
You can do this with an ```php instanceof ``` check.

```php
<?php
namespace App\EventListener;
  
class TestListener {
     
    public function onPreUpdate (ElementEventInterface $e) {
       
        if($e instanceof Customer) {
            // do something with the asset
            $foo = $e->getAsset(); 
       }
    }
}
```

Could you provide your service definitions and the Classes you implemented?
Some more basic infos on the Customer Save Manager [here](https://pimcore.com/docs/customer-management-framework/current/CustomerSaveManager.html)
