### DISCUSSION TITLE
is it possible to use the Symfony MakerBundle with Pimcore to generate Controllers/Entities ?

### DISCUSSION THREAD

**Discussion by YassinS** [pimcore/pimcore#14127] [Q&A / Support]
Hello everyone,

does the Symfony MakerBundle work in conjunction with Pimcore? e.g.  `php bin/console make:entity` ? If it does indeed work how would one go about doing that? I have read the documentation for [custom persistent models and decided to go with option 1.](https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Custom_Persistent_Models.html)

Any help would be greatly appreciated
 
EDIT:
No it is not possible, since the MakerBundle is specifically made for symfony. As soon as there's a fork for the MakerBundle to support Pimcore this edit can be disregarded.

**Comment by StefanRickli** [comment]
Yes, it is possible (only tested with Entities). Configuration has its limits though because maker has some hard-coded parts in the paths.

Here's how everything comes together. It's 3am and I hope I didn't make any mistake in transferring my handwritten notes 🙈. Also, I had to anonymize some folder names:
![image](https://github.com/pimcore/pimcore/assets/19881323/4eb2404a-dfb2-4401-a60e-f7a9f82f0935)

Be aware that some configs are sensitive to the order in which they appear because maker, if I recall correctly, doesn't handle multiple entity managers well. That is why I chose to namespace multiple systems/ORMs as I did above.

```yaml
# config/local/database.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                host: 'db'
                port: '3306'
                server_version: 'pimcore_server_version'
                dbname: 'pimcore_dbname'
                user: 'pimcore_user'
                password: 'pimcore_password'
                mapping_types:
                    enum: string
                    bit: boolean
            sys1:
                host: 'sys1_host'
                port: 'sys1_port'
                server_version: 'sys1_server_version'
                dbname: 'sys1_dbname'
                user: 'sys1_user'
                password: 'sys1_password'
    orm:
        default_entity_manager: sys1
        entity_managers:
            sys1:
                connection: sys1
                mappings:
                    mapping1:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/OwnORM/Entity/Sys1'
                        prefix: 'App\OwnORM\Entity\Sys1'
                        # Alias: to be used as short in DQL, i.e. SELECT p FROM SYS1:Product instead of App\Sys1\Entity\Product
                        alias: SYS1
```

```yaml
# config/packages/dev/maker.yaml
maker:
    root_namespace: App\OwnORM
```

```yaml
# config/services.yaml
services:
    _defaults:
        # Since we might have multiple entity managers in future, we already now define
        # an alias for the Sys1 Entity Manager, to be used for dependency injection.
        # I have not tested if everything works with multiple entity managers, though.
        bind:
            $Sys1EntityManager: '@doctrine.orm.sys1_entity_manager'
    App\OwnORM\:
        resource: '../src/OwnORM/'
        exclude:
            - '../src/OwnORM/Entity/'
```

Then you can use the entities in your controller:
```php
    public function testSelectLineORM(EntityManagerInterface $Sys1EntityManager): JsonResponse
    {
        $em = $Sys1EntityManager;

        $query = $em->createQuery("SELECT p FROM SYS1:Product p");
        dd($query->getResult());

        return new JsonResponse();
    }

    // This works as well if you only have one entity manager
    public function testSelectLineORM(EntityManagerInterface $em): JsonResponse
    { ... }
```
