### DISCUSSION TITLE
redis cache pimcore 6 vs pimcore 10

### DISCUSSION THREAD

**Discussion by thgross** [pimcore/pimcore#14306] [Q&A / Support] [answered]
I am trying to understand the difference in redis configurations between pimcore 6 and pimcore 10.

In pimcore 6, you had to configure a database:
`database: 0`

We are running multiple pimcore 6 installations on the same server, so I figured it would be neccessary to give each installation it's own database-ID: 0, 1, 2 etc.

But with pimcore 10, there is no `database` setting. Now I'm not sure how to seperate the caches for our multiple installations. Or maybe I am completely wrong about that `database` setting.

I just want to make sure that there is no mixup between the caches for multiple pimcore installations, (pimcore 6 and pimcore 10) on the same server.

Can someone please explain this to me?

**Comment by jdreesen** [comment, marked as answer]
I suggest using multiple Redis processes (one per instance). Redis is a very lightweight software, so running multiple instances is not a problem. Also, Redis is *single-threaded*, so if you put multiple Pimcore instances into multiple databases of the *same* Redis instance, everything will be processed in *a single thread*. If you launch multiple Redis instances, they will be processed in multiple threads, which should be more performant.

**Reply by thgross** [reply]
Thanks. With seperate instances, I don't have to worry about DB-Ids.

I also found that I can choose different DB-Ids by changing the provider setting, for example `redis://localhost/2` for DB-ID 2.

**Reply by solverat** [reply]
ah you already figured it out. :)

**Comment by solverat** [comment]
@thgross:

```yaml
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 31536000  # 1 year
                adapter: pimcore.cache.adapter.redis_tag_aware
                provider: 'redis://localhost:6379/4'
```

Where `/4` represents your redis db index.
