### DISCUSSION TITLE
UnitTest Controllers: How to authenticate a user?

### DISCUSSION THREAD

**Discussion by chm0815** [pimcore/pimcore#14567] [Q&A / Support] [answered]
I try to unit test controllers with simple phpunit. This works in general fine, however I did not find and easy way to authenticate users before sending the request. 
There is the [loginUser()](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Bundle/FrameworkBundle/KernelBrowser.php#method_loginUser) method from Symfony, but so far I was not successful.
Does anybody know how to test controllers behind a Symfony firewall?

```php
class ControllerTest extends WebTestcase
{
    protected function setUp(): void
    {
    }
    public function testDefault()
    {
        $client = static::createClient();
        $admin = \Pimcore\Model\User::getByName('admin');

        $p = new \Pimcore\Bundle\AdminBundle\Security\User\UserProvider();
        $a = $p->loadUserByIdentifier("admin");
        
        $client->loginUser($a);
        // $client->loginUser($a, "pimcore_admin"); does also not work

        $client->request('GET', '/admin/xyz');
        $client->followRedirect(); 
        $this->assertResponseIsSuccessful();
    }
}
```

This is my session configuration:
```yaml
framework:
    test: true
    session:
        handler_id:  session.handler.mock_file
        #cookie_samesite: 'strict'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.mock_file
```
