### DISCUSSION TITLE
Upgrading v6.9 to v10 - Core migration fails

### DISCUSSION THREAD

**Discussion by JohEngstrom** [pimcore/pimcore#14823] [Q&A / Support] [answered]
I'm attempting to upgrade Pimcore from version 6.9 to version 10.

When I run the core migration script `./bin/console doctrine:migrations:migrate --prefix=Pimcore\\Bundle\\CoreBundle` it runs for a while then fails with the following:

`[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20210324152822 failed during Execution. Error: "The table with name 'pimcore.object_brick_query_obconfiguratorstaticstepconfirmation_77' already exists.`

`In SchemaException.php line 112: The table with name 'pimcore.object_brick_query_obconfiguratorstaticstepconfirmation_77' already exists.`

Should you have to delete tables from the database to do the upgrade or should the core migrations handle this?

Thanks for any help on this.

**Comment by dpfaffenbauer** [comment]
did you change the database in the mean time? I guess your database was configured to be lower-case only table names, now its not anymore. Maybe you are using the wrong DATABASE_VERSION doctrine configuration. Something like that

**Reply by JohEngstrom** [reply]
Thanks for the reply. Where can I find this DATABASE_VERSION config?

**Reply by JohEngstrom** [reply]
Oh and also we're moving from MySQL to MariaDB so maybe you're on the right track.

**Reply by dpfaffenbauer** [reply]
```bin/console debug:config doctrine | grep server_version```

Usually the config is defined in `config/config.yaml` or somewhere in the config folder in general

**Reply by JohEngstrom** [reply]
Old: ``server_version: 5.7``

New: `server_version: '10.7.8-MariaDB-1:10.7.8+maria~ubu2004'`

**Reply by dpfaffenbauer** [reply]
Are the right versions set for the migration?

**Reply by JohEngstrom** [reply]
Sorry for all the stupid questions. Where would I do that? In the doctrine:migrations:migrate command?

**Reply by dpfaffenbauer** [reply]
This is our doctrine config:

```yaml
doctrine:
    dbal:
        connections:
            default:
                driver: '%database_driver%'
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: 'utf8mb4'
                mapping_types: { enum: string, bit: boolean }
                server_version: '%env(DATABASE_VERSION)%'

```

We configure it purely via Env Vars, here you can see where the server_version is configured, you can configure it direcly like:

```yaml
doctrine:
    dbal:
        connections:
            default:
                server_version: '10.7.8-MariaDB-1:10.7.8+maria~ubu2004'
```
