### DISCUSSION TITLE
CustomerManagementFrameworkBundle and E-commerce bundle setup for test

### DISCUSSION THREAD

**Discussion by LeonNoBears** [pimcore/pimcore#14884] [Q&A / Support] [answered]
Greetings Pimconauts,

I'm breaking my head over a small coding challenge so I thought I should ask the community for help 😉 
For some time I have been trying to setup an application / acceptance test where I test a registration form, the "problem" I keep running against is that it's missing the tables and classes that are created by the  CustomerManagementFrameworkBundle and the E-commerce bundle and if I read the documentation's correctly:

> The Pimcore module is able to drop and re-create the database and addtional modules like the ClassManager provide helper code to create Pimcore classes from JSON exports. As the DB initialization is configurable, you should be able to use the module as you need it - [source](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Testing/Application_Testing.html#page_Application-Testing)

I have either the option to use the `\Pimcore\Tests\Helper\ClassManager` and export all my classes to JSON and use a `_beforeSuite` function to import these classes. This is not my really a great options for my situation since classes are changed often, reuploading them is tiresome, and it doesn't create the additional tables (as far as I can see).

The other option it gives us is using Pimcore's test helpers, they already have their own `_beforeSuite` function and creates the classes and run's their respective installers. This is exactly what I'm looking for but when calling for `\CustomerManagementFrameworkBundle\Tests\Helper\Model` (vendor/pimcore/customer-management-framework-bundle/tests/_support/Helper/Model.php) it returns the following error:

```
In ModuleContainer.php line 117:

Module \CustomerManagementFrameworkBundle\Tests\Helper\Model could not be found and loaded  
```

If I try the E-commerce bundle helper  `\Pimcore\Tests\Helper\Ecommerce`  (vendor/pimcore/pimcore/tests/_support/Helper/Ecommerce.php) I hit a different problem.
```
In Container.php line 271:
                                                             
You have requested a non-existent service "Pimcore\Bundle\EcommerceFrameworkBundle\Tools\Installer". 
```

below I add a snippet of my suite, I hope you guys can help me with this setup. 👨🏻‍🚀 

```yaml
actor: Acceptance
modules:
    enabled:
        - \Tests\Helper\Acceptance
        - \Pimcore\Tests\Helper\Pimcore:
            # CAUTION: the following config means the test runner
            # will drop and re-create the Pimcore DB and purge var/classes
            # use only in a test setup (e.g. during CI)!
            connect_db: true
            initialize_db: true
            purge_class_directory: false
            # If true, it will create database structures for all definitions
            setup_objects: true
            url: http://foo.localhost.nl
#        - \Pimcore\Tests\Helper\Ecommerce
#        - \CustomerManagementFrameworkBundle\Tests\Helper\Model
        - \Tests\Helper\Factories
```
