### DISCUSSION TITLE
Hiding js/routing url for security reason?

### DISCUSSION THREAD

**Discussion by stormwind84** [pimcore/pimcore#15400] [General]
Dear All,
I was wondering if having the js/routing exposed could lead to potential security issues (e.g. for the listing of methods, see https://demo.pimcore.com/js/routing); wouldn't it be possible to expose it only to logged-in users?

Thank you,
Greetings,
/Bob

**Comment by NiklasBr** [comment]
That's not a security issue, one should always use proper authentication rather than relying on obscurity.

Symfony has support for many types of authentication, including HTTP Basic which is easy to set up. I suggest you check the section on https://symfony.com/doc/current/security.html which deals access control on specific routes if you need to prevent unauthenticated users from getting any data:

```yaml
security:
    access_control:
        - { path: ^/your/sensitive/data, roles: ROLE_ADMIN }
        - { path: ^/some/locked/content, roles: ROLE_USER }
```
