### DISCUSSION TITLE
Should pimcore.temp.storage be stored on an S3 bucket?

### DISCUSSION THREAD

**Discussion by ayoob-lfc** [pimcore/pimcore#15602] [Q&A / Support]
Hi,

I'm using kubernetes and I have separated my file systems so that they are stored in an S3 bucket.

My question is, that when creating a flysystem.yaml config file, do I also need to save the tmp folder to the S3 bucket?

i.e:

```
        pimcore.temp.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'temp'
```
