### DISCUSSION TITLE
Update from 6.9 to 10.6 and problem with SessionBagInterface "pimcore_admin" is not registered

### DISCUSSION THREAD

**Discussion by ziggurad** [pimcore/pimcore#15805] [Q&A / Support]
Hello!

for a few days I've been working on updating the project from pimcore 6.9 to 10.6

Everything works fine on my local environment. After deploying to the qa environment, I have one problem. The login form (admin panel) displays, I log in and then nothing is displayed.

In the console I see 500 during request to: /js/routing?callback=fos.Router.setData

In Sentry I see an error:
Uncaught PHP Exception InvalidArgumentException: "The SessionBagInterface "pimcore_admin" is not registered." at /var/www/pimcore/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 346

Can anyone give me a clue what could be the reason? On the local dev environment everything works fine.

security.yaml (I was based on pimcore demo repository)
```
security:
    enable_authenticator_manager: true

    providers:
        pimcore_admin:
            id: Pimcore\Bundle\AdminBundle\Security\User\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Pimcore WebDAV HTTP basic // DO NOT CHANGE!
        pimcore_admin_webdav:
            pattern: ^/admin/asset/webdav
            provider: pimcore_admin
            http_basic: ~

        # Pimcore admin form login // DO NOT CHANGE!
        pimcore_admin:
            pattern: ^/admin(/.*)?$
            # admin firewall is stateless as we open the admin
            # session on demand for non-blocking parallel requests
            stateless: true
            provider: pimcore_admin
            login_throttling:
                max_attempts: 3
                interval: '5 minutes'
            logout:
                path: pimcore_admin_logout
                target: pimcore_admin_login
            custom_authenticators:
                - Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminLoginAuthenticator
                - Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminTokenAuthenticator
                - Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminSessionAuthenticator
            two_factor:
                auth_form_path: /admin/login/2fa                   # Path or route name of the two-factor form
                check_path: /admin/login/2fa-verify                # Path or route name of the two-factor code check
                default_target_path: /admin            # Where to redirect by default after successful authentication
                always_use_default_target_path: false  # If it should always redirect to default_target_path
                auth_code_parameter_name: _auth_code   # Name of the parameter for the two-factor authentication code
                trusted_parameter_name: _trusted       # Name of the parameter for the trusted device option
                multi_factor: false                    # If ALL active two-factor methods need to be fulfilled (multi-factor authentication)

    access_control:
        # Pimcore admin ACl  // DO NOT CHANGE!
        - { path: ^/admin/settings/display-custom-logo, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login/2fa-verify, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS}
        - { path: ^/admin/login/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS}
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login/(login|lostpassword|deeplink|csrf-token)$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_PIMCORE_USER }

    role_hierarchy:
        # Pimcore admin  // DO NOT CHANGE!
        ROLE_PIMCORE_ADMIN: [ROLE_PIMCORE_USER]
```
framework.yml
```
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
#    session:
#        handler_id: null
#        cookie_secure: auto
#        cookie_samesite: lax
#        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```
config.yml:
```
imports:
    - { resource: parameters.yaml }
    - { resource: services.yaml }
    - { resource: 'local/' }

parameters:
    pimcore_url: (***)
    process_time_limit: 540
    run_with_day_interval: true
    day_interval: 14

    s3_bucket_name: '%env(S3_BUCKET_NAME)%'
    s3_version: '%env(S3_VERSION)%'
    aws_default_region: '%env(AWS_DEFAULT_REGION)%'
    aws_access_key_id: '%env(AWS_ACCESS_KEY_ID)%'
    aws_secret_access_key: '%env(AWS_SECRET_ACCESS_KEY)%'

doctrine:
    dbal:
        connections:
            default:
                mapping_types:
                    enum: string
                    bit: boolean
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true

pimcore:

# IMPORTANT Notice!
# Following there are only some examples listed, for a full list of possible options, please run the following command:
# ./bin/console debug:config pimcore
# you can also filter them by path, eg.
# ./bin/console debug:config pimcore assets
# or even more specific:
# ./bin/console debug:config pimcore assets.image


#### TRANSLATIONS
#    translations:
#        case_insensitive: true

#### REDIS CACHE
#    cache:
#        pools:
#            redis:
#                enabled: true
#                connection:
#                    server: localhost
#                    database: 14

#### FEATURE FLAGS
#    flags:
#        zend_date: true

#### CLASS OVERRIDES EXAMPLES
#    models:
#        class_overrides:
#            'Pimcore\Model\DataObject\News': 'AppBundle\Model\DataObject\News'
#            'Pimcore\Model\DataObject\News\Listing': 'AppBundle\Model\DataObject\News\Listing'
#            'Pimcore\Model\DataObject\Folder': 'AppBundle\Model\DataObject\Folder'
#            'Pimcore\Model\Asset\Folder': 'AppBundle\Model\Asset\Folder'
#            'Pimcore\Model\Asset\Image': 'AppBundle\Model\Asset\Image'
#            'Pimcore\Model\Document\Page': 'AppBundle\Model\Document\Page'
#            'Pimcore\Model\Document\Link': 'AppBundle\Model\Document\Link'
#            'Pimcore\Model\Document\Listing': 'AppBundle\Model\Document\Listing'


#### CUSTOM DOCUMENT EDITABLES
#    documents:
#        tags:
#            map:
#                markdown: \AppBundle\Model\Document\Tag\Markdown


#### CUSTOM OBJECT DATA TYPES
#    objects:
#        class_definitions:
#            data:
#                map:
#                  myDataType: \AppBundle\Model\DataObject\Data\MyDataType


#### ASSET CUSTOM SETTINGS
#    assets:
#        versions:
#            use_hardlinks: false
#        image:
#            low_quality_image_preview:
#                enabled: false
#                generator: imagick
#            thumbnails:
#                webp_auto_support: false


#### SYMFONY OVERRIDES
framework:

#### USE SESSION HANDLER CONFIGURED IN php.ini
#    session:
#        handler_id: null

flysystem:
    storages:
        local.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
```
