### DISCUSSION TITLE
Token storage having empty value

### DISCUSSION THREAD

**Discussion by nehagaur89** [pimcore/pimcore#15801] [Q&A / Support]
Hello Everyone,

```
    public function __construct(
        TokenStorageUserResolver $userResolver,
        TokenStorageInterface $tokenStorage
    ) {
            $token = $tokenStorage->getToken();
            $resolver = \Pimcore::getContainer()->get('pimcore_admin.security.token_storage_user_resolver');
           $this->user = $resolver->getUser();
    }
```

 I am getting nothing here and not able to proceed with my bundle. 
 
 This is for a custom bundle and controller is extending AdminController.
    
 Kindly help

**Comment by nehagaur89** [comment]
Can someone please reply on this. Thanks

**Reply by dvesh3** [reply]
Did you try to get the user from `$userResolver`? I don't why you are getting the service directly from container even though you have injected it (maybe for debugging purpose?).

**Reply by nehagaur89** [reply]
Hi @dvesh3 ,

Yes for debugging purpose only I tried it again directly from container. 

I need user from TokenStorageUserResolver or TokenStorageInterface. I have tried with both. But token storage values are null. 

This is the case of custom bundle.

**Reply by dvesh3** [reply]
and how the controller action is called? basically your request has to be in admin firewall to get the user from TokenStorageResolver

**Comment by nehagaur89** [comment]
```
 App\CsvImportBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
        arguments:
            - '@pimcore_admin.security.token_storage_user_resolver'
```

I know this is just for arguments , but other than this I have not specified it anywhere in firewall etc. 

I have provided like this in services.yml file of my bundle. 

Controller action is called via ajax.

It is CSVImport (for data objects) Functionality of Pimcore 6 which I am trying to upgrade to 10 and getting this error in importupload.
