### DISCUSSION TITLE
Workflows issue when upgrading to Pimcore 11 in instances created before 5.5.0

### DISCUSSION THREAD

**Discussion by bramstroker** [pimcore/pimcore#15828] [Q&A / Support] [answered]
### Pimcore version

11.0.7

### Steps to reproduce

We just upgrade our large pimcore installation on acceptance to Pimcore 11. Workflows are completely broken for me in Pimcore 11.

I have a workflow with different places defined:

```yaml
pimcore:
  workflows:
    product_review:
      label: 'Product review Workflow'
      type: 'state_machine'
      supports:
        - 'Pimcore\Model\DataObject\ProductReview'
      places:
        initial:
          label: 'Initial state'
          color: '#377ea9'
        new:
          label: 'New review'
          color: '#377ea9'
        rejected:
          label: 'Rejected review'
          color: '#ff4144'
        accepted:
          label: 'Accepted review'
          color: '#28a013'
      initial_markings: [initial]
      transitions:
        new_review:
          from: initial
          to: new
          options:
            label: 'New review'
        reject_review:
          from: new
          to: rejected
          options:
            label: 'Reject the review'
        accept_review:
          from: new
          to: accepted
          options:
            label: 'Accept the review'
            changePublishedState: force_published
```

Next try to execute a state transition.

```php
$workflow = $this->workflowRegistry->get($productReview, 'product_review');
if (!$workflow->can($productReview, 'new_review')) {
    return;
}

$workflow->apply($productReview, 'new_review');
```

### Actual Behavior

Following error is raised:

`Key \"`workflowId`\" passed for upsert not found in data`

I have tracked the issue down to be in `\Pimcore\Db\Helper::upsert`

![Screenshot 2023-08-24 at 14 10 54](https://github.com/pimcore/pimcore/assets/2345875/4f42ab20-861f-4040-b9ec-d178be14e501)

Here the composite key of the table consists of 4 columns
- cid
- ctype
- workflowId
- workflow

However in the data value for workflowId is missing.

I cannot find any reference where `workflowId` should be set in the codebase, and there are no comments on `workflowId` column in the DB definitions which explain it's purpose.
Not sure what this needs to be in the first place as it seems superfluous with `workflow` and it's not foreign key to another table whatsoever.

### Expected Behavior

State transition is working correctly as it was in Pimcore 10.
