### DISCUSSION TITLE
The controller for URI "/" is not callable.

### DISCUSSION THREAD

**Discussion by M-Ali-Aziz** [pimcore/pimcore#15918] [Q&A / Support]
Pimcore version: 10.6.9

Hi,
After Upgrading Pimcore from Version 6.x to Version 10 using this [document](https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/V6_to_V10.html) I get error and homepage doesn’t  work.
I'd done all steps and after running `COMPOSER_MEMORY_LIMIT=-1 composer update` and then `./bin/console doctrine:migrations:migrate --prefix=Pimcore\\Bundle\\CoreBundle` I get no errors and everything is green.

When I gå to the homepage I get the following error:
```
The controller for URI "/" is not callable: Controller "AppBundle\Controller\ContentController" does neither exist as service nor as class.
```

composer.json
```
...

  "autoload": {
    "psr-4": {
      "App\\": "src/",
      "Pimcore\\Model\\DataObject\\": "var/classes/DataObject"
    }
  },

...
```

config/services.yaml

```
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]
  ...
```

src/Controller/ContentController.php
```
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ContentController extends BaseController
{
    [#Template]
    public function startAction(Request $request)
    {
        return ['startsite' => true];
    }
}
```

In the database `documents_page` table:
```
SELECT * FROM documents_page WHERE id = 2;
controller => AppBundle\Controller\ContentController::startAction
```

I tried the following but still get error:
1. On `database` changed controller data for this page from `AppBundle\...` to `App\...` and save the database.

I also  tried the following but still get error:
1. Changed namespace on `ContentController.php` from `App\Controller` to `AppBundle\Controller`
2. Add `"AppBundle\\": "src/",` on composer.json under `autoload`.

Any help please!
