### DISCUSSION TITLE
Creating New Custom Calculated Value

### DISCUSSION THREAD

**Discussion by kara-hyyyper** [pimcore/pimcore#16119] [Q&A / Support]
I am new to Pimcore, and after a lot of effort I cannot figure out how to create a custom calculated value.

This is the error. I'm getting this every time I try to open my test product in the pimcore app.

```
Status: 500 | Internal Server Error
URL: /admin/object/get
Message: You have requested a non-existent service "App\Model\Product\CalculatedValue\TestCalculator". Did you mean one of these: "App\Model\Product\CalculatedValue\AccessoryPartName", "App\Model\Product\CalculatedValue\QualityCalculator"?
```

My goal is to make a product ID (or SKU) from other data provided in an object. 

Here is how my new calculated value is defined in the Classes tab:
![image](https://github.com/pimcore/pimcore/assets/125572770/bdec66e6-44de-4e2a-9972-93a39e621edb)

Here is my code for my custom calculator located in the same location as the other calculators (/opt/bitnami/pimcore/src/Model/Product/CalculatedValue/TestCalculator.php)
```php
namespace App\Model\Product\CalculatedValue;

use App\Model\Product\AccessoryPart;
use Pimcore\Model\DataObject\ClassDefinition\CalculatorClassInterface;
use Pimcore\Model\DataObject\Concrete;
use Pimcore\Model\DataObject;
use Pimcore\Model\DataObject\Data\CalculatedValue;

class TestCalculator implements CalculatorClassInterface
{
    public function compute(Concrete $object, CalculatedValue $context): string
    {
        if ($context->getFieldname() == "sum") {
            $language = $context->getPosition();
            return $object->getFinish($language) +  $object->getStyleCode($language);
        } else {
            return "error";
        }
    }

    public function getCalculatedValueForEditMode(Concrete $object, CalculatedValue $context): string 
    {
        $language = $context->getPosition();
        $result = $this->compute($object, $context);
        return $result;
    }
} 

```
I used [this link](https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Calculated_Value_Type/) to help me create this file. I had to remove the `\Logger::error("unknown field");` section because I was getting errors every time saying I was missing a "use" definition. 

I've already added the required info to "services.yaml".

```yaml
    # ---------------------------------------------------------
    # Misc Services
    # ---------------------------------------------------------
    # ...

    App\Model\Product\CalculatedValue\QualityCalculator:
        public: true

    App\Model\Product\CalculatedValue\AccessoryPartName:
        public: true

    App\Model\Product\CalculatedValue\TestCalculator:
        public: true
```

I am no longer getting any error messages in the backend, but every time I try to open my test product in the pimcore app I get the same error message: 
```
Status: 500 | Internal Server Error
URL: /admin/object/get
Message: You have requested a non-existent service "App\Model\Product\CalculatedValue\TestCalculator". Did you mean one of these: "App\Model\Product\CalculatedValue\AccessoryPartName", "App\Model\Product\CalculatedValue\QualityCalculator"?
```

The only difference I can see in the backend between my "TestCalculator" and the other calculators like "AccessoryPartName" and "QualityCalculator" is that they seem to be logged in a file location "/opt/bitnami/pimcore/dump/data-1-settings_store.sql" and my "TestCalculator" is not. 

How do I fix this issue?
