### DISCUSSION TITLE
Pimcore 11 backend session duration

### DISCUSSION THREAD

**Discussion by valentin-** [pimcore/pimcore#16513] [Q&A / Support] [answered]
Hi, as explained in https://github.com/pimcore/pimcore/discussions/7834 I've increased the session lifetime to keep the backend login active for one day.

It works fine for me, but the client keeps telling they are getting logged out every 2-3 hours. The cookie is set correctly.

Can there be any other reasons why the client get logged out earlier then expected?

Thanks,
Valentin

**Comment by rberneder** [comment, marked as answer]
We had a similar problem – our root cause were the PHP garbage collection settings `gc_maxlifetime` and `gc_probability`.
After adding these settings, our problems were resolved.
```yml
framework:
    session:
        cookie_lifetime: 43200 # 12h
        gc_maxlifetime: 43200
        gc_probability: 3000
```
