### DISCUSSION TITLE
After implement azure container not able to delete assets

### DISCUSSION THREAD

**Discussion by rushitkhunt1996** [pimcore/pimcore#16649] [Q&A / Support]
Hi,
I am not able to delete Assets after implement Azure container for Asset storage. 
Below is my configuration for Azure.

filesystem.yaml
```
services:
    MicrosoftAzure\Storage\Blob\BlobRestProxy:
        factory: ['MicrosoftAzure\Storage\Blob\BlobRestProxy', 'createBlobService']
        arguments:
            - '%env(connectionString)%'

    League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter:
        arguments:
            $client: '@MicrosoftAzure\Storage\Blob\BlobRestProxy'
            $container: '%env(containerName)%'

flysystem:
    storages:
        pimcore.asset.storage:
            adapter: 'League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter'
            visibility: 'public'
        pimcore.thumbnail.storage:
            adapter: 'League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter'
            visibility: 'public'
```

config.yaml

```
pimcore:
    assets:
        frontend_prefixes:
           # Prefix used for the original asset files
           source: https://xxxxxx.windows.net/containerName/assets
           # Prefix used for all generated image & video thumbnails
           thumbnail: https://xxxxxx.windows.net/containerName/assets
```

with this configuration Assets are get uploaded on Azure and thumbnail also created
Below is the azure folder structure
![image](https://github.com/pimcore/pimcore/assets/60934941/daff68fa-e8b3-4e00-845c-b81b132efbd6)

when I am going to delete this assets from PIMCORE admin I am facing below error
![image](https://github.com/pimcore/pimcore/assets/60934941/a7a250fc-c9e5-4790-9cc9-d820db259f23)

If anyone has any idea please guide me.

**Comment by dpfaffenbauer** [comment]
we got it configured like this:

```
parameters:
    azure.storage.dsn: '%env(AZURE_STORAGE_DSN)%'

services:
    azure.client.storage:
        class: MicrosoftAzure\Storage\Blob\BlobRestProxy
        factory: [ MicrosoftAzure\Storage\Blob\BlobRestProxy, createBlobService ]
        arguments:
            - '%azure.storage.dsn%'

    flysystem.adapter.azure.admin:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'admin'

    flysystem.adapter.azure.asset_cache:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'asset-cache' # underscores are not allowed in container names

    flysystem.adapter.azure.asset:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'asset'

    flysystem.adapter.azure.recycle_bin:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'recycle-bin'

    flysystem.adapter.azure.thumbnail:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'thumbnail'

    flysystem.adapter.azure.version:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'version'

    flysystem.adapter.azure.email:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'email'

    flysystem.adapter.azure.temp:
        class: League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter
        arguments:
            $client: '@azure.client.storage'
            $container: 'temp'

flysystem:
    storages:
        pimcore.admin.storage:
            adapter: 'flysystem.adapter.azure.admin'
            visibility: private
        pimcore.asset.storage:
            adapter: 'flysystem.adapter.azure.asset'
            visibility: public
        pimcore.asset_cache.storage:
            adapter: 'flysystem.adapter.azure.asset_cache'
            visibility: private
        pimcore.recycle_bin.storage:
            adapter: 'flysystem.adapter.azure.recycle_bin'
            visibility: private
        pimcore.thumbnail.storage:
            adapter: 'flysystem.adapter.azure.thumbnail'
            visibility: public
        pimcore.version.storage:
            adapter: 'flysystem.adapter.azure.version'
            visibility: private
        pimcore.email.storage:
            adapter: 'flysystem.adapter.azure.email'
            visibility: private
        pimcore.temp.storage:
            adapter: 'flysystem.adapter.azure.temp'
            visibility: private
```
