### DISCUSSION TITLE
Different mailers in same config

### DISCUSSION THREAD

**Discussion by manuelkleinert** [pimcore/pimcore#16788] [Q&A / Support] [answered]
Hey, does anyone know how I can define 2 different mailers for different websites in the same instance and send them in the mail or use them depending on the domain.

config.yaml:
```
pimcore:
    email:
        sender:
            name: \<name>
            email: \<email>
        return:
            name: \<name>
            email: \<email>

framework:
   mailer:
       transports:
           main: \<smtp config>
           pimcore\_newsletter: \<smtp config>
```

**Comment by manuelkleinert** [comment, marked as answer]
I have now solved the problem, but I don't know if this is the best way.

``` yaml

# pimcore:   ==>    pimcore sender commented out 
#    email:
#        sender:
#            name: \<name>
#            email: \<email>
#        return:
#            name: \<name>
#            email: \<email>


framework:
   mailer:
       transports:
           main: <smtp config 1>
           demo: <smtp config 2>
```

```php
$mail = new Mail();
$mail->getHeaders()->addTextHeader('X-Transport', 'demo');
```
