### DISCUSSION TITLE
Connect to OneDrive Business for asset storage

### DISCUSSION THREAD

**Discussion by NoopNetwork** [pimcore/pimcore#16820] [Q&A / Support]
Hi all,

I am new to Pimcore and to Symfony, so sorry in advance if I ask dump questions.

I am struggling to use OneDrive Business as an asset storage. I installed shitware-ltd/flysystem-msgraph and my configuration currently looks like this (stored in /config/packages/flysystem.yaml):
```
parameters:
    msgraph.accessToken: '%env(MSGRAPH_ACCESSTOKEN)%'
    msgraph.driveId: '%env(MSGRAPH_DRIVEID)%'

services:
    msgraph.client:
        class: 'Microsoft\Graph\Graph'
        calls:
            - [setAccessToken, ['%msgraph.accessToken%']]

    flysystem.adapter.msgraph:
        class: 'ShitwareLtd\FlysystemMsGraph\Adapter'
        arguments:
            $graph: '@msgraph.client'
            $drive_id: '%msgraph.driveId%'
            $options: []

flysystem:
    storages:
        pimcore.asset.storage:
            adapter: 'flysystem.adapter.msgraph'
            visibility: public
```

**My problems are:**

1. The configuration does not seem to work. When interacting with the Asses in the admin backend, they are still managed in the default local storage. However, I am sure that the configuration file is loaded as I get an error when I mistype a class name or something. Does anyone have an example on how to configure this correctly?
2. I have no idea how to get the access token. I am somewhat familiar with OAuth but don’t know how to use it with Pimcore. Do I have to implement the OAuth process myself or does Pimcore (or another component that is easy to integrate) provide some support here?

**To give you a bit more context:**

- I intentionally only configured pimcore.asset.storage and no other flysystem interfaces like pimcore.thumbnail.storage etc. as I would like to handle cache, thumbnails etc. locally and only want to get the original files from OneDrive. Don’t know, if this is even possible.
- I am using the flysystem-msgrah implementation by shitware-ltd only because it seemed to be the most discussed and used implementation. However, if you can recommend any of the other flysystem adapters to connect to OneDrive Business, I am happy to switch.
- I intensively read the Pimcore documentation already. Specifically, https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Setup_and_Hosting/File_Storage_Setup
- I also read everything I could find regarding flysystem and msgraph. Specifically, https://packagist.org/packages/shitware-ltd/flysystem-msgraph and linked pages by Microsoft
- I found the following two posts. The first one helped me to piece together the config file:
https://github.com/orgs/pimcore/discussions/12879
https://github.com/orgs/pimcore/discussions/16576

Any help would be highly appreciated!
Thank you!

Best,
Fabian
