### DISCUSSION TITLE
How to configure (Tiny MCE) WYSIWYG in Data Objects?

### DISCUSSION THREAD

**Discussion by dariusmann** [pimcore/pimcore#16841] [Q&A / Support]
Where is the documentation for that?
So far I just found the documentation for editables: https://pimcore.com/docs/platform/Pimcore/Documents/Editables/WYSIWYG/

Anyone has a hint or code example?

**Comment by idna001** [comment]
Hey, 

Obviously, there is no Documentation especially for that, but I assume that it is not very different from the configuration for the editables. That's working. I found it in the demo of Pimcore.
Here is a deeplink example: https://demo.pimcore.fun/admin/login/deeplink?object_1121_object
<img width="1077" alt="grafik" src="https://github.com/pimcore/pimcore/assets/46223359/be6f2db3-9abc-4cdd-9796-706ef7e99f0f">

You can look up the class in use or even export it and add it in your project. 

If your Navbar don't show up, you may also have to install an editor. In the Skeleton TinyMCE is preinstalled, in the skeleton Version it's missing. 
If you installed it successfully, maybe you have to enable the TinyMCE in the `config/bundles.php`
This is in the [next Version](https://pimcore.com/docs/platform/next/Pimcore/Documents/Editables/WYSIWYG) of the Documentation: 
![grafik](https://github.com/pimcore/pimcore/assets/46223359/2601200f-ddb1-4d2d-a417-2448bce899e1)

I think, the config for the Navbar, will be the same as in the Link you shared for Data Objects in the File `config/packages/html_sanitizer.yaml`. But you have to try it.

Hope that helps
Andreas

**Comment by skoch98** [comment]
Hi,

Andreas has already said the most of it but as addendum take a look at the README of the TinyMCE Bundle: https://github.com/pimcore/pimcore/tree/11.x/bundles/TinymceBundle

You can simply change the TinyMCE config via json. Either globally, for editable or for each object field in the class definition.

Edit: To change it globally just put you config to `pimcore.object.tags.wysiwyg.defaultEditorConfig`, see: https://github.com/pimcore/pimcore/blob/11.x/bundles%2FTinymceBundle%2Fpublic%2Fjs%2Feditor.js#L83

^Sebastian

**Comment by betterapp** [comment]
@skoch98

I tried add in both places>

In config.yaml:
```
pimcore:
    object:
        tags:
            wysiwyg:
                defaultEditorConfig:
                    extended_valid_elements: "iframe[src|width|height|name|align],script[type|src],style[type]"
                    valid_elements: "*[*]" 
                    forced_root_block: "" 
                    valid_children: "+body[style],+div[iframe|script]"
```

but when I clear cache I got error

![image](https://github.com/user-attachments/assets/5cb9ca8f-3367-48d2-9b26-e58fdc7a86c3)

I tried add config to field:

```
{
    "extended_valid_elements": "iframe[src|width|height|name|align],script[type|src],style[type]",
    "valid_elements": "*[*]",
    "forced_root_block": "",
    "valid_children": "+body[style],+div[iframe|script]"
}
```
![image](https://github.com/user-attachments/assets/cc50a823-587b-4754-8686-088a7a878db7)
