### DISCUSSION TITLE
Faulty pimcoreadmin paths

### DISCUSSION THREAD

**Discussion by paulhaem** [pimcore/pimcore#16998] [Q&A / Support]
Inside of `public/bundles/pimcoreadmin/extjs/css/PimcoreApp-all_1.css` there is this and similar lines that reference a sprite with a wrong path. `img` should be used instead of `images` for the correct path. As this is part of the pimcoreadmin bundle where would I optimally report this to or add a PR for fixing the path?

```css
.x-tool-img {
    background-image: url(../images/tools/tool-sprites.png);
}
```
