### DISCUSSION TITLE
Switch dev to prod environment

### DISCUSSION THREAD

**Discussion by betterapp** [pimcore/pimcore#17034] [Q&A / Support]
Hi.

I have a Pimcore 11 project. This is my first Pim 11 (not 6.9) project,

I have switched .env file
from

`APP_ENV=dev`

to

`APP_ENV=prod`

And now I can not add/remove DataHub configuration and configure Image Thumbnails

![image](https://github.com/pimcore/pimcore/assets/7449124/f7884a5d-2d81-4a30-95dd-d3a3f5c0c571)

![image](https://github.com/pimcore/pimcore/assets/7449124/510e71c2-f5ab-429c-8a08-c94091458b3d)

I tried add (like in documentation https://pimcore.com/docs/platform/Pimcore/Deployment/Configuration_Environments/#page_Production-environment-with)

```
pimcore:
    config_location:
        predefined_properties:
            write_target:
                type: 'settings-store'
```
                
to /config/config.yaml file but it doesn not work still

tried add to .env

`PIMCORE_WRITE_TARGET_DATA_HUB=settings-store`

cleared the cache. does not work also.

can someone help me ?

**Comment by betterapp** [comment]
BTW.

I know that I can add to .env

`APP_DEBUG=true`

but I do not want to do this. I want to keep

`APP_DEBUG=false`

**Reply by blankse** [reply]
Did you install the dotenv package? Otherwise env vaeiable doesn't work
See https://github.com/pimcore/demo/blob/8bcf5b4906cfcf65c832462532cd10a1d7af2433/composer.json#L32

**Comment by blankse** [comment]
`predefined_properties` != `data_hub`

Try this config:
```
pimcore:
    config_location:
        data_hub:
            write_target:
                type: 'settings-store'
```

See: https://pimcore.com/docs/platform/Datahub/Deployment#example

See here for other configs:
https://github.com/pimcore/demo/blob/8bcf5b4906cfcf65c832462532cd10a1d7af2433/config/config.yaml#L28

**Comment by betterapp** [comment]
@blankse 

1. For image thumbnails I have added:
```
pimcore:
    config_location:
        image_thumbnails:
            write_target:
                type: 'settings-store'
```
cleared the cache, reload the admin panel
and still can not remove/add Thumbnail configurations

2. For data hub tried Your config but

DO NOT WORK:
```
pimcore:
    config_location:
        data_hub:
            write_target:
                type: 'settings-store'
```

THIS IS WORKING:

```
pimcore_data_hub:
    config_location:
        data_hub:
            write_target:
                type: 'settings-store'
```

**Reply by natted** [reply]
[updated] sorry false alarm - I re-saved my config and cleared cache and thumbnail config in pimcore admin is working as expected. @betterapp perhaps re-check in case you missed something?

**Reply by betterapp** [reply]
@natted 

Can You share what exactly and where (in which file) did you enter ?

**Comment by natted** [comment]
> Can You share what exactly and where (in which file) did you enter ?
@betterapp 

in config.yaml under pimcore section:

```
pimcore:
    config_location:
            image_thumbnails:
                write_target:
                    type: 'settings-store'
            video_thumbnails:
                write_target:
                    type: 'settings-store'
```

make sure you clear your cache after the change and reload the admin page in browser

**Comment by betterapp** [comment]
@natted 

Found what is going on with it.

I had: `APP_ENV=dev`
I saved image/video thumbnails and it used `symfony-config` (write_target) for it.

Then I changed APP_ENV to: 
`APP_ENV=prod`

and added
```
pimcore:
    config_location:
            image_thumbnails:
                write_target:
                    type: 'settings-store'
            video_thumbnails:
                write_target:
                    type: 'settings-store'
```

If You have some image/video thumbnails configuration saved already with different write_target
and You change write_target via pimcore config then it will not work.

I needed to remove all image/video thumbnails configurations first then change APP_ENV to prod
and add write_target configuration type 'settings-store'
And now it is working.
