### DISCUSSION TITLE
Issues with integrating Doctrine ORM to create tables in Pimcore

### DISCUSSION THREAD

**Discussion by AlephLau** [pimcore/pimcore#17043] [Q&A / Support]
Hello Pimcorenauts,

I'm experiencing some issues while trying to generate and apply migrations in my Pimcore project, and I was wondering if you could help me resolve them.

Currently, my Doctrine ORM and migrations configuration in my config.yml file looks like this:
```
doctrine:
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

doctrine_migrations:
    storage:
        table_storage:
            table_name: migration_versions
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
    em: default
    connection: ~
```

However, when I run the make:migration command, the migration is not generated in the specified folder in my configuration. Instead, migrations are only generated for the Pimcore bundles.

After doing some research, I found a suggestion in a forum to use the command bin/console doctrine:migrations:diff --em=default --namespace=App\\Migrations to generate migrations. This seems to work, but when I run the migrate command, I encounter a series of errors that I don't fully understand.

I was wondering if any of you have experienced similar issues when integrating Doctrine ORM into a Pimcore project. Could you guide me on what I might be doing wrong or if there are any additional steps I should follow to resolve this issue?

I would greatly appreciate any help or suggestions you can offer to help me solve these problems and make my migrations work correctly.

Thank you in advance for your time and assistance!
