### DISCUSSION TITLE
Pimcore Enterprise: Pimcore Copilot [Variant Generator]

### DISCUSSION THREAD

**Discussion by Chauhan-Mukesh** [pimcore/pimcore#17079] [General]
Hi everyone, I'm working on the Pimcore Copilot Variant Generator and running into an issue where the process doesn't complete when trying to create variants. Has anyone else experienced this or have any tips for troubleshooting the configuration? I've double-checked the settings, but no luck so far.

I have created a Car class with following attributes

**Class:** Car
**Fields:** name(input), color(multiselect) {opitons: red, green, blue}

Here are the copilot configuration:
```
pimcore_copilot:
    automation_actions:
        actions:
            car_variant_generator:
                name: car_variant_generator
                title: 'Car Variant Generator'
                description: ''
                triggers:
                    schedule:
                        cron: ''
                        subject_provider: ''
                        enabled: false
                        type: ''
                        object_class: ''
                        workspaces: {  }
                    manual:
                        context_limitations:
                            - object_car
                            - object_car_selection
                        search_terms: {  }
                        enabled: true
                environment_variables:
                    -
                        configuration:
                            required: false
                        name: Published
                        type: Pimcore\Bundle\CopilotBundle\AutomationAction\Configuration\Environment\Type\Checkbox
                    -
                        configuration:
                            required: false
                            columns:
                                -
                                    configuration:
                                        required: true
                                        values:
                                            -
                                                key: red
                                                value: red
                                            -
                                                key: green
                                                value: green
                                            -
                                                key: blue
                                                value: blue
                                    name: Color
                                    type: Pimcore\Bundle\CopilotBundle\AutomationAction\Configuration\Environment\Type\Select
                        name: Variants
                        type: Pimcore\Bundle\CopilotBundle\AutomationAction\Configuration\Environment\Type\Matrix
                steps:
                    -
                        name: 'Car Variant'
                        step_implementation: variant_generator
                        condition: ''
                        configuration:
                            class_name: Pimcore\Model\DataObject\Car
                            matrix_variable: Variants
                            field_mappings:
                                key: Color
                                color:
                                    matrixColumn: Color
                                    transformers:
                                        - asArray
                post_execution_interaction: !php/const Pimcore\Bundle\CopilotBundle\AutomationAction\Configuration\PostInteractionTypes::RELOAD_SUBJECT
                # icon: ''
                # is_expanded_on_show: false
                # action_permissions:
                #     users:
                #         admin:
                #             permissions:
                #                 - !php/const Pimcore\Bundle\CopilotBundle\ActionPermissions\ActionPermissionTypes::EXECUTE
                #     roles: {  }
```

I want a Configuration usnig I can generate a variant of Car using Copilot, I have only installed copilot and created above configuration if there is anything else I am missing please help. 

Any help would be greatly appreciated! Thanks!
