### DISCUSSION TITLE
What are the correct steps to integrate ORM in a Pimcore application?

### DISCUSSION THREAD

**Discussion by AlephLau** [pimcore/pimcore#17113] [Q&A / Support]
What are the specific steps to correctly integrate ORM within a Pimcore application? While the current documentation covers Symfony integration, it lacks detailed instructions for the Pimcore environment, which requires additional configurations.

It would be extremely helpful if the documentation could be expanded to include these specific steps. 

I have tried following the Symfony documentation, but encountered issues due to additional configurations required for Pimcore. Searching through forums and community discussions provided some insights, but a comprehensive guide in the official documentation would be ideal.

Providing a step-by-step guide with examples specific to Pimcore would not only help me but also many other developers facing similar challenges. Thank you for considering this request.

**Comment by alasdair-shields** [comment]
Pimcore already uses Doctrine ORM.  If you need to use a second database for non-Pimcore data you can set up multiple connections and entity managers as described here: https://symfony.com/doc/current/doctrine/multiple_entity_managers.html

An example config for a second entity manager maight be something like:

```
doctrine
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        proxy_namespace: P10Proxies
        default_entity_manager: default
        entity_managers:
            default: # For Pimcore - Pimcore doesn't set this explicitly as it expects only one connection
                connection: default
            data:
                connection: data_conection
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppData:
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity"
                        prefix: App\Entity
```

**Reply by jdreesen** [reply]
Where does Pimcore use Doctrine ORM? As far as I know, it only uses DBAL.

**Reply by alasdair-shields** [reply]
Sorry, you're right.  It's possible to use a second database connection and set the default entity manager to use that:
```

doctrine
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        proxy_namespace: P10Proxies
        default_entity_manager: default
        entity_managers:
            default: 
                connection: data_connection
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppData:
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity"
                        prefix: App\Entity
```

**Reply by dpfaffenbauer** [reply]
you can also use the same connection (same database) with ORM.

**Reply by AlephLau** [reply]
When running a doctrine command php app/console doctrine:migrations:diff, my tables were being deleted. It was necessary to define a different connection with a schema filter like this: 

```
doctrine:
    dbal:
        connections:
            default: &default
                host: db-host
                port: '3306'
                user: "%env(MYSQL_USER)%"
                password: "%env(MYSQL_PASSWORD)%"
                dbname: "%env(MYSQL_DATABASE)%"
                mapping_types: { enum: string, bit: boolean}
                server_version: '10.11.2-MariaDB-1:10.11.2+maria~ubu2204'
            app:
                <<: *default
                schema_filter: ~(^app_|migration_versions)~
```

In addition to this configuration, I had to add my repositories as services, and then I did something like this in the controller and it worked!

```
# Definition of the repository as a service
App\Repository\TestProRepository:
    arguments: ['@doctrine']
    tags:
        - { name: 'doctrine.repository_service' }

```
```

public function __construct(ManagerRegistry $doctrine)
{
    $this->entityManager = $doctrine->getManager('app');
}

/**
 * @Route("/test")
 */
public function test()
{
    $testPro = new TestPro();

    $testPro->setName('new name');
    $testPro->setLastname('new lastname');
    $this->entityManager->persist($testPro);
    $this->entityManager->flush();
    return new Response('New entity created with ID ' . $testPro->getId());
}

```
