### DISCUSSION TITLE
There are no registered paths for namespace "PimcoreAssetsBundle".

### DISCUSSION THREAD

**Discussion by aguerer-remind** [pimcore/pimcore#17655] [Q&A / Support]
Hi I have created an bundle for creating an API key in the backend for my project, I have created the following:

src/Controller/Admin/ApiKeyController
```
<?php

namespace Remind\PimcoreAssetsBundle\Controller\Admin;

use Pimcore\Bundle\AdminBundle\Controller\AdminAbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ApiKeyController extends AdminAbstractController
{
    /**
     * @Route("/admin/apikey/list", name="app_pimcoredriver_admin_apikey_list")
     */
    public function listAction(Request $request): Response
    {
        return $this->render('@PimcoreAssetsBundle/admin/apikey/list.html.twig');
    }
}
```

config/pimcore/routing.yaml
```
app_pimcoredriver_admin_apikey_list:
    path: /admin/apikey/list
    defaults: { _controller: Remind\PimcoreAssetsBundle\Controller\Admin\ApiKeyController::listAction }
    options:
        expose: true
```

under resources/views/admin/apikey/ is my template list.html.twig

but i get this error if i try to go to the route:
There are no registered paths for namespace "PimcoreAssetsBundle".

My Log says
`[2024-09-25T08:21:58.398287+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "There are no registered paths for namespace "PimcoreAssetsBundle"." at FilesystemLoader.php line 204 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): There are no registered paths for namespace \"PimcoreAssetsBundle\". at /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php:204)"} []
`

on blundles.php i registered my bundle like this:
`Remind\PimcoreAssetsBundle\PimcoreAssetsBundle::class => ['all' => true]`

Whats the problem here?
