### DISCUSSION TITLE
PIMCORE : Increase server memory

### DISCUSSION THREAD

**Discussion by JeremyDP-2606** [pimcore/pimcore#17688] [Q&A / Support]
Hi, 

I am trying to launch Pimcore but it is really slow locally. 
I can see on docker that only 600m are used, is it possible to increase this limit on a docker file or php.ini?

Thanks in advance.

**Comment by jjsararas** [comment]
Same, painfully slow in a Docker container. I've been messing with Redis cache and increasing maxmemory in the docker-compose.yaml but to no avail. 

```
redis:
  image: redis:alpine
  command: [ redis-server, --maxmemory, 1024mb, --maxmemory-policy, volatile-lru, --save, '""' ]
  volumes:
    - pimcore-demo-redis-data:/data
```


I also tried adding a .wslconfig in home directory and specifying:

```
[wsl2]
memory=4GB  
processors=2
swap=2GB 
```

I'm going to put it on a VPS but I'd love to hear if you get it going locally.
