### DISCUSSION TITLE
Default Currency in eCommerce

### DISCUSSION THREAD

**Discussion by esisl** [pimcore/pimcore#17818] [Q&A / Support]
I'm full of regrets.
But I don't understand at all how to set up the default currency in the configuration.
Configured by overriding the configure Options method for Environment
But I think it's a crutch!

**Comment by esisl** [comment]
https://pimcore.com/docs/platform/Ecommerce_Framework/Configuration/PimcoreEcommerceFrameworkBundle_Configuration_Reference/

I don't see this option in the directory :(

**Reply by GNi33** [reply]
Indeed, that value is not included in the reference values anymore.
You're able to set the `defaultCurrency` using the environment.options parameter in the configuration.

I didn't test it specifically right now, but it at least used to be set like this:

```
pimcore_ecommerce_framework:
    environment:
        options: 
            defaultCurrency: CHF
```
