### DISCUSSION TITLE
pimcore cluster setup with ci/cd

### DISCUSSION THREAD

**Discussion by talsan74** [pimcore/pimcore#17948] [General]
We are using Pimcore 11.x, which has been deployed on Kubernetes. Our setup includes persistent volume paths mounted as an NFS file system, which are as follows:

```
1. var/classes  
2. var/config/<bundle>  
3. public/var  
4. var/tmp  
5. config/  
```
Additionally, we use S3 Flysystem paths for the following:

```
1. pimcore.asset.storage  
2. pimcore.asset_cache.storage  
3. pimcore.thumbnail.storage  
4. pimcore.version.storage  
5. pimcore.recycle_bin.storage  
6. pimcore.admin.storage  
```
We have a Docker CI/CD setup. During initial deployment, running **/vendor/bin/pimcore-install** with the skeleton doesn't cause issues while Dockerizing the application. However, upgrading Pimcore is challenging. For example:

Installing a new bundle and Dockerizing it for deployment to Kubernetes.
Mounting S3 Flysystem paths during the Docker build process is feasible, but mounting the NFS file system during the same process is not.

**Question:**
What steps should we follow to upgrade Pimcore while using mounted S3 Flysystem paths during the Docker build process, particularly for:

- Installing new bundles.

A detailed explanation of the steps would be highly helpful to upgrade without data loss.

**Comment by dpfaffenbauer** [comment]
why do you need to mount anything during docker build?

**Reply by talsan74** [reply]
I don't need to mount the NFS file system during the Docker build process, as the S3 mount works fine.

However, the issue arises when I run a Docker build to add a new module. The build process executes the following steps:

1. Install composer dependencies for the bundle.
2. vendor/bin/pimcore-install <envs>
3. Add the bundle to config/bundles.php.
4. Run bin/console pimcore:bundle:install <bundle_name>.

**Questions:**
Do I need to run `vendor/bin/pimcore-install <envs>` again, as I did during the initial Pimcore deployment?
If so, should I pass any specific arguments to it for a subsequent deployment?

**Reply by dpfaffenbauer** [reply]
why you need to mount s3 for docker build? I wanna get to the bottom of it before providing you answers ;)

PS: We also run on Kubernetes and don't mount anything on docker build and have no issues with new modules. we don't even have NFS, we only use GCS or S3.

**Reply by talsan74** [reply]
S3 Flysystem configurations are not required during the Docker build process as they are already included in our source code within the `flysystem.yaml` file under the config/ folder.

```
# flysystem.yaml
services:
   assets_s3:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: 'https://s3.ap-south-1.amazonaws.com'
               region: 'ap-south-1'
               version: 'latest'
               credentials:
                   key: '<key>'
                   secret: '<secret>'
flysystem:
   storages:
       pimcore.asset.storage:
           # Storage for asset source files, directory structure is equal to the asset tree structure
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'pimcore-bucket'
               prefix: assets
       pimcore.asset_cache.storage:
           # Storage for cached asset files, e.g. PDF and image files generated out of Office files or videos
           # which are then used by the thumbnail engine as source files
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'pimcore-bucket'
               prefix: cache
       pimcore.thumbnail.storage:
           # Storage for image and video thumbnails, directory structure is equal to the source asset tree
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'pimcore-bucket'
               prefix: thumbnail
       pimcore.version.storage:
           # Storage for serialized versioning data of documents/asset/data objects
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'pimcore-bucket'
               prefix: version
       pimcore.recycle_bin.storage:
           # Storage for serialized recycle bin data of documents/asset/data objects
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'pimcore-bucket'
               prefix: recycle_bin
       pimcore.admin.storage:
           # Storage for shared admin resources, such as the user avatar, custom logos, ...
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'pimcore-bucket'
               prefix: admin
```
NFS paths, such as `var/classes`, `var/tmp/datahub` (to prevent DataHub schedule import errors from Kubernetes CronJobs), and` var/config/datahub`, are primarily used for storing files generated during the creation of classes or DataHub configurations. If these paths are not shared across pods, the files will not be accessible in the admin UI.

The current setup is working fine, but if I need to add a new bundle using the Docker build process, for example:

```
vendor/bin/pimcore-install --install-bundles PimcoreApplicationLoggerBundle,PimcoreCustomReportsBundle,PimcoreGlossaryBundle,PimcoreSeoBundle,PimcoreSimpleBackendSearchBundle,PimcoreStaticRoutesBundle,PimcoreTinymceBundle,PimcoreUuidBundle,PimcoreWordExportBundle,PimcoreXliffBundle --no-interaction
bin/console pimcore:bundle:install PimcoreDataHubBundle
bin/console pimcore:bundle:install PimcoreDataImporterBundle
# Adding a new bundle
bin/console pimcore:bundle:install PimcorePerspectiveEditorBundle
```
If I add the new bundle in the Dockerfile, the updated Docker image deployment will not display DataObjects and classes in the admin UI, even though the files are mounted in Kubernetes. This is the issue.

**Reply by talsan74** [reply]
i have added additionally in
```
#flysystem.yaml
       pimcore.temp.storage:
           # Storage for temporary files that work under a batch process, such as export csv
           # must not be `local` for stateless environment
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'pimcore-bucket'
               prefix: temp
```
It seems this isn't working properly. The `var/tmp` files are not being updated to S3. If we have an option to add custom folders, it would be helpful to include `var/config/datahub` and `var/classes`, which should fix the problem.

**Reply by dpfaffenbauer** [reply]
Ok, this is how we do it, we also have this configuration for flysystem for GCS in our case. For CI/CD, we never touch those actually, the Symfony Container gets build and that is it. We don't have any NFS either. 

For installing Bundles, we create custom Migrations that run the installer like:

```
<?php

declare(strict_types=1);

namespace App\Migrations;

use CoreShop\Bundle\DocumentRouteBundle\Installer;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;

/**
 * @psalm-suppress DeprecatedTrait
 */
final class Version20241204131038 extends AbstractMigration implements ContainerAwareInterface
{
    use ContainerAwareTrait;

    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $installer = $this->container->get(Installer::class);

        if ($installer && $installer->canBeInstalled()) {
            $installer->install();
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
    }
}

```

**Reply by talsan74** [reply]
is there any possible way to include` var/config/datahub` and` var/classes` in the flysystem config to mount s3?

**Reply by dpfaffenbauer** [reply]
you can move datahub to the setting store (database) with this config:

```yaml
pimcore_data_hub:
    config_location:
        data_hub:
            write_target:
                type: 'settings-store'

```

re class definition: I am afraid not...

**Reply by talsan74** [reply]
What approach would you follow to save the classes?
The `pimcore.temp.storage` Flysystem configuration is not mounting the `var/tmp` written files to S3. What could be the reason?

**Reply by talsan74** [reply]
> Ok, this is how we do it, we also have this configuration for flysystem for GCS in our case. For CI/CD, we never touch those actually, the Symfony Container gets build and that is it. We don't have any NFS either.
> 
> For installing Bundles, we create custom Migrations that run the installer like:
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\Migrations;
> 
> use CoreShop\Bundle\DocumentRouteBundle\Installer;
> use Doctrine\DBAL\Schema\Schema;
> use Doctrine\Migrations\AbstractMigration;
> use Symfony\Component\DependencyInjection\ContainerAwareInterface;
> use Symfony\Component\DependencyInjection\ContainerAwareTrait;
> 
> /**
>  * @psalm-suppress DeprecatedTrait
>  */
> final class Version20241204131038 extends AbstractMigration implements ContainerAwareInterface
> {
>     use ContainerAwareTrait;
> 
>     public function getDescription(): string
>     {
>         return '';
>     }
> 
>     public function up(Schema $schema): void
>     {
>         $installer = $this->container->get(Installer::class);
> 
>         if ($installer && $installer->canBeInstalled()) {
>             $installer->install();
>         }
>     }
> 
>     public function down(Schema $schema): void
>     {
>         // this down() migration is auto-generated, please modify it to your needs
>     }
> }
> ```

I am a newbie to coding. new bundle has to be installed from docker build. Can you guide me how and where to use it with steps?

**Reply by dpfaffenbauer** [reply]
new bundle can't be installed from build cause it might needs a database, same with class definitions

**Reply by talsan74** [reply]
We are running `vendor/bin/pimcore-install` inside the Dockerfile for every Docker build, so we can access the database from it.

**Reply by dpfaffenbauer** [reply]
which isn't a good idea tbh. how do you handle different envs? what if something breaks during docker build? then you have a broken db as well and your prod isn't in the right state

**Reply by talsan74** [reply]
Correct, which is why finding a solution for that. The approach would be to have the Docker build only copy the code of skeleton and  bundles, and then, inside the Kubernetes pod, execute `vendor/bin/pimcore-install` and enable the installed bundle. Right?"

**Reply by dpfaffenbauer** [reply]
Yes

**Reply by talsan74** [reply]
I copied the skeleton and downloaded the required packages during the Docker build process. Inside Kubernetes, I mounted the `var/classes` directory as an EFS volume. Then, I executed the `vendor/bin/pimcore-install` command within the pod.

When installing a new bundle, the Docker build retrieves the required dependencies. The latest Docker image is then deployed, and Kubernetes executes the install:bundle command. This workflow seems to be working well for me.

Below is myconfiguration:
```
##config.yaml

#save datahub config to database
pimcore_data_hub:
    config_location:
        data_hub:
            write_target:
                type: 'settings-store'
```
```
##flysystem.yaml

services:
   assets_s3:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: 'https://s3.ap-south-1.amazonaws.com'
               region: 'ap-south-1'
               version: 'latest'
               credentials:
                   key: '%env(AWS_ACCESS_KEY_ID)%'
                   secret: '%env(AWS_SECRET_ACCESS_KEY)%'
flysystem:
   storages:
       pimcore.document_static.storage:
           adapter: 'aws'
           visibility: public
           options:
#               directory: /var/www/html/public/var/tmp/pages
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: documents
       pimcore.asset.storage:
           # Storage for asset source files, directory structure is equal to the asset tree structure
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: assets
       pimcore.asset_cache.storage:
           # Storage for cached asset files, e.g. PDF and image files generated out of Office files or videos
           # which are then used by the thumbnail engine as source files
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: cache
       pimcore.thumbnail.storage:
           # Storage for image and video thumbnails, directory structure is equal to the source asset tree
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: thumbnail
       pimcore.version.storage:
           # Storage for serialized versioning data of documents/asset/data objects
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: version
       pimcore.recycle_bin.storage:
           # Storage for serialized recycle bin data of documents/asset/data objects
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: recycle_bin
       pimcore.admin.storage:
           # Storage for shared admin resources, such as the user avatar, custom logos, ...
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: admin
       pimcore.temp.storage:
           # Storage for temporary files that work under a batch process, such as export csv
           # must not be `local` for stateless environment
           adapter: 'aws'
           visibility: private
           options:
#               directory: '%kernel.project_dir%/var/tmp'
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: temp-dir
       pimcore.application_log.storage:
           # Storage for application logs
           adapter: 'aws'
           visibility: private
           options:
               client: 'assets_s3'
               bucket: '%env(AWS_BUCKET)%'
               prefix: application-log
```

I believe the `var/classes` directory requires NFS mount to update or add classes through the UI. Is there an alternative solution to avoid using NFS for this while still allowing classes to be edited via the UI?
