### DISCUSSION TITLE
Add button disabled on prod env.

### DISCUSSION THREAD

**Discussion by betterapp** [pimcore/pimcore#17988] [Q&A / Support]
Hi.

I am logged with admin user and I see taht Add button is disabled.

![image](https://github.com/user-attachments/assets/bfa34d48-0ce4-49df-9458-e1bffc47ccbc)

**Comment by betterapp** [comment]
```
/config/config.yaml

pimcore_custom_reports:
    config_location:
        custom_reports:
            write_target:
                type: 'settings-store'
```
