### DISCUSSION TITLE
Custom layout for variant

### DISCUSSION THREAD

**Discussion by edersign** [pimcore/pimcore#18201] [Q&A / Support] [answered]
Hello,
I have a custom layout for variant, but it doesn't work, when I open it, it opens the default layout.
Can anyone help me!
```
class BikeCustomLayoutListener
{
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    public function selectCustomLayout(GenericEvent $event): void
    {
        $object = $event->getArgument('object');
        if ($object instanceof Bike) {
            $data = $event->getArgument('data');

            // Check if object is a variant
            if ($object->getType() === DataObject\AbstractObject::OBJECT_TYPE_VARIANT) {
                $this->logger->error('Object is a variant, applying variant layout');
                $data = $this->doModifyCustomLayouts($data, $object, 'b110aa17-dbf1-4816-82ef-c6bf0e7a03a7', [0, 1]);
            } else {
                // Check if object has variants
                $variants = $object->getChildren([DataObject\AbstractObject::OBJECT_TYPE_VARIANT]);
                $hasVariants = !empty($variants);

                $this->logger->error('Object is not a variant', [
                    'has_variants' => $hasVariants,
                    'object_id' => $object->getId()
                ]);

                if ($hasVariants) {
                    $data = $this->doModifyCustomLayouts($data, $object, 0, ['b110aa17-dbf1-4816-82ef-c6bf0e7a03a7']);
                }
            }

            $event->setArgument('data', $data);
        }
    }

    private function doModifyCustomLayouts(array $data, Bike $object, $customLayoutToSelect, array $layoutsToRemove): array
    {
        //set current layout to subcategory layout
        $data['currentLayoutId'] = $customLayoutToSelect;
        $customLayout = CustomLayout::getById($customLayoutToSelect);

        if ($customLayout) {
            $data['layout'] = $customLayout->getLayoutDefinitions();
            Service::enrichLayoutDefinition($data['layout'], $object);

            $this->logger->debug('Custom layout applied', [
                'layout_id' => $customLayoutToSelect
            ]);

            if (!empty($layoutsToRemove)) {
                //remove main layout from valid layouts
                $validLayouts = $data['validLayouts'];
                foreach($validLayouts as $key => $validLayout) {
                    if(in_array($validLayout['id'], $layoutsToRemove)) {
                        unset($validLayouts[$key]);
                    }
                }
                $data['validLayouts'] = array_values($validLayouts);
            }
        } else {
            $this->logger->error('Custom layout not found', [
                'layout_id' => $customLayoutToSelect
            ]);
        }

        return $data;
    }
}

```

**Comment by edersign** [comment, marked as answer]
by chance, I managed to solve it, probably because I'm a beginner, I realized that calling without `services.yaml` is different from other Events, 

``` 
App\EventListener\BikeCustomLayoutListener:
       arguments:
             $logger: '@logger'
         tags:
             - { name: kernel.event_listener, event: pimcore.admin.object.get.preSendData, method: selectCustomLayout }
```
so, it worked fine!!
```
    app.event_listener.BikeCustomLayoutListener:
        class: App\EventListener\BikeCustomLayoutListener
        arguments:
             $logger: '@logger'
        tags:
            - { name: kernel.event_listener, event: pimcore.admin.dataobject.get.preSendData, method: selectCustomLayout }

```
