### DISCUSSION TITLE
Product Registration Improvements for Test Environments

### DISCUSSION THREAD

**Discussion by dpfaffenbauer** [pimcore/pimcore#18419] [General]
Hey,

the Product Registration needs some improvements. It took us several times to get it up and running and several more times to get it up and running for our test suites.

Problem is: Pimcore does to much own its own. If you register, and use the config values like this:

```
pimcore:
    encryption:
        secret: "%env(PIMCORE_SECRET)%"
    product_registration:
        instance_identifier: "%env(PIMCORE_INSTANCE_IDENTIFIER)%"
        product_key: "%env(PIMCORE_PRODUCT_KEY)%"
```

Pimcore should not try to create a new yaml config file on installation

For automatic system like in test envs, you need the following env vars to get it working:

```
export PIMCORE_INSTALL_ENCRYPTION_SECRET=
export PIMCORE_SECRET=
export PIMCORE_INSTALL_INSTANCE_IDENTIFIER=
export PIMCORE_INSTANCE_IDENTIFIER=
export PIMCORE_PRODUCT_KEY=
```

where PIMCORE_INSTALL_ENCRYPTION_SECRET and PIMCORE_SECRET are the same and PIMCORE_INSTALL_INSTANCE_IDENTIFIER and PIMCORE_INSTANCE_IDENTIFIER are the same.

Also, can we `leak` our private keys for the CoreShop demo/dev setup for easy setup? Something like special keys for us?
