### DISCUSSION TITLE
Facing issues with workflow in latest pimcore versions

### DISCUSSION THREAD

**Discussion by neha04** [pimcore/pimcore#7763] [General]
Hi All,

I am facing issues in all the Dataobjects or assets on which I have applied workflow. If i use guard in workflow transitions , my the request to get objects fails after sometime. This is happening in latest pimcore version and in all the pimcore instances with symfony 4.There was no issue with pimcore versions that supports symfony 3.
Have anybody faced similar kind of issue?
Here is my workflow configuration.
```
pimcore:
    workflows:
        product_workflow:
            enabled: true
            priority: 1
            label: product_workflow
            type: state_machine
            initial_markings: [new]
            audit_trail:
                enabled: false
            marking_store:
                type: single_state
                arguments:
                    - workflowState
            supports:
                - Pimcore\Model\DataObject\Product
                - Pimcore\Model\DataObject\Products
            places:
                new:
                    label: 'New Product'
                    color: '#377ea9'
                    visibleInHeader: true
                rejected:
                    label: 'Rejected Product'
                    color: '#ff0000'
                    visibleInHeader: true
                review_content:
                    label: 'In Review'
                    title: 'Content review step'
                    color: '#d4750a'
                    visibleInHeader: true
                publish_content:
                    label: 'In Publish'
                    title: 'Content publish step'
                    color: '#d9ef36'
                    visibleInHeader: true
                accepted:
                    label: Published
                    color: '#28a013'
                    visibleInHeader: true
            transitions:
                reject_product_review:
                    from:
                        - review_content
                        - publish_content
                    to:
                        - rejected
                    guard: 'is_fully_authenticated() and has_role(''ROLE_REVIEWER'') or has_role(''ROLE_PUBLISHER'') or has_role(''ROLE_PIMCORE_ADMIN'')'
                    options:
                        label: 'Reject Changes'
                        iconClass: 'pimcore_icon_workflow_action'
                        notes:
                            commentEnabled: true
                            commentRequired: true
                            type: 'Status update'
                            additionalFields: {  }
                            title: 'Reject Changes'
                        changePublishedState: save_version
                        notificationSettings:
                            -
                                condition: ''
                                notifyUsers:
                                    - 'admin'
                                notifyRoles:
                                    - 'Creator'
                                mailType: template
                                mailPath: '@PimcoreCore/Workflow/NotificationEmail/notificationEmail.html.twig'
                    name: reject_product_review              
                after_reject:
                    from:
                        - rejected
                    to:
                        - new
                    guard: 'is_fully_authenticated() and has_role(''ROLE_REVIEWER'') or has_role(''ROLE_PUBLISHER'') or has_role(''ROLE_PIMCORE_ADMIN'')'
                    options:
                        label: 'Send for Edit'
                        iconClass: 'pimcore_icon_workflow_action'
                        notes:
                            commentEnabled: true
                            commentRequired: true
                            type: 'Status update'
                            additionalFields: {  }
                            title: 'Send for Edit'
                        changePublishedState: save_version
                        notificationSettings:
                            -
                                condition: ''
                                notifyUsers:
                                    - 'admin'
                                notifyRoles:
                                    - 'Creator'
                                mailType: template
                                mailPath: '@PimcoreCore/Workflow/NotificationEmail/notificationEmail.html.twig'
                    name: after_reject
                content_review:
                    guard: 'is_fully_authenticated() and has_role(''ROLE_CREATOR'') or has_role(''ROLE_PIMCORE_ADMIN'')'
                    from:
                        - new
                    to:
                        - review_content
                    options:
                        label: 'Send for Review'
                        iconClass: 'pimcore_icon_workflow_action'
                        changePublishedState: save_version
                        notes:
                            commentEnabled: true
                            commentRequired: true
                            commentSetterFn: ''
                            commentGetterFn: ''
                            type: 'Status update'
                            title: 'Send for Review'
                            additionalFields: {  }
                        notificationSettings:
                            -
                                condition: ''
                                notifyUsers:
                                    - 'admin'
                                notifyRoles:
                                    - 'Reviewer'
                                mailType: template
                                mailPath: '@PimcoreCore/Workflow/NotificationEmail/notificationEmail.html.twig'
                    name: content_review
                publish:
                    guard: 'is_fully_authenticated() and has_role(''ROLE_PUBLISHER'') or has_role(''ROLE_PIMCORE_ADMIN'')'
                    from:
                        - publish_content
                    to:
                        - accepted
                    options:
                        label: 'Publish the Product'
                        iconClass: 'pimcore_icon_workflow_action'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: true
                            commentRequired: true
                            commentSetterFn: ''
                            commentGetterFn: ''
                            type: 'Status update'
                            title: 'Publish the Product'
                            additionalFields: {  }
                        notificationSettings:
                            -
                                condition: ''
                                notifyUsers:
                                    - 'admin'
                                notifyRoles:
                                    - 'Publisher'
                                mailType: template
                                mailPath: '@PimcoreCore/Workflow/NotificationEmail/notificationEmail.html.twig'
                    name: publish
                further_modifications:
                    guard: 'is_fully_authenticated() and has_role(''ROLE_PUBLISHER'') or has_role(''ROLE_PIMCORE_ADMIN'')'
                    from:
                        - accepted
                    to:
                        - new
                    options:
                        label: 'Send for Edit'
                        iconClass: 'pimcore_icon_workflow_action'
                        changePublishedState: force_unpublished
                        notes:
                            commentEnabled: true
                            commentRequired: true
                            commentSetterFn: ''
                            commentGetterFn: ''
                            type: 'Status update'
                            title: 'Send for Edit'
                            additionalFields: {  }
                        notificationSettings:
                            -
                                condition: ''
                                notifyUsers:
                                    - 'admin'
                                notifyRoles:
                                    - 'Creator'
                                mailType: template
                                mailPath: '@PimcoreCore/Workflow/NotificationEmail/notificationEmail.html.twig'
                    name: further_modifications
                content_pulish:
                    guard: 'is_fully_authenticated() and has_role(''ROLE_REVIEWER'') or has_role(''ROLE_PIMCORE_ADMIN'')'
                    from:
                        - review_content
                    to:
                        - publish_content
                    options:
                        label: 'Send for Publish'
                        iconClass: 'pimcore_icon_workflow_action'
                        changePublishedState: save_version
                        notes:
                            commentEnabled: true
                            commentRequired: false
                            commentSetterFn: ''
                            commentGetterFn: ''
                            type: 'Status update'
                            title: 'Send for Publish'
                            additionalFields: {  }
                        notificationSettings:
                            -
                                condition: ''
                                notifyUsers:
                                    - 'admin'
                                notifyRoles:
                                    - 'Publisher'
                                mailType: template
                                mailPath: '@PimcoreCore/Workflow/NotificationEmail/notificationEmail.html.twig'
```
Is there any issue with this configuration ?
It seems it is related to cache as the issue is resolved on clearing the cache but comes back after a few new sessions.
