### DISCUSSION TITLE
Multi theme/template for Frontend

### DISCUSSION THREAD

**Discussion by vinitchopra12** [pimcore/pimcore#7887] [Q&A / Support]
Hi there,

I have multiple website in Pimcore v 6.7. I want to apply different theme for each website.
Basically, I have created separate theme folders under `/app/Resources/views`. Now I want to apply the frontend theme based on the website configuration (document Property).

Please advise me here to achieve this.

**Comment by dpfaffenbauer** [comment]
these solves your issue https://github.com/coreshop/ThemeBundle

**Reply by vinitchopra12** [reply]
I have checked with this Bundle, but it require CoreShop. I don't have CoreShop installed.

**Reply by dpfaffenbauer** [reply]
it does not require coreshop, you can install it standalone

**Reply by vinitchopra12** [reply]
Is there any documentation is available. The mentioned doc. link is not working.
https://docs.coreshop.org/2.1.0/Bundles/Theme_Bundle.html

**Reply by vinitchopra12** [reply]
Also, once I installed this bundle and then If I goes to Bundle page in Pimcore it gives an error. 

![image](https://user-images.githubusercontent.com/14720025/104219776-9187f000-5464-11eb-9a85-422147f347ee.png)

**Reply by dpfaffenbauer** [reply]
that is a bug that is gonna be fixed soon. it does not actually need the full installation.  

Docu is not really existing... But what you need todo is:

activate the default resolver you want:

```
core_shop_theme:
    default_resolvers:
        pimcore_site: true
        pimcore_document_property: true
```

Where 
 - pimcore_site is based on the Pimcore Site name (key of the site document)
 - pimcore_document_property checks for a "theme" property and assigns that as theme

Create folders:

`app/Resources/themes/[THEME_NAME]/layout.html.twig`

to overwrite the layout.html.twig file.

**Reply by vinitchopra12** [reply]
Can you please help me exactly where I need to place the below code (file).

```
core_shop_theme:
    default_resolvers:
        pimcore_site: true
        pimcore_document_property: true
```

Also, does it support the HTML PHP template?
