### DISCUSSION TITLE
Custom FilterType... Help?

### DISCUSSION THREAD

**Discussion by justbane** [pimcore/pimcore#8010] [Q&A / Support] [answered]
So I have tried doing what is listed here in the documentation: [https://pimcore.com/docs/pimcore/current/Development_Documentation/E-Commerce_Framework/Filter_Service/index.html](https://pimcore.com/docs/pimcore/current/Development_Documentation/E-Commerce_Framework/Filter_Service/index.html)

I have this in my **base-ecommerce.yml** file: 
```
FilterGenesMultiRelation:
    filter_type_id: AppBundle\Ecommerce\FilterService\FilterType\GenesMultiSelectRelation
    template: 'tests/filters/multi_relation.html.twig'
```

I created the file listed in the filter_type_id in the location shown.

Adding this and creating the FilterType Collection do nothing. The filter shows in the list of filters on my filter definition but it doesn't fire my custom filter code at all.

Also there is a reference to a **filter_service_filter_types.yml** file in the documentation but it doesnt seem to have anything but a reference to the parent abstract.

SOO CONFUSING!  any help or general direction would be appreciated.

**Comment by fashxp** [comment, marked as answer]
Hi,
does your field collection type have the name `FilterGenesMultiRelation`

BR
Christian

**Reply by justbane** [reply]
Hi Christian, yes it does.

**Reply by justbane** [reply]
OK, it seems that I am able to dump on the frontend and it works. I am seeing the dump from my filter file... so SOMETHING is working :)

Quick clarification: I noticed in the docs mention of **filter_service_filter_types.yml** - I created this file and included it in my commerce config.

The only thing I added to it was the location of the folder that my FilterTypes will reside... is this the correct use of this file?

Here are the contents of my file

```
services:

    AppBundle\Ecommerce\FilterService\FilterType\:
        resource: '../../Ecommerce/FilterService/FilterType/'
        parent: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\AbstractFilterType
```
