### DISCUSSION TITLE
how to create a pimcore ldap data mapper

### DISCUSSION THREAD

**Discussion by rhufsky** [pimcore/pimcore#8373] [Q&A / Support] [answered]
I am quite new to Pimcore, I have a basic installation of version 6.8 on ubuntu 20.
I installed `blackbit_digital_commerce/pimcore-ldap` and configured it so I can log in via an Active Directory server.

Now I want to customize the DataMapper to be able to assign users to certain roles based on data from AD.

To start I created a custom Datamapper class `MyLdapUserMapper` in `src/MyDam/MyLdapUserMapper.php` which is a copy of `DefaultLdapUserMapper`.

I just adapted the namespace and the class name:

```
namespace MyDam;
....
class MyLdapUserMapper implements LdapUserMapperInterface
{
```

In `app/config/config.yml` I added
```
alep_ldap:
    enabled: true
    base_dn: "DC=..."
    search_dn: "CN=..."
    search_password: "***"
    uid_key: "sAMAccountName"
    logger: "monolog.logger"
    #mapper: 'Alep\LdapBundle\DataMapper\DefaultLdapUserMapper'
    #mapper: 'Alep\LdapBundle\DataMapper\MyLdapUserMapper'
    mapper: 'MyDam\MyLdapUserMapper'

```
When I run `bin/console debug:config AlepLdapBundle` it tells me that it does not find the Mapper:

```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "Alep\LdapBundle\Service\Ldap" has a dependency on a non-existent service "MyDam\MyLdapUserMapper". in /var/www/html/dam/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
...
```

I tried various variants, even putting my new datamapper under `vendor/blackbit_digital_commerce/pimcore-ldap/...` .

After `composer dump-autoload` I even can find `MyLdapDataMapper` in the mappings.

What do I have to do to make `MyLdapDataMapper` available?

Thanks in advance
