### DISCUSSION TITLE
Custom Address Source Adapter not found

### DISCUSSION THREAD

**Discussion by dennisdittrich** [pimcore/pimcore#8642] [Q&A / Support] [answered]
Hello folks,

i want to create a CustomAddressSourceAdapter with the goal to send mails via mailchimp.

Docs Reference: https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Document_Types/Newsletter_Documents.html

The js file works quite well. the option in select appears.  But i have a problem with the php class.

Then i click the "send newsletter button" the backend throws a error:  "Cannot send newsletters because Address Source Adapter with identifier mailchimp could not be found"

The service.yml:

```
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
```

```
    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    #
    # COMMANDS
    #

    # auto-register all commands as services
    AppBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']

    # adds additional static files to admin backend
    AppBundle\EventListener\PimcoreAdminListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.js, method: addJSFiles }

    app.document.newsletter.factory.mailchimp:
        class: Pimcore\Document\Newsletter\DefaultAddressSourceAdapterFactory
        arguments:
            - 'AppBundle\Document\Newsletter\Mailchimp'

```

Class: (copy and renamed the csvList class for now)

```
<?php
/**
 * Pimcore
 *
 * This source file is available under two different licenses:
 * - GNU General Public License version 3 (GPLv3)
 * - Pimcore Enterprise License (PEL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 * @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
 * @license    http://www.pimcore.org/license     GPLv3 and PEL
 */

namespace AppBundle\Document\Newsletter\AddressSourceAdapter;


use Pimcore\Document\Newsletter\AddressSourceAdapterInterface;
use Pimcore\Document\Newsletter\SendingParamContainer;

class Mailchimp implements AddressSourceAdapterInterface
{
  [CONTENT REMOVED, COPY FROM CSVLIST.PHP]
}

```

Any ideas how register the class correctly? :)
