### DISCUSSION TITLE
Using Doctrine ORM with external Database Connection

### DISCUSSION THREAD

**Discussion by polymed** [pimcore/pimcore#8742] [Q&A / Support]
Hi guys, 

since I added a new database configuration, I get the following error. Does anyone have any ideas?

config.yml
```
doctrine:
  dbal:
    connections:
        ....my_external_config
```

```
bin/console pimcore:migrations:status

In PimcoreMigrationsConfiguration.php line 122: Return value of Pimcore\Migrations\Command\StatusCommand::getConnection() must implement interface Pimcore\Db\ConnectionInterface, instance of Doctrine\DBAL\Connection returned
```

Best regards
