### DISCUSSION TITLE
Pimcore Demo - Login - ERROR

### DISCUSSION THREAD

**Discussion by M-Ali-Aziz** [pimcore/pimcore#9372] [Q&A / Support] [answered]
Pimcore : v10.0.2
customer-data-framework : v3.1.0

Hi,

Login not working on https://demo.pimcore.com/en/account/login (Pimcore Demo) at the moment,
and I have the same problem on my dev.

`No password hasher has been configured for account "Pimcore\Model\DataObject\Customer".`

<img width="1082" alt="login-error-demo" src="https://user-images.githubusercontent.com/8568212/121191581-64e9d000-c86c-11eb-9857-ffb1273bfc33.png">

Any help please!

**Comment by M-Ali-Aziz** [comment]
I'm getting this error on Admin UI as well

```
An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS(?)'
with params [2]: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION
pimcore.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist

Server threw exception - could not perform action. Please reload the admin interface and try again.
```

<img width="714" alt="error2" src="https://user-images.githubusercontent.com/8568212/121343279-cc625700-c922-11eb-9451-a588b96a12cc.png">

**Reply by dvesh3** [reply]
@M-Ali-Aziz how to reproduce?

**Reply by M-Ali-Aziz** [reply]
Hi, Thank you for your reply.

this error appears directly when I login to Admin UI and open any page

**Reply by M-Ali-Aziz** [reply]
Pimcore : v10.0.3
customer-data-framework : v3.2.0

Updated Pimcore and customer-data-framework.
Uninstalled and then reinstalled customer-data-framework.

But still same problem/error :(

**Reply by fashxp** [reply]
can you verify that the stored functions [here](https://github.com/pimcore/customer-data-framework/tree/6c012bbbf1b30f578d33d5fc07d073276c4e5011/src/Resources/sql/segmentAssignment) are installed in your database properly?

**Reply by M-Ali-Aziz** [reply]
Yes 🎉 
After  running all queries [here](https://github.com/pimcore/customer-data-framework/tree/6c012bbbf1b30f578d33d5fc07d073276c4e5011/src/Resources/sql/segmentAssignment), I don't get any error and the problem is solved. 

Thanks alot 😃

**Reply by fashxp** [reply]
strange that it didn't run in the first place...

**Comment by dvesh3** [comment, marked as answer]
this should fix the login error on frontend https://github.com/pimcore/demo/pull/241

**Reply by M-Ali-Aziz** [reply]
Working perfect! Thank you :)

**Reply by dvesh3** [reply]
Update: proper fix here https://github.com/pimcore/pimcore/pull/9397

**Reply by M-Ali-Aziz** [reply]
First I wanted to confirm that the fix on Pimcore 10.0.4 is working fine 👍 🎉 
Thanks a lot 😃 

But now I get problem with the `default_target_path: 'account-index'` under `security.yaml`.

```
form_login:
     login_path: 'account-login'
     check_path: 'account-login'
     csrf_token_generator: security.csrf.token_manager
     default_target_path: 'account-index'
```

After login the user redirects to start page, but it should redirects to `account/index`  ❗❓❗ 

Dose this problem have with the last update to do (Pimcore 10.0.4) ?

**Reply by fashxp** [reply]
hmm, normally this should not be related. can you try to debug a bit and create an issue (or even better a PR 😉)

**Reply by M-Ali-Aziz** [reply]
Let me see if I can find something 👍

**Reply by M-Ali-Aziz** [reply]
It now works fine again after clearing the cache on Admin UI + the web browser and then restarting the page.
No worries, everything seems to work fine 👍 ✨

NOTE!
I  just wanted to mention that to add `always_use_default_target_path: true` to the `form_login:` config under `security.yaml` can also make sure that `default_target_path: 'account-index'` is always used:
```
form_login:
     login_path: 'account-login'
     check_path: 'account-login'
     csrf_token_generator: security.csrf.token_manager
     default_target_path: 'account-index'
     always_use_default_target_path: true
```
Anyway I'm not using this at the moment and login works fine without it.

Thank you very much!
