### DISCUSSION TITLE
How to enable only pimcore.* log

### DISCUSSION THREAD

**Discussion by Karthi96** [pimcore/pimcore#9507] [Q&A / Support] [answered]
Hi Team, 

Here is the monolog config on `config.yaml`
```
monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        console:
            type: console
            process_psr_3_messages: false
```

If enable this config in prod, the huge logs are coming php.INFO, pimcore.INFO, request.INFO. I want only pimcore.INFO logs, how can I do it ?

Thanks, 
Karthikeyan
