### DISCUSSION TITLE
Is it possible to list products based on a value from a brick of a related object?

### DISCUSSION THREAD

**Discussion by rsaunders2** [pimcore/pimcore#9647] [Q&A / Support] [answered]
I apologize in advance, as I'm not sure if I'm asking this question properly. For brevity, these are the names of the objects that will be mentioned: PRODUCT, PRODUCT_MAKER, PRODUCT_MAKER_BRICK.

I would like to search for my PRODUCTS and order them based on a value of my PRODUCT_MAKER_BRICK. 

My ecommerce config file looks something like this:
```
index_service:
        tenants:
            default:
                search_attributes:
                    - name
                attributes:
                    name:
                        fieldname: OSName
                        type: varchar(255)
                        filter_group: string
                    product_maker_createdat:
                        fieldname: 'product_maker'
                        type: datetime
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\ObjectValue
                        interpreter_options:
                            onlyValue: true
                        getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetter
                        getter_options:
                            brickfield: productMakerInfo
                            bricktype: ProductMakerInfo
                            fieldname: createdAt 
```

             
I then try to order it like this:
`$productListing->setOrderKey('product_maker_createdat', false);`
`$productListing->setOrder('DESC');`

Obviously this doesn't work, but am I even in the ballpark? I'm not sure what direction I should be heading in. 

Thank you.
