### DISCUSSION TITLE
Images cannot be uploaded when I use GCS

### DISCUSSION THREAD

**Discussion by ninanomenon** [pimcore/pimcore#9839] [Q&A / Support]
I am currently trying to include GCS as a storage backend with Pimcore 10 (v10.0.8). 

When I include GCS as storage via the flysystem abstaction, I get the following error message when uploading images:  

`Pimcore\Model\Asset\Image\Thumbnail::getLocalFileFromStream(): Return value must be of type string, null returned`
(i can also provide the whole stacktrace if needed)

I use the following config for this: 
```
flysystem:
    storages:
        pimcore.asset.storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_STORAGE_SOURCE_ASSET)%'
        pimcore.asset.storage.gcs:
            visibility: public
            adapter: gcloud
            options:
                client: gcs_client
                bucket: '%env(GCS_BUCKET)%'
                prefix: 'public/var/assets'
        pimcore.asset.storage.local:
            adapter: local
            visibility: public
            options:
                directory: '%kernel.project_dir%/public/var/assets'
                permissions:
                    file:
                        private: 420
                    dir:
                        private: 493
            case_sensitive: true
            disable_asserts: false
        pimcore.asset_cache.storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_STORAGE_SOURCE_ASSET_CACHE)%'
        pimcore.asset_cache.storage.gcs:
            visibility: private
            adapter: gcloud
            options:
                client: gcs_client
                bucket: '%env(GCS_BUCKET)%'
                prefix: 'public/var/tmp/asset-cache'
        pimcore.asset_cache.storage.local:
            adapter: local
            visibility: private
            options:
                directory: '%kernel.project_dir%/public/var/tmp/asset-cache'
            case_sensitive: true
            disable_asserts: false
        pimcore.thumbnail.storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_STORAGE_SOURCE_THUMBNAIL)%'
        pimcore.thumbnail.storage.gcs:
            visibility: public
            adapter: gcloud
            options:
                client: gcs_client
                bucket: '%env(GCS_BUCKET)%'
                prefix: 'public/var/tmp/thumbnails'
        pimcore.thumbnail.storage.local:
            adapter: local
            visibility: public
            options:
                directory: '%kernel.project_dir%/public/var/tmp/thumbnails'
                permissions:
                    file:
                        private: 420
                    dir:
                        private: 493
            case_sensitive: true
            disable_asserts: false
        pimcore.version.storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_STORAGE_SOURCE_VERSION)%'
        pimcore.version.storage.gcs:
            visibility: private
            adapter: gcloud
            options:
                client: gcs_client
                bucket: '%env(GCS_BUCKET)%'
                prefix: 'var/versions'
        pimcore.version.storage.local:
            adapter: local
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/versions'
            case_sensitive: true
            disable_asserts: false
        pimcore.recycle_bin.storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_STORAGE_SOURCE_RECYCLE_BIN)%'
        pimcore.recycle_bin.storage.gcs:
            visibility: private
            adapter: gcloud
            options:
                client: gcs_client
                bucket: '%env(GCS_BUCKET)%'
                prefix: 'var/recyclebin'
        pimcore.recycle_bin.storage.local:
            adapter: local
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/recyclebin'
            case_sensitive: true
            disable_asserts: false
        pimcore.admin.storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_STORAGE_SOURCE_ADMIN)%'
        pimcore.admin.storage.gcs:
            visibility: private
            adapter: gcloud
            options:
                client: gcs_client
                bucket: '%env(GCS_BUCKET)%'
                prefix: 'var/admin'
        pimcore.admin.storage.local:
            adapter: local
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/admin'
            case_sensitive: true
            disable_asserts: false
```

I have now spent several hours debugging and am currently stuck. I am grateful for every tip.
