### DISCUSSION TITLE
Error after updating to Pimcore 10.1: TranslationDebugListener::__construct(): Argument #1 ($translator) must be of type Pimcore\Translation\Translator, Symfony\Component\Translation\DataCollectorTranslator given

### DISCUSSION THREAD

**Discussion by shaselboeck** [pimcore/pimcore#9950] [Q&A / Support]
After updating a website to Pimcore 10.1 an error appears only in development mode. The error does not appear in productive mode.
![](https://drive.google.com/uc?export=view&id=1l6iDhLOEO4HNQT3UZFKrTTtbIYhL9IVo)

App_KernelDevDebugContainer.php - line 3149:
`return $this->privates['Pimcore\\Bundle\\CoreBundle\\EventListener\\TranslationDebugListener'] = new \Pimcore\Bundle\CoreBundle\EventListener\TranslationDebugListener(($this->services['translator'] ?? $this->getTranslatorService()), 'pimcore_debug_translations');`

Does anyone have any idea why the error occurs in development mode after updating?
Clearing symfony and pimcore cache won't fix the problem. Composer update command ran without any problems.

Below is an excerpt from my configuration (concerning the translation):
**config/packages/translation.yaml**
```
framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
```

**var/config/system.yml**
```
pimcore:
    general:
        domain: xxx.dev.de
        redirect_to_maindomain: false
        language: en
        valid_languages: 'en,hr,cs,nl,fr,de,de_AT,el,hu,mk,pl,ro,sr'
        fallback_languages:
            en: ''
            hr: en
            cs: en
            nl: en
            fr: en
            de: en
            de_AT: de
            el: en
            hu: en
            mk: en
            pl: en
            ro: en
            sr: en
        default_language: en
        debug_admin_translations: false
```
