### ISSUE TITLE
[Bug]: config_test in Bundles is ignored when running function tests

### ISSUE THREAD

**Issue by flopes89** [pimcore/pimcore#10232]
### Expected behavior

`config_test.yml` file in `/src/MyBundle/Resources/config` should be read so the parameter overwrites apply when bootstrapping services

### Actual behavior

`config_test.yml` file is ignored - only defaults in `config.yml` are read

### Steps to reproduce

I have a Bundle that also contains `Resources/config/config_test.yml` files to overwrite some parameters during testing:

```
imports:
  - { resource: config.yml }

parameters:
  job_folder_root: "%kernel.project_dir%/tests/_output/myjobs/"
  step_xml_root: "%kernel.project_dir%/tests/_data/"
```

where `config.yml` is:

```
twig:
  paths:
    "%kernel.project_dir%/src/MyBundle/Resources/views": MyBundle

parameters:
  job_folder_root: "%kernel.project_dir%/var/tmp/myjobs/"
  step_xml_root: "%kernel.project_dir%/_data/"
```

When running this via codecept functional testing, the actual parameters are always those defined in the `config.yml` file, even though I would expect them to be overwritten by the ones in `config_test.yml`
