### ISSUE TITLE
[Bug]: Unrecognized option "webp_auto_support" under "pimcore.assets.image.thumbnails". 

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10533]
### Expected behavior

Following [the documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Assets/Working_with_Thumbnails/Image_Thumbnails.html#page_WebP-Support) we should not have WebP images generated by the server.

### Actual behavior

We get the following Symfony error:
> Unrecognized option "webp_auto_support" under "pimcore.assets.image.thumbnails". Available options are "auto_clear_temp_files", "clip_auto_support".

### Steps to reproduce

In `config.yaml` set:
```yaml
pimcore:
    assets:
        image:
            thumbnails:
                webp_auto_support: false
```
