### ISSUE TITLE
[Bug]: Install Static Route with two % since 10.2

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#10608]
### Expected behavior

Static Routes containing two % sign that are installed via API don't work anymore. The Problem is that % is a reserved "keyword" for resolving dynamic parameters like env vars.  Installed route should look like (note that % is escaped with another %):

```yaml
pimcore:
    staticroutes:
        definitions:
            0d275fff-e1cc-4f46-8fc1-ee9544065dd5:
                name: coreshop_partial_cart_add
                pattern: '/(\w+)\/_partial\/cart\/add\/([0-9]+)$/'
                reverse: '/%%_locale/_partial/cart/add/%%product'
                controller: 'CoreShop\Bundle\FrontendBundle\Controller\CartController:addItemAction'
                variables: '_locale,product'
                defaults: null
                siteId: null
                methods: {  }
                priority: 3
                creationDate: 1634228168
                modificationDate: 1634228168
```

Resulting in following error:

```
Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException^ {#5561
  -key: "_locale/shop/customer/addresses/delete/"
  -sourceId: null
  -sourceKey: null
  -alternatives: []
  -nonNestedAlternative: null
  #message: "You have requested a non-existent parameter "_locale/shop/customer/addresses/delete/"."
  #code: 0
  #file: "./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php"
  #line: 93
  trace: {
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:93 { …}
    ./vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php:61 { …}
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:217 { …}
    Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->Symfony\Component\DependencyInjection\ParameterBag\{closure}() {}
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:206 { …}
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:175 { …}
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:165 { …}
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:165 { …}
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:165 { …}
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:165 { …}
    ./vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:165 { …}
    ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:62 { …}
    ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 { …}
    ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
    ./vendor/symfony/dependency-injection/ContainerBuilder.php:744 { …}
    ./vendor/symfony/http-kernel/Kernel.php:545 { …}
    ./vendor/pimcore/pimcore/lib/Kernel.php:237 { …}
    ./vendor/symfony/http-kernel/Kernel.php:786 { …}
    ./vendor/symfony/http-kernel/Kernel.php:125 { …}
    ./vendor/pimcore/pimcore/lib/Kernel.php:216 { …}
    ./src/Kernel.php:37 {
      Kernel->boot()^
      › 
      ›     parent::boot();
      › }
    }
    ./vendor/pimcore/pimcore/lib/Bootstrap.php:255 { …}
    ./vendor/pimcore/pimcore/lib/Bootstrap.php:60 { …}
    ./bin/console:44 { …}
  }
}

```

### Actual behavior

```yaml
pimcore:
    staticroutes:
        definitions:
            0d275fff-e1cc-4f46-8fc1-ee9544065dd5:
                name: coreshop_partial_cart_add
                pattern: '/(\w+)\/_partial\/cart\/add\/([0-9]+)$/'
                reverse: '/%_locale/_partial/cart/add/%product'
                controller: 'CoreShop\Bundle\FrontendBundle\Controller\CartController:addItemAction'
                variables: '_locale,product'
                defaults: null
                siteId: null
                methods: {  }
                priority: 3
                creationDate: 1634228168
                modificationDate: 1634228168

```

### Steps to reproduce

```php
$route = Staticroute::create();
$route->setName('coreshop_cart_create_qoute');
$route->setPattern('/(\w+)\/shop\/cart\/quote$/');
$route->setReverse('/%_locale/shop/cart/quote');
$route->setController('CoreShop\Bundle\FrontendBundle\Controller\CartController:createQuoteAction');
$route->setVariables('_locale');
$route->setPriority(3);
$route->save();
```
