### ISSUE TITLE
[Bug][Improvement]: Pimcores Authentication built on deprecated Symfony components?

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#10828]
### Expected behavior

Trying to implement a Pimcore-independent user login built on Symfonys most recent authentication mechanism should be possible following the official documentation: https://symfony.com/doc/current/components/security/authentication.html

### Actual behavior

Trying to implement Symfonys most recent Authentication system I am getting the following error: 

`Unrecognized option "authenticators" under "security.firewalls.pimcore_admin".`

It seems like the following part of security.yml is causing the problem (removed guard, otherwise you have another exception):

```
        # Pimcore admin form login // DO NOT CHANGE!
        pimcore_admin:
            anonymous: ~
            pattern: ^/admin(/.*)?$
            # admin firewall is stateless as we open the admin
            # session on demand for non-blocking parallel requests
            stateless: true
            provider: pimcore_admin
            logout:
                path:   /admin/logout
                target: /admin/login
                success_handler: Pimcore\Bundle\AdminBundle\Security\LogoutSuccessHandler
            guard:
                entry_point: Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator
                authenticators:
                    - Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator
            two_factor:
                auth_form_path: /admin/login/2fa                   # Path or route name of the two-factor form
                check_path: /admin/login/2fa-verify                # Path or route name of the two-factor code check
                default_target_path: /admin            # Where to redirect by default after successful authentication
                always_use_default_target_path: false  # If it should always redirect to default_target_path
                auth_code_parameter_name: _auth_code   # Name of the parameter for the two-factor authentication code
                trusted_parameter_name: _trusted       # Name of the parameter for the trusted device option
                multi_factor: false                    # If ALL active two-factor methods need to be fulfilled (multi-factor authentication)
```

I suspect that Pimcore still relies on Symfonys old authentication mechanism which is deprecated and will be removed soon. Please correct me and close the ticket if this is my mistake. I also heard other developers complaining about it. Can you upgrade this to be up to date?

Stack trace:
```
Symfony\Component\Config\Definition\Exception\InvalidConfigurationException:
Unrecognized option "authenticators" under "security.firewalls.pimcore_admin". Available options are "access_denied_handler", "access_denied_url", "anonymous", "context", "custom_authenticators", "entry_point", "form_login", "form_login_ldap", "guard", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "lazy", "login_link", "login_throttling", "logout", "methods", "pattern", "pimcore_admin_pre_auth", "provider", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "two_factor", "user_checker", "x509".

  at /var/www/html/vendor/symfony/config/Definition/ArrayNode.php:314
  at Symfony\Component\Config\Definition\ArrayNode->normalizeValue(array('authenticators' => array('Pimcore\\Bundle\\AdminBundle\\Security\\Guard\\AdminAuthenticator')))
     (/var/www/html/vendor/symfony/config/Definition/BaseNode.php:410)
  at Symfony\Component\Config\Definition\BaseNode->normalize(array('anonymous' => null, 'pattern' => '^/admin(/.*)?$', 'stateless' => true, 'provider' => 'pimcore_admin', 'logout' => array('path' => '/admin/logout', 'target' => '/admin/login', 'success_handler' => 'Pimcore\\Bundle\\AdminBundle\\Security\\LogoutSuccessHandler'), 'entry_point' => 'Pimcore\\Bundle\\AdminBundle\\Security\\Guard\\AdminAuthenticator', 'authenticators' => array('Pimcore\\Bundle\\AdminBundle\\Security\\Guard\\AdminAuthenticator'), 'two_factor' => array('auth_form_path' => '/admin/login/2fa', 'check_path' => '/admin/login/2fa-verify', 'default_target_path' => '/admin', 'always_use_default_target_path' => false, 'auth_code_parameter_name' => '_auth_code', 'trusted_parameter_name' => '_trusted', 'multi_factor' => false)))
     (/var/www/html/vendor/symfony/config/Definition/PrototypedArrayNode.php:253)
  at Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue(array('dev' => array('pattern' => '^/(_(profiler|wdt)|css|images|js)/', 'security' => false), 'pimcore_admin_webdav' => array('pattern' => '^/admin/asset/webdav', 'provider' => 'pimcore_admin', 'http_basic' => null), 'pimcore_admin' => array('anonymous' => null, 'pattern' => '^/admin(/.*)?$', 'stateless' => true, 'provider' => 'pimcore_admin', 'logout' => array('path' => '/admin/logout', 'target' => '/admin/login', 'success_handler' => 'Pimcore\\Bundle\\AdminBundle\\Security\\LogoutSuccessHandler'), 'entry_point' => 'Pimcore\\Bundle\\AdminBundle\\Security\\Guard\\AdminAuthenticator', 'authenticators' => array('Pimcore\\Bundle\\AdminBundle\\Security\\Guard\\AdminAuthenticator'), 'two_factor' => array('auth_form_path' => '/admin/login/2fa', 'check_path' => '/admin/login/2fa-verify', 'default_target_path' => '/admin', 'always_use_default_target_path' => false, 'auth_code_parameter_name' => '_auth_code', 'trusted_parameter_name' => '_trusted', 'multi_factor' => false))))
```

### Steps to reproduce

Simply try to build and authentication mechanism as described here: https://symfony.com/doc/current/components/security/authentication.html
