### ISSUE TITLE
[Bug][Email]: impossible to send emails

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#11140]
### Expected behavior

After adding the email configuration as explained in the [docs](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Email_Framework/index.html), pimcore should be albe to send emails.

### Actual behavior

After adding email configuration to config/config.yml nothing happens (the notification "It seems that the mail settings are incomplete" still appears) and emails can't be send.

### Steps to reproduce

In pimcore 10.1.5 I was still able to send emails. After update to 10.2.8 it's not possible to send any emails anymore.

Added following test settings to config/config.yml, but email still can't be send and is not recognized:
```
pimcore:
    email:
        sender:
            name: 'Test Sender'
            email: test@test.com
        return:
            name: ''
            email: ''

framework:
    mailer:
        transports:
            main: smtp://test@test.com:test@test.com:587

```

Already tested in pimcore demo, same results
