### ISSUE TITLE
[Bug]: Update form 10.3.0 to 10.3.1 - Invalid configuration for path "framework.mailer": "dsn" and "transports" cannot be used together.

### ISSUE THREAD

**Issue by Stefan-JustMe69-SQ** [pimcore/pimcore#11471]
### Expected behavior

Normal update process without problems

### Actual behavior

After udate process, clear cache throws exception. Backend ist not useable
no login is possible. Even downgrade to 10.3.0 is showing this error. Pimcore is not useable anymore.

### Steps to reproduce

Update from 10.3.0 to 10.3.1 - and same on downgrade from 10.3.1 to 10.3.0

Having a SMTP-Account as mailer defined in config/config.yml, like:

```
framework:
    email:
        sender:
            name: 'Just a Name'
            email: '12345@domaincom'
        return:
            name: ''
            email: ''

    mailer:
        transports:
            main: smtp://12345:abc@smtpserver:465
```
