### ISSUE TITLE
[Bug]: PHP 8.1 Deprecated: Implicit conversion from float 79.5 to int loses precision when cropping images

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#11799]
### Expected behavior

Image dimensions passed as integers (since the image can't have .5 pixels)

### Actual behavior

Image dimensions passed as floats

### Steps to reproduce

Crop an image using the built in Pimcore features, with the image dimensions such that the `$x` passed here gets calculated to a decimal. The exact calculation depends on the original image size so can't provide exact details:

```php
// /vendor/pimcore/pimcore/lib/Image/Adapter/Imagick.php in Pimcore\Image\Adapter\Imagick::createCompositeImageFromResource at line 684

// $x = 79.5 here for me
$newImage->compositeImage($this->resource, $composite, $x, $y);
```

**Comment by brusch** [comment]
Maybe a stupid question, but why should someone use decimals for pixels? 😵‍💫

**Comment by NiklasBr** [comment]
Let's say you have a vector image (e.g. EPS or SVG) and want to composite it onto a bitmap image, such as a PNG image. [This might help explain it a bit](https://krita-foundation.tumblr.com/post/150234710828/how-come-the-brushes-can-be-resized-with-decimal) why it can be useful.

But in this case I would think that converting to `int` here would suffice: https://github.com/pimcore/pimcore/blob/1dcbc2254a7a3addde3f7a9308715165cf4fd2cb/lib/Image/Adapter/Imagick.php#L593-L594

**Comment by dkarlovi** [comment]
Nice example @NiklasBr! I could see subpixel precision might be valuable, but in that case the API is wrong if this is allowed here.

I guess casting to int is correct since that happens anyway implicitly, the purpose of this deprecation is to warn the developer about it happening so they might fix it in some way explicitly.

The intent of the bug report here is the misalignment of the type requested and type received, it doesn't really matter which type is used, only that they're the same when in use. :)

**Comment by brusch** [comment]
@dkarlovi can you maybe provide us a PR for this issue? Thanks in advance 🤗

**Comment by kingjia90** [comment]
Thank you for reporting!

This issue should be closed since Pimcore 11, right?
https://github.com/pimcore/pimcore/blob/d31d686fdeff7fc304ac24a03ab9718a1bd43e59/lib/Image/Adapter/Imagick.php#L554-L555
https://github.com/pimcore/pimcore/blob/d31d686fdeff7fc304ac24a03ab9718a1bd43e59/lib/Image/Adapter/Imagick.php#L607
Please re-open if there's any follow up to do on it

**Comment by JakobBruening** [comment]
I still experience the issue on Pimcore [11.5.0](https://github.com/pimcore/pimcore/releases/tag/v11.5.0) and PHP 8.3 @kingjia90.

The issue occurs here
https://github.com/pimcore/pimcore/blob/fcedfd356ba726ba238996aa4777b2178366367d/lib/Image/Adapter/Imagick.php#L530
https://github.com/pimcore/pimcore/blob/fcedfd356ba726ba238996aa4777b2178366367d/lib/Image/Adapter.php#L190

Currently, I experience the issue only with one thumbnail, that is configured like this:
```yaml
pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    offer_sm:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 300
                                    height: 180
                                    positioning: center
                                    forceResize: false
                        medias: {  }
                        name: offer_sm
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 60
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1734183079
                        creationDate: 1688791839
                        preserveAnimation: false
```
