### ISSUE TITLE
[Bug]: \Pimcore\Model\Asset\Image\Thumbnail::getPath doesn't account for pimcore.assets.frontend_prefixes

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#11914]
### Expected behavior

```php
\Pimcore\Model\Asset\Image\Thumbnail::getImageTag();
```

produces a valid `<img/>` tag with
```yaml
pimcore:
   assets:
       frontend_prefixes:
           thumbnail: https://tavi-12345678990.cloudfront.net/thumbnail
```

defined.

### Actual behavior

Currently, the defined prefix is not used, the `<img/>` tag points to a broken URL.

### Steps to reproduce

1. Setup a remove filesystem and define a thumbnail prefix as described above
2. upload an image and echo `\Pimcore\Model\Asset\Image\Thumbnail::getImageTag()`, it will not use the prefix, resulting in a broken image

**Comment by brusch** [comment]
For me this works just as expected ... using the demo I've the following code/configs: 

```yaml
pimcore:
    assets:
        frontend_prefixes:
            thumbnail: https://bax.pimcore.com
```

```php
        $image = Asset\Image::getById(360);
        $thumbnail = $image->getThumbnail('exampleCover');
        echo $thumbnail->getImageTag();
``` 

Output is: 
```html
<img src="https://bax.pimcore.com/Sample%20Content/Example%20Images/360/image-thumb__360__exampleCover/Mercedes-Benz%20300%20SL%20Front.jpg" width="275" height="150" alt="" loading="lazy" srcset="https://bax.pimcore.com/Sample%20Content/Example%20Images/360/image-thumb__360__exampleCover/Mercedes-Benz%20300%20SL%20Front.jpg 1x, /Sample%20Content/Example%20Images/360/image-thumb__360__exampleCover/Mercedes-Benz%20300%20SL%20Front@2x.jpg 2x" />
```
