### ISSUE TITLE
[Bug]: Pimcore serving deferred thumbnail URL even though the thumbnail exists (Azure Storage used)

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12055]
### Expected behavior

I have assets set up like this:

```yaml
flysystem:
    storages:
        pimcore.thumbnail.storage:
            adapter: 'flysystem.adapter.azure.thumbnail'
            visibility: public

pimcore:
    assets:
        frontend_prefixes:
            source: 'https://storage.example.com/asset'
            thumbnail: 'https://storage.example.com/thumbnail'
```

And it works, the files get created in the correct, expected place, etc.

The issue is, the `\Pimcore\Model\Asset\Image\Thumbnail::getPath` seems to return a deferred URL instead of the storage (static file, with the frontend prefix) quite often, even though the image exists on the remote storage (using Azure Blob Storage).

What's more, it seems the request then sometimes actually crops and writes over the existing file in the storage, meaning it can take quite a long time, all of which unnecessary.

### Actual behavior

Even though the thumbnail exists in storage, the deferred (crop on demand) URL version is generated.

### Steps to reproduce

The static URL version gets generated if the thumbnail exists.
