### ISSUE TITLE
[Feature]: make configuration storage locations configurable via Pimcore's Symfony config tree

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12066]
### Feature description

Currently, [the config storage location tweaks are available via env vars](https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Configuration_Environments.html#page_Configuration-Storage-Locations-Fallbacks).

This, to me, feels counter-intuitive because this configuration is quite central to Pimcore's behaviour, it should be manageable app-wide (meaning, the app should explicitly allow its own config to be environment-specific). This mostly means this shouldn't be random environment vars which do this from thin air, it should be explicitly stated in Pimcore's own config:

```yaml
pimcore:
   config:
       storage:
           image_thumbnails: settings-store
```

This allow the app to enforce where it expects the config to be, with the developer being able to explicitly allow the current behaviour

```yaml
pimcore:
   config:
       storage:
           image_thumbnails: '%env(PIMCORE_WRITE_TARGET_IMAGE_THUMBNAILS)%'
```

but being able to ship this decision with the app.

In general, I feel Pimcore is way too reliant on environment variables which should all actually be Symfony config, in which case the developer would be able to make them use env vars, hardcode, make them configurable per (Symfony) environment, etc.

Note, **this does not work**:

```yaml
parameters:
    env(PIMCORE_WRITE_TARGET_IMAGE_THUMBNAILS): settings-store
```
