### ISSUE TITLE
[Bug]: v10.5.X "test" ENV Login fails with CSRF error

### ISSUE THREAD

**Issue by Fahl-Design** [pimcore/pimcore#12918]
### Expected behavior

Login works as expected

- tested with `enable_authenticator_manager: true` and `enable_authenticator_manager: false`

### Actual behavior

> Detected CSRF Attack! Do not do evil things with pimcore ... ;-)

```
Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException:


  at vendor/pimcore/pimcore/bundles/AdminBundle/Security/CsrfProtectionHandler.php:68
  at Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler->checkCsrfToken(object(Request))
     (vendor/pimcore/pimcore/bundles/AdminBundle/EventListener/CsrfProtectionListener.php:92)
  at Pimcore\Bundle\AdminBundle\EventListener\CsrfProtectionListener->handleRequest(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/http-kernel/HttpKernel.php:128)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:54)           
``` 

### Steps to reproduce

- set ENV to "test"
- try to login

**Comment by solverat** [comment]
Just for the record: All our acceptance tests are broken since months (I guess even since 10.1) because of this. 

@Fahl-Design: Have you been able to find out anything in the meantime?

**Comment by Fahl-Design** [comment]
@solverat well kind of... I added a `framework.session` config to the test env. The pimcore test session configuration looks broken

file: `config/packages/tests/framework.yaml`

```yaml
#### SYMFONY OVERRIDES 

framework:
    profiler: { only_exceptions: false }
    test: true
    session:
        handler_id: RedisSessionHandler # add your default session handler like: \Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        enabled: true
        #storage_id: session.storage.native
        cookie_httponly: true
        gc_probability: 1
        save_path: /php/var/cache/test/sessions
        metadata_update_threshold: 0

```

**Comment by solverat** [comment]
@Fahl-Design Thanks for your feedback.

I found the issue. And i also found out, that i already reported it...

https://github.com/pimcore/pimcore/issues/11042#issuecomment-1006614692

However, changing the storage_id did the trick:

```yaml

framework:
    session:
        storage_id: session.storage.native                  # pimcore < 10.5
        storage_factory_id: session.storage.factory.native  # pimcore >= 10.5
```

So the test configuration is - like you described - broken.
Maybe pimcore should add some more functional tests...


https://github.com/pimcore/pimcore/blob/b2110bb3c416cbf4a7fce967fe98a0e031d642a0/bundles/CoreBundle/config/pimcore/test.yaml#L4


Related: https://github.com/pimcore/pimcore/issues/13614
