### ISSUE TITLE
[Bug]: WebDav authentication fails on both 

### ISSUE THREAD

**Issue by ChrisB9** [pimcore/pimcore#12913]
### Expected behavior

It's possible to login into webdav.

### Actual behavior

When accessing the webdav user interface, after login, the following exception occurs.

![image](https://user-images.githubusercontent.com/7099583/185407670-50766b45-50eb-49c8-96b9-8c1a27d70b8b.png)

An error also occurs on the [demo.pimcore.com](http://demo.pimcore.com/admin/asset/webdav) and https://demo.pimcore.fun/admin/asset/webdav page, but because that website is not in Debugging-Mode I wasn't able to determine, whether these are the same issues. I do believe, though, that they actually might be.

**Investigation-Part**:

The issue most likely is related to this change introduced with symfony 5.3 and pimcore 10.x.
```yaml
security:
  enable_authenticator_manager: true
```

I saw, that @dpfaffenbauer had a similar problem before v10.1 got released. Though there the issue seemed to be related to custom elements not the webdav.  
Anyways, I did try to include:
```yaml
pimcore:
  security:
    factory_type: password_hasher
```
in my configuration, but the outcome was still the same.

In my system, I am also using pimcore-members and had the same issue there a while ago and solved it through adding the `MembersUser` to the password_hashers configuration.

I tried the same style of configuration then with the `Pimcore\Bundle\AdminBundle\Security\User\User` but that led continuous basic auth prompts, even though I inputted the correct credentials. Interestingly the normal Admin-Login continued to work.

```yaml
security:
  password_hashers:
    Pimcore\Model\DataObject\MembersUser: 'auto'
    Pimcore\Bundle\AdminBundle\Security\User\User: 'auto'
```

### Steps to reproduce

1. Navigate to /admin/asset/webdav, eg. https://demo.pimcore.fun/admin/asset/webdav
2. Enter valid credentials
3. The error should then already be there

### Possible solution

The following actually solves the problem but I am not sure, whether that is the intended way of configuring the webdav access:

```yaml
pimcore:
  security:
    factory_type: password_hasher
    password_hasher_factories:
      Pimcore\Bundle\AdminBundle\Security\User\User: pimcore_admin.security.password_hasher_factory
```
