### ISSUE TITLE
[Bug]: Dont output avif if disabled in thumbnail settings

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#13525]
### Expected behavior

Dont output avif if disabled

### Actual behavior

Avif is included in picture tags for thumbnails, even if they are disabled.

### Steps to reproduce

1. Enable avif via config:
```
pimcore:
    assets:
        image:
            thumbnails:
                auto_formats:
                    webp:
                        enabled: true
                    avif:
                        enabled: true
                        quality: 85
```

2. Generate thumbnails for any image with format "auto"

3. Disable avif via config:
```
pimcore:
    assets:
        image:
            thumbnails:
                auto_formats:
                    webp:
                        enabled: true
                    avif:
                        enabled: false
```

4. Generate output for picture tag, avif format will be included in the html output, even if disabled
