### ISSUE TITLE
[Bug]: twig sandbox causes error when sending emails after update

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#13788]
### Expected behavior

When updating from `10.5.8` to >`10.5.9` (in my case `10.5.12`), emails should be sent just as before.

### Actual behavior

After the update, emails were not sent. Instead the error in the following line was thrown:

https://github.com/pimcore/pimcore/blob/f2fa96ee1db3e0ef5ca4cd8a47c4d8aabe5d9d1b/lib/Mail.php#L667

Which stated that the `default` filter is not allowed. 

Note that adding the following config fixed the issue for me:
```
 pimcore:
    templating_engine:
        twig:
            sandbox_security_policy:
                filters: ['default']
```

### Steps to reproduce

1. Create E-Mail Template
2. Add WYSIWYG
3. Add content like the one in the screenshot
4. Send Test-Email

<img width="326" alt="image" src="https://user-images.githubusercontent.com/57256630/207337834-fe4dd965-6f51-49e0-9255-2159277de0ca.png">

Reproducible on demo:

![image](https://user-images.githubusercontent.com/57256630/207355950-bae5bfb4-748a-456f-9d72-e639ea842c52.png)
