### ISSUE TITLE
[Bug]: pimcore install ignores connection parameters.

### ISSUE THREAD

**Issue by khusseini** [pimcore/pimcore#14135]
### Expected behavior

When running 
```
 vendor/bin/pimcore-install --ignore-existing-config --admin-username=admin --admin-password=admin --mysql-ssl-cert-path=${MYSQL_CERT_PATH} --mysql-username=${DATABASE_USER} --mysql-password=${DATABASE_PASSWORD} --mysql-database=${DATABASE_NAME}
```

The installation should go through.

### Actual behavior

Getting the error:

```
[ERROR] The following errors were encountered during installation                                                      


 * Couldn't establish connection to MySQL: An exception occurred in driver: SQLSTATE[HY000] [3159] Connections using insecure transport are prohibited while --require_secure_transport=ON.
 * 
```

### Steps to reproduce

- create a new pimcore 10.4 repository
- install mysql with ssl
- run ` vendor/bin/pimcore-install --ignore-existing-config --admin-username=admin --admin-password=admin --mysql-ssl-cert-path=${MYSQL_CERT_PATH} --mysql-username=${DATABASE_USER} --mysql-password=${DATABASE_PASSWORD} --mysql-database=${DATABASE_NAME}` where the $DATABASE_* variables contain proper mysql credentials.

**Comment by mattamon** [comment]
Hey @khusseini,

is this specific for 10.4 only? Could you please try to reproduce the error for the latest 10.5 version?

**Comment by mattamon** [comment]
@khusseini,

Any update? :)

**Comment by mattamon** [comment]
I will close the issue for now. If the problems appear again, please feel free to open another issue. Thank you!

**Comment by khusseini** [comment]
Hi there, my apologies for the late reply. I have tried the installer now with 10.5 but no luck. The pimcore installation still fails:
```
pimcore-install --ignore-existing-config --admin-username=admin --admin-password=admin -n --mysql-ssl-cert-path=/etc/mysql-ca/cert.crt

[WARNING] Using sensitive options (--admin-username) on the command line interface can be insecure.
Consider using the interactive prompt or the PIMCORE_INSTALL_ADMIN_USERNAME environment variable instead.

[WARNING] Using sensitive options (--admin-password) on the command line interface can be insecure.
Consider using the interactive prompt or the PIMCORE_INSTALL_ADMIN_PASSWORD environment variable instead.


Running installation. You can find a detailed install log in var/log/integration.log

Starting the install process...

  0/11 [>---------------------------]   0%


                                                                                                                        
 [ERROR] The following errors were encountered during installation                                                      
                                                                                                                        

 * Couldn't establish connection to MySQL: An exception occurred in driver: SQLSTATE[HY000] [3159] Connections using insecure transport are prohibited while --require_secure_transport=ON.
```


```bash
composer show | grep pimcore
asioso/pimcore-quicktranslate-module                v3.0.3    With this Bundle you can automatically translate your content via DeepL Interface.
pimcore/data-hub                                    v1.2.0    Pimcore Datahub
pimcore/data-importer                               v1.6.3   
pimcore/number-sequence-generator                   v1.0.7   
pimcore/output-data-config-toolkit-bundle           v4.1.9   
pimcore/pimcore                                     v10.5.14  Content & Product Management Framework (CMS/PIM/E-Commerce)
```

**Comment by mattamon** [comment]
Hey @khusseini,

I checked your error message again and this is not a pimcore specific issue. 
https://github.com/kimai/kimai/discussions/3247
https://forums.phpfreaks.com/topic/305817-warning-mysqli_real_connect-hy0003159-connections-using-insecure-transport-are-prohibited-while-require_secure_transporton/
https://support.quest.com/de-de/foglight-for-databases/kb/4230801/-connections-using-insecure-transport-are-prohibited-while-require_secure_transport-on-error-using-mysql-agent

Please try to reconfigure your database setup. 
I won't reopen the issue since it is not pimcore specific.

**Comment by khusseini** [comment]
I have imported a dump from a different fresh installation and pimcore works. The only thing that doesn't work is the mysql ssl connection between the pimcore installer and the database. Since other PHP, nodejs etc. application and even pimcore itself can access the database over ssl with my current configuration I can with confidence say that it is pimcore-installer specific.

**Comment by jdreesen** [comment]
How did you configure your Doctrine DBAL/PDO connection in your running Pimcore? Especially: which parameters do you use to configure the cert?

The `--mysql-ssl-cert-path` option from the installer sets the [`PDO::MYSQL_ATTR_SSL_CA`](https://www.php.net/manual/en/ref.pdo-mysql.php#pdo.constants.mysql-attr-ssl-ca) (see here: https://github.com/pimcore/pimcore/blob/10.5/bundles/InstallBundle/Installer.php#L333)

**Comment by mattamon** [comment]
The support for ssl was added back in 2019. 
https://github.com/pimcore/pimcore/pull/4977

Maybe @mgomse can help with this topic?

**Comment by khusseini** [comment]
This is my doctrine configuration for my pimcore instance. As I mentioned, once the pimcore database structure exists, I can use pimcore normally, the only thing not working is the installer.

```
doctrine:
    dbal:
        connections:
            default:
                driver: "pdo_mysql"
                server_version: "8.0.27"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                user: "%env(DATABASE_USER)%"
                password: "%env(DATABASE_PASSWORD)%"
                dbname: "%env(DATABASE_NAME)%"
                host: "%env(DATABASE_HOST)%"
                port: "%env(DATABASE_PORT)%"
                url: "%env(resolve:DATABASE_URL)%"
                mapping_types:
                    enum: string
                    bit: boolean
```

```
doctrine:
  dbal:
    connections:
      default:
        options:
          "1009": "%env(MYSQL_CERT_PATH)%"
          "1014": false
  orm:
    auto_generate_proxy_classes: false
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool
```

EDIT: The config is split up as the SSL configuration is an overlay over the general doctrine config with the connection parameter.

**Comment by mattamon** [comment]
Hey @khusseini,

thank you for providing more details. I reopened the issue and will check internally with our infrastructure expert.

**Comment by jdreesen** [comment]
Well, you have set the options [`PDO::MYSQL_ATTR_SSL_CA (1009)`](https://www.php.net/manual/en/ref.pdo-mysql.php#pdo.constants.mysql-attr-ssl-ca) (which the installer also sets) as well as [`PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT (1014)`](https://www.php.net/manual/en/ref.pdo-mysql.php#pdo.constants.mysql-attr-ssl-verify-server-cert) (which the installer does _not_ set). Maybe that's the issue?

**Comment by khusseini** [comment]
> Well, you have set the options [`PDO::MYSQL_ATTR_SSL_CA (1009)`](https://www.php.net/manual/en/ref.pdo-mysql.php#pdo.constants.mysql-attr-ssl-ca) (which the installer also sets) as well as [`PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT (1014)`](https://www.php.net/manual/en/ref.pdo-mysql.php#pdo.constants.mysql-attr-ssl-verify-server-cert) (which the installer does _not_ set). Maybe that's the issue?


My apologies for the late reply. 

The options you mentioned are set like so
```yaml
doctrine:
  dbal:
    connections:
      default:
        options:
          "1009": "%env(MYSQL_CERT_PATH)%"
          "1014": false
```

to run the installer I use the following command:

```bash
pimcore-install --ignore-existing-config --admin-username=admin --admin-password=admin -n --mysql-ssl-cert-path=/etc/mysql-ca/cert.crt
```
