### ISSUE TITLE
[Improvement]: Enhance document configs for more flexibility 

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14268]
## Current situation
When it comes to new document types, menu structures are not flexible enough. 
There are some hardcoded parts that need to be configurable to make it more useful.

E.g.
https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/js/pimcore/document/tree.js
```js
if (addDocuments && record.data.type != "printcontainer") {
    menu.add(new Ext.menu.Item({
        text: t('add_page'),
        iconCls: "pimcore_icon_page pimcore_icon_overlay_add",
        menu: documentMenu.page,
        hideOnClick: false
    }));
}
```
```js
var childSupportedDocument = (record.data.type == "page" || record.data.type == "folder"
            || record.data.type == "link" || record.data.type == "hardlink"
            || record.data.type == "printcontainer");
```

https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/js/pimcore/document/document.js
```js
  menu: [{
                text: t("new_document"),
                hidden: !in_array(this.getType(), ["page", "snippet", "email", "printpage", "printcontainer"]),
                iconCls: "pimcore_icon_page pimcore_icon_overlay_add",
                menu: [{
                    text: t("using_inheritance"),
                    hidden: !in_array(this.getType(), ["page", "snippet", "printpage", "printcontainer"]),
                    handler: this.createTranslation.bind(this, true),
                    iconCls: "pimcore_icon_clone"
                }
            }
```

https://github.com/pimcore/pimcore/blob/11.x/bundles/AdminBundle/public/js/pimcore/settings/docTypes.js
```js
   {
                text: t("type"),
                flex: 50,
                sortable: true,
                dataIndex: 'type',
                editor: new Ext.form.ComboBox({
                    triggerAction: 'all',
                    editable: false,
                    store: ["page", "snippet", "email", "newsletter", "printpage", "printcontainer"]
                })
            },
```

## Improvment
Make all this settings configurable eitehr with new configs or try to enhance  type_definitions e.g.
```yaml
documents:
    type_definitions:
        map:
            page:
                class: \Pimcore\Model\Document\Page
                translatable: true
                valid_tables: 'page'
                direct_route: true
                translatable_inheritance: true
```
