### ISSUE TITLE
[System Settings] Change valid_languages format

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14372]
Currently the `valid_languages` is configured CSV: 

```yaml
pimcore:
    general:
        valid_languages: 'en,de,fr'
```

This was for legacy reasons and we should change that to proper  array format: 

```yaml
pimcore:
    general:
        valid_languages: 
            - en
            - de
            - fr
```
