### ISSUE TITLE
[Bug]: CMYK thumbnails are broken when using Imagick and setBackgroundColor

### ISSUE THREAD

**Issue by maximilian-walter** [pimcore/pimcore#14543]
### Expected behavior

Thumbnails where `preserveColor` is `true` should preserve the colorspace, even if the method `setBackgroundImage` is used.

### Actual behavior

The method `setBackgroundImage` creates a new image, using always sRGB as colorspace. If the original file is CYMK and the option `preserveColor` is `true`, CMYK data is added to the new image, which results in an sRGB file with inverted color.

### Steps to reproduce

Create a new image thumbnail which preserves color but calls `setBackgroundColor`. Example:

```yaml
pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    example:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 720
                                    height: 720
                                    forceResize: false
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#ffffff'
                        medias: {  }
                        name: example
                        description: ''
                        group: ''
                        format: JPEG
                        quality: 85
                        highResolution: 0.0
                        preserveColor: true
                        preserveMetaData: true
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1674506504
                        creationDate: 1628096419
                        preserveAnimation: false
```
Upload a CMYK file to Pimcore. Example: [example-cmyk.jpg](https://user-images.githubusercontent.com/1067260/223160765-0eae2618-1fcc-4a41-b016-e659a69bdfc1.jpg)

Then download and open the generated thumbnail: The colors are inverted the colorspace was set to sRGB instead of CMYK. Example: [example-thumbnail.jpg](https://user-images.githubusercontent.com/1067260/223162768-54004983-72fe-4992-a401-ca93a0ca43f0.jpg)

You can use ìdentify` (from ImageMagick) to confirm this:

```shell
$ identify thumbnail.jpg
thumbnail.jpg JPEG 596x720 596x720+0+0 8-bit sRGB 179586B 0.000u 0:00.000
```

in comparision the original file:

```shell
$ identify original.jpg 
original.jpg JPEG 1061x1280 1061x1280+0+0 8-bit CMYK 889633B 0.000u 0:00.000
```

To fix the issue, we had to inherit the colorspace and image profiles in `\Pimcore\Image\Adapter\Imagick::createCompositeImageFromResource()` using the following patch:

```patch
--- lib/Image/Adapter/Imagick.php
+++ lib/Image/Adapter/Imagick.php
@@ -675,6 +675,13 @@
         if ($this->checkPreserveAnimation()) {
             foreach ($this->resource as $i => $frame) {
                 $imageFrame = $this->createImage($width, $height, $color);
+                if (method_exists($imageFrame, 'setColorspace')) {
+                    $imageFrame->setColorspace($this->resource->getColorspace());
+                }
+                $imageFrame->setImageColorspace($this->resource->getImageColorspace());
+                foreach ($this->resource->getImageProfiles() as $name => $profile) {
+                    $imageFrame->setImageProfile($name, $profile);
+                }
                 $imageFrame->compositeImage($frame, $composite, $x, $y);
                 if (!$newImage) {
                     $newImage = $imageFrame;
@@ -684,6 +691,13 @@
             }
         } else {
             $newImage = $this->createImage($width, $height, $color);
+            if (method_exists($newImage, 'setColorspace')) {
+                $newImage->setColorspace($this->resource->getColorspace());
+            }
+            $newImage->setImageColorspace($this->resource->getImageColorspace());
+            foreach ($this->resource->getImageProfiles() as $name => $profile) {
+                $newImage->setImageProfile($name, $profile);
+            }
             $newImage->compositeImage($this->resource, $composite, $x, $y);
         }
```
