### ISSUE TITLE
[SECURITY] Provide an authenticator authenticating against existing admin session

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#1465]
Certain sections of a site need to authenticate against admin users. Build a simple authenticator which is able to read an existing admin session and returning a pre authenticated token.

Can be used by just activating the authenticator on the firewall:

```yaml
security:
    firewalls:
        foo:
            pimcore_admin_pre_auth: ~
```
