### ISSUE TITLE
Improve Configuration Storage Locations

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14858]
### Improvement description

1. change the config structure to allow more flexibility in future and be more specific: 

```yaml
pimcore:
    config_location:
        image_thumbnails:
            write_target: 
              type: 'symfony-config'
              options:
                 directory: '/var/www/html/var/config/image-thumbnails'
```

It should be clear that you configure the write target here, additionally it would allow us to add more configs here in future, e.g. to disable certain read-locations ... 

2. we should explain in the docs how the configs are getting loaded and merged. 
3. we should have different examples for `symfony-config` , `settings-store` and `disabled`.
