### ISSUE TITLE
LocationAwareConfigRepository: possibility to define read targets

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14861]
### Improvement description

Currently it's only possible to configure the write target to be used when saving configs in the admin UI, but reading is based on a fallback/merge strategy that brings together the configs from multiple storage backends. But in certain cases it would be good to be also able to limit the reading souces, e.g.

```yaml
pimcore:
    config_location:
        image_thumbnails:
            write_target: 
              type: 'settings-store'
            read_targets: ['settings-store']
```

- [ ]  Adapt getReadTargets()

**Comment by robertSt7** [comment]
Hi @brusch What do you mean by the [certain nodes](https://github.com/pimcore/pimcore/pull/14889#discussion_r1162620236) for `read_targets`?

Should we use the `read_target` also for more targets? Because then we don't need to add a second key, care about the priority of this two keys and we can cast the value to an array of it.

**Comment by brusch** [comment]
Actually I guess my point was that `read_target` accepts at the moment only one backend, but there are config types, such as `image_thumbnails` that would allow (in theory) to configure multiple storages including a custom priority. 

E.g. 
```yaml
pimcore:
    config_location:
        image_thumbnails:
            write_target: 
              type: 'settings-store'
            read_target:
                type: ['settings-store', 'symfony-config']
```

With this config it would be possible to change the loading order from the default (`symfony-config -> settings-store`) to `settings-store` -> `symfony-config`. 

But having multiple storages should be only possible for configs supporting that, e.g. NOT for `system_settings`.
