### ISSUE TITLE
[Bug]:  Avif segfault at 20 ip 00007f47068a5b64 sp 00007ffefd5627a0 error 4 in libaom.so.0[7f4706712000+2da000] 

### ISSUE THREAD

**Issue by mackrais** [pimcore/pimcore#14863]
### Expected behavior

Without kill process 

### Actual behavior

`[Wed Apr 5 13:14:47 2023] php[3887895]: segfault at 20 ip 00007f47068a5b64 sp 00007ffefd5627a0 error 4 in libaom.so.0[7f4706712000+2da000] 
[Wed Apr 5 13:14:47 2023] Code: 7e 18 f7 de 0f af f3 48 63 c6 c1 fe 1f 48 69 c0 1f 85 eb 51 48 c1 f8 25 29 f0 48 83 c4 08 5b 5d c3 0f 1f 44 00 00 55 48 89 fd <48> 8b 7f 20 e8 d3 6f f9 ff 48 8b 7d 28 e8 ca 6f f9 ff 48 89 ef 5d`

### Steps to reproduce

Image which i try generate thumbnail [download](https://fex.net/s/fbl1asv)
Config thumbnail 
```
pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    product_gallery_preview:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 3200
                                    height: 4000
                                    forceResize: false
                        medias: {  }
                        name: product_gallery_preview
                        description: ''
                        group: Product
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1669740473
                        creationDate: 1658930137
                        preserveAnimation: false

```
Command with error

`./bin/console pimcore:thumbnails:image  --id=220097 --thumbnails=product_gallery_preview --verbose`

Command without error

`./bin/console pimcore:thumbnails:image  --id=220097 --thumbnails=product_gallery_preview --verbose --skip-avif`
