### ISSUE TITLE
[Task] Double check if pimcore.bundles.search_paths config is still needed

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#15005]
### Improvement description

check if following config is still needed? 
```yaml
pimcore:
      bundles:
         search_paths:
```
