### ISSUE TITLE
[Bug]: Redis doesnt seem to work with Pimcore 11

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/pimcore#15605]
### Pimcore version

11.0.4

### Steps to reproduce

1 - Run Pimcore Skeleton via Docker (docker compose up)
2 - Change the config to use Redis:

```
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 31536000  # 1 year
                adapter: pimcore.cache.adapter.redis_tag_aware
                provider: 'redis://redis'
```
3 - Execute the following code:

```
        $cacheKey = "abc";
        $lifetime = 99999;
        $data = "def";
         \Pimcore\Cache::save($data,$cacheKey,[],$lifetime);

        echo \Pimcore\Cache::load($cacheKey);
```

### Actual Behavior

When you echo the code above you get nothing.

### Expected Behavior

When you echo the code above you should get "def".

**Comment by jdreesen** [comment]
I think you have to either call `\Pimcore\Cache::setForceImmediateWrite(true)` first or call `save()` with `force: true`, like: `\Pimcore\Cache::save($data, $cacheKey, [], $lifetime, force: true)`. 

Otherwise, it's only in the write queue, and you can `load()` it in the *next* request.

**Comment by ayoob-lfc** [comment]
Hi @jdreesen ,

I tried that, but it doesn't work. However when I don't use Redis it works. For example:

```
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 31536000  # 1 year
                adapter: pimcore.cache.adapter.doctrine_dbal
                provider: 'doctrine.dbal.default_connection'
```

The above works and gets cached. But as soon I switch to redis or use a remote redis service (azure), it doesn't work,

**Comment by ayoob-lfc** [comment]
The value gets saved in Redis, but it seems like its not getting sent back to Pimcore:


![image](https://github.com/pimcore/pimcore/assets/46787382/4995cfc5-5371-43c5-be6b-2aa2d267deb0)

**Comment by ayoob-lfc** [comment]
I got it working. So the issue was that I was using the documentation from here:

https://pimcore.com/docs/platform/Pimcore/Development_Tools_and_Details/Cache/#configuring-the-cache

The problem was caused by `tags: true`. As soon as I removed it, it started to work:

```
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                #tags: true
                default_lifetime: 31536000  # 1 year
                adapter: pimcore.cache.adapter.redis_tag_aware
                provider: 'redis://redis'

```

**Comment by brusch** [comment]
@ayoob-lfc please be aware that `tags: true` is essential for Pimcore to work properly, otherwise you'll experience data inconsistencies.

**Comment by ayoob-lfc** [comment]
Hi @brusch, but for Pimcore 11, when I use redis_tag_aware, the cache gets saved in Redis, but I cant get the data back from the cache when `tag: true`.

**Comment by brusch** [comment]
@ayoob-lfc see: 
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php#L263 

Symfony cache is doing a deferred save when using tags, so your code is not intended to work. 
If you want to use the cache that way, you'd have to configure your own cache pool and use Symfony cache directly - which is totally fine when using Pimcore 😉

**Comment by ayoob-lfc** [comment]
Hey @brusch 
So originally I was using data-hub's GraphQl. The issue was that the response wasn't getting cached at all. Even with the following settings:

```
pimcore_data_hub:
    graphql:
        output_cache_enabled: true
        output_cache_lifetime: 60
```

Its important for the client that the responded is cached via Redis since were setting up Pimcore via kubernetes. 

Please can you show me how would I go about configuring Redis to work that way (some code snippets please)? 
Thank you.

FYI, I ran some performance test on a graphql endpoint, and redis wasn't getting hit.

I added logs here:

https://github.com/pimcore/data-hub/blob/74b345701d83a6377004cd9c88b2655ce1a94cdf/src/Service/OutputCacheService.php#L106

And the data coming back was empty 😞

**Comment by brusch** [comment]
The output cache only works for identical requests after the initial request, NOT within the same process. 
If that's not working, please create an issue here https://github.com/pimcore/data-hub/issues with a reproducible case. Thanks!

**Comment by ayoob-lfc** [comment]
@brusch thanks man. Appreciate it

**Comment by ayoob-lfc** [comment]
Issue created here:
https://github.com/pimcore/data-hub/issues/775

**Comment by ayoob-lfc** [comment]
@brusch 

I did a sanity check to confirm it for datahub and to see if its not an issue with my setup, but I think it might be an issue with Pimcore. 
I create a new Pimcore 11 skeleton docker image. 
Set redis as:

```
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 31536000
                adapter: pimcore.cache.adapter.redis_tag_aware
                provider: 'redis://redis'
```

Ran the following, and expected nothing since save is deferred:

```
        $cacheKey = "abc";
        $lifetime = 99999;
        $data = "def";
         \Pimcore\Cache::save($data,$cacheKey,[],$lifetime);

        echo \Pimcore\Cache::load($cacheKey);
```

However after a while when I ran the following, I got nothing back:

```
        $cacheKey = "abc";
        echo \Pimcore\Cache::load($cacheKey);
```

I repeated it, but still nothing.

I tried it with doctrine_dbal and it works as expected:

```
...
                public: true
                tags: true
                default_lifetime: 31536000
                adapter: pimcore.cache.adapter.doctrine_dbal
                provider: 'doctrine.dbal.default_connection'
...
```

For doctrine_dbal the initial cache is empty (as expected since its deferred), and the subsequent cache come through, meaning it works for doctrine_dbal but not for redis_tag_aware 😕 .

**Comment by brusch** [comment]
@ayoob-lfc thanks you very much for coming back on this, and you're completely right - there's an issue.
I've already created a fix for it, see: #15625 
Actually it's about the docs, so using the following config should work for you: 

```yaml
# config/packages/cache.yaml
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                default_lifetime: 31536000  # 1 year
                adapter: cache.adapter.redis_tag_aware
                provider: 'redis://redis'
```

Thanks again!
