### ISSUE TITLE
[PIMCORE 5] Segfault when using undefined constants from classes inheriting from Pimcore\Helper\LegacyClass

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#1607]
`Pimcore\Helper\LegacyClass` generates a segmentation fault when a (obviously not existing) constant is used from a class inheriting `LegacyClass`.

In the `dev` environment this happens upon dumping the debug container in `ContainerBuilderDebugDumpPass`, however this probably also happens in `prod` as soon as the class/service is loaded.

Tested on PHP 7 and 7.1 on different machines (no opcache or module issue).

---

Example view helper:

```yaml
services:
    example_helper:
        class: AppBundle\Templating\Helper\Example
        tags:
            - { name: templating.helper, alias: example }
```

```php
<?php

namespace AppBundle\Templating\Helper;

use Symfony\Component\Templating\Helper\Helper;

class Example extends Helper
{
    public function test($format = \Zend_Date::LONG) // <-- this default param causes the segfault
    {
    }
}
```

```
$ PIMCORE_ENVIRONMENT=dev bin/console
Segmentation fault (core dumped)
```
