### ISSUE TITLE
[Bug]: Redis doesnt seem to work with Pimcore 11

### ISSUE THREAD

**Issue by bitfactory-falko-neven** [pimcore/pimcore#16352]
### Pimcore version

11.1.1

### Steps to reproduce

Setup redis cache `config/packages/cache.yaml`

```
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                default_lifetime: 31536000  # 1 year
                adapter: cache.adapter.redis_tag_aware
                provider: 'redis://:%env(REDIS_PASS)%@%env(REDIS_HOST)%:%env(REDIS_PORT)%/1'
```

Save and load data from cache
```
\Pimcore\Cache::save(
    'Pimcore Cache - Test',
    'randomkey',
    [],
    600
);

// Load data from cache
$testdata = \Pimcore\Cache::load('randomkey');
```
which always returns false where I expect "Pimcore Cache - Test"

### RedisAdapter
Using the RedisAdapter it works

```
$dsn = sprintf(
    'redis://:%s@%s:%s/1',
    $_ENV['REDIS_PASS'],
    $_ENV['REDIS_HOST'],
    $_ENV['REDIS_PORT']
);

$client = RedisAdapter::createConnection(
    $dsn
);

$client->set('randomkey', 'RedisAdapter - Test', 600);

dump("RedisAdapter: ".$client->get('randomkey'));
```
Here I do receive the string "RedisAdapter - Test'"

### Actual Behavior

Above mentioned code and way of saving data to Redis always returns false instead of the data. Both saving and loading seem to not work.

I saw https://github.com/pimcore/pimcore/issues/15605#issuecomment-1651347525 and believe I adapted my cache.yaml accordingly but unfortunately doesnt work for me

### Expected Behavior

Expected behaviour is that the key 'randomkey' is being saved to Redis with 'Pimcore Cache - Test' as data and that other pimcore core caches are also going to be saved correctly. In my log there are several `[2023-12-08T09:16:10.071839+00:00] cache.DEBUG: Key object_733 doesn't exist in cache {"key":"object_733"} []` records present.

Hope I made my ticket clear enough, if not please let me know and I will try to clarify

**Comment by bitfactory-falko-neven** [comment]
After some more investigation it appears this scenario does work in another Pimcore project we are running however its unclear to me why. The are both updated to the latest 11.1.13. with the config/packages/cache.yaml being:

```
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 31536000  # 1 year
                adapter: pimcore.cache.adapter.redis_tag_aware
                provider: 'redis://:%env(REDIS_PASS)%@%env(REDIS_HOST)%:%env(REDIS_PORT)%/1'
```
for both projects. Im currently testing with the following code:

```
$test = \Pimcore\Cache::save('thisisastring', 'cachekey');
$result = \Pimcore\Cache::load('cachekey');
```

Anyone has ideas what could cause it to work for 1 Pimcore project and not another?

**Comment by bitfactory-falko-neven** [comment]
After more research it appears that there are 2 more scenarios:

1: running the following in a controller:
```
        \Pimcore\Cache::setForceImmediateWrite(true);

        $test = \Pimcore\Cache::save('abcdefg', 'cachekey');
        $result = \Pimcore\Cache::load('cachekey');
        dd($result);
```

Does give save and retrieve the values from Redis even though im unclear yet why \Pimcore\Cache::setForceImmediateWrite(true); has to be added here

2: When attempting to write cache using a tag it doesnt work however
```
\Pimcore\Cache::setForceImmediateWrite(true);

            \Pimcore\Cache::save(
                $result,
                $cacheKey,
                ["globaldata"],
                600
            );

            $test = \Pimcore\Cache::load($cacheKey);
            dd($test);
```
When emptying the tag part to just [] it works

**Comment by bitfactory-falko-neven** [comment]
I believe the problem is in regard to using tags.

```
$test = \Pimcore\Cache::save(
            'thisisastring',
            'cachekey',
            ["globaldata"],
            // [],
            600,
            1,
            true
        );
        //$test = \Pimcore\Cache::save('thisisastring', 'cachekey');
        $result = \Pimcore\Cache::load('cachekey');
```

So the one using tag "globaldata" appears to fail

**Comment by jdreesen** [comment]
Right, see: #15625 and #16197

@dvesh3 maybe it's time to merge the latter one.

**Comment by bitfactory-falko-neven** [comment]
It seems that certain objects ( in my example object_912 ) is present in the `$this->saveQueue` array but is never stored in Redis. This results in a issue where the same 50 items are always present within that array and are never stored so new cache items are never written to Redis.

@jdreesen do you happen to know anything about this?

**Comment by jdreesen** [comment]
No, but did you try to remove the `tags: true` setting? According to the mentioned PRs, it should be removed.

**Comment by bitfactory-falko-neven** [comment]
Yes, i've updated it accordingly.

```
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                default_lifetime: 31536000  # 1 year
                adapter: cache.adapter.redis_tag_aware
                provider: 'redis://:%env(REDIS_PASS)%@%env(REDIS_HOST)%:%env(REDIS_PORT)%/1'
```
