### ISSUE TITLE
[Bug]: Login Screen Image not loaded when asset is not on local file system

### ISSUE THREAD

**Issue by dfranek-pix** [pimcore/pimcore#16369]
### Pimcore version

11

### Steps to reproduce

Add AWS S3 as asset storage:

```
services:
    assets_s3:
        class: 'Aws\S3\S3Client'
        arguments:
            - endpoint: 'https://s3.eu-central-1.amazonaws.com'
              region: 'eu-central-1'
              version: 'latest'
              credentials:
                  key: '%env(S3_STORAGE_KEY)%'
                  secret: '%env(S3_STORAGE_SECRET)%'
flysystem:
    storages:
        pimcore.asset.storage:
            adapter: 'aws'
            visibility: private
            options:
                client: 'assets_s3'
                bucket: '%s3_bucket%'
                prefix: 'media/%env(S3_PREFIX)%/assets'
```
Add cloudfront to frontend prefixes:
```
pimcore:
    assets:
        frontend_prefixes:
            # Prefix used for the original asset files
            source: '%env(CLOUDFRONT_HOST)%/media/%env(S3_PREFIX)%/assets'
            # Prefix used for all generated image & video thumbnails
            thumbnail: '%env(CLOUDFRONT_HOST)%/media/%env(S3_PREFIX)%/thumbnails'
```

### Actual Behavior

If you store your assets on AWS S3 and reference an asset that is stored there in "Appearance & Branding" for the custom login image, it is not displayed.

### Expected Behavior

The image should be loaded with the cloudfront url, for example: `https://<cloudfrontid>.cloudfront.net/media/master/assets/Systeminhalte/image.jpg
