### ISSUE TITLE
[Bug]: Select options in settings-store does not work

### ISSUE THREAD

**Issue by Navino16** [pimcore/pimcore#16682]
### Pimcore version

11.1.5

### Steps to reproduce

1. In config/config.yaml set the select_options to be stored in settings-store:
``` yaml
pimcore:
    config_location:
        select_options:
            write_target:
                type: 'settings-store'
```
3. On the Pimcore interface try to create a new Select Options

### Actual Behavior

Actually it generate the following error
```
Timestamp: Tue Feb 27 2024 18:01:19 GMT+0100 (heure normale d’Europe centrale)
Status: 404 | 
URL: /admin/class/select-options-get
Message: Not Found
Trace: 
in /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/ClassController.php:2266
#0 /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/ClassController.php(2143): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController->getSelectOptionsConfig('TestSelect1')
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\ClassController->selectOptionsGetAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#6 /var/www/html/public/index.php(19): require_once('/var/www/html/v...')
#7 {main}
```

### Expected Behavior

Being able to use settings-store for Select Options

**Comment by christopher-siegel** [comment]
Try adding both write and read configs:

```yaml
config_location:
    select_options:
        write_target:
            type: 'settings-store'
        read_target: 
            type: 'settings-store'
```
