### ISSUE TITLE
[Bug]: Asset migration storage is done using Flysystem, but the moved images are not reflecting in the UI Assets section

### ISSUE THREAD

**Issue by talsan74** [pimcore/pimcore#16786]
### Pimcore version

v11.2.0

### Steps to reproduce

I have deployed Pimcore using the Pimcore Docker image and installed 'league/flysystem-aws-s3-v3': '^3.0' for persistent storage with Amazon S3. Uploading assets via the Pimcore UI, which are then saved to S3 bucket 'B', is working fine. I am attempting to copy assets from S3 bucket 'A' to bucket 'B' using the Flysystem command pimcore:migrate:storage. The command's output indicates that all assets were successfully copied from bucket 'A' to bucket 'B'.  Even we can list the bucket 'A' assets in bucket 'B' using aws commands. However, the updated assets are not appearing in the UI.

this is the flysystem config i am using
```
#config/packages/prod/flysystem.yaml
services:
   assets_s3:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: 'https://s3.ap-south-1.amazonaws.com'
               region: 'ap-south-1'
               version: 'latest'
               credentials:
                   key: 'access_key'
                   secret: 'secret-key'
flysystem:
   storages:
       pimcore.asset.storage.source:
           # Storage for asset source files, directory structure is equal to the asset tree structure
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'bucket-A'
               prefix: assets
       pimcore.asset.storage.target:
           # Storage for asset source files, directory structure is equal to the asset tree structure
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'bucket-B'
               prefix: pimcore/assets

       pimcore.asset.storage:
           # Storage for asset source files, directory structure is equal to the asset tree structure
           adapter: 'aws'
           visibility: public
           options:
               client: 'assets_s3'
               bucket: 'bucket-B'
               prefix: pimcore/assets
```

### Actual Behavior

But only the uploaded images from the Pimcore UI are shown in the UI. Copied assets using `bin/console pimcore:migrate:storage asset` are not getting reflected in the UI

![image](https://github.com/pimcore/pimcore/assets/122008280/9412bc24-d0bb-4efc-a087-4145dd091137)
![image](https://github.com/pimcore/pimcore/assets/122008280/7b5f8ecf-401c-4da5-90cc-bdba6aaab3c2)

### Expected Behavior

The 'test.png' image also needs to be viewed from the Pimcore UI. Like

![image](https://github.com/pimcore/pimcore/assets/122008280/348eb33b-34ea-4d07-b85c-f287d1f9030e)
