### ISSUE TITLE
[Bug]: WYSIWYG editor content not handled properly within block elements

### ISSUE THREAD

**Issue by hitsoul11** [pimcore/pimcore#16814]
### Pimcore version

11.2.1

### Steps to reproduce

1. Add frontend_prefix for assets in config:

```
pimcore:
   assets:
       frontend_prefixes:
           source: /resources
```

2. Build a random class definition with block which contains a wysiwyg editor data type
3. Choose a random file from assets and link it in the editor
4. Check field output via PHP API (in test controller)

### Actual Behavior

Link URL in Frontend is not prefixed with `/resources/`.

### Expected Behavior

Link URL should be prefixed with `/resources/`
