### ISSUE TITLE
[Bug, EC]: Impossible to install pimcore with variables inside config.yaml

### ISSUE THREAD

**Issue by Navino16** [pimcore/pimcore#16891]
### Pimcore version

11.2.2

### Steps to reproduce

- Init a new project: ``docker run -u `id -u`:`id -g` --rm -v `pwd`:/var/www/html pimcore/pimcore:php8.2-latest composer create-project pimcore/skeleton my-project``
- Add in config.yaml:
  ````yaml
  framework:
      cache:
          pools:
              pimcore.cache.pool:
                  public: true
                  default_lifetime: 31536000
                  adapter: cache.adapter.redis_tag_aware
                  provider: '%env(string:REDIS_HOST)%'
              cache.adapter.system:
                  default_lifetime: 31536000  # 1 year
                  adapter: cache.adapter.redis_tag_aware
                  provider: '%env(string:REDIS_HOST_SYSTEM)%'
  ````
- Add in .env:
  ````
  REDIS_HOST=redis://redis/1
  REDIS_HOST_SYSTEM=redis://redis/2
  ````
- Run `sed -i "s|#user: '1000:1000'|user: '$(id -u):$(id -g)'|g" docker-compose.yaml` to set the correct user id and group id.
- Start the needed services with `docker compose up -d`
-  `docker compose exec php vendor/bin/pimcore-install`
- Enter admin/password and answer no to extra bundles
- See error

### Actual Behavior

Since Pimcore 11.2.2 we can't install a project with variables inside config.yaml.

We get the following error:
![image](https://github.com/pimcore/pimcore/assets/22234867/0c141985-9373-46f7-9f8e-4017cf924845)

It's seem that env values are not loaded anymore.

### Expected Behavior

Before 11.2.X we where able to install a new project with variables inside config.yaml.
