### ISSUE TITLE
[Bug]: [Objects] External video preview image (YouTube) blocked due to CSP

### ISSUE THREAD

**Issue by podarcis** [pimcore/pimcore#16919]
### Pimcore version

11.2.2

### Steps to reproduce

1. Have data field of type `video`.
2. Choose external video (e.g. YouTube) and paste its YT-code.
3. Preview image is blocked by the browser due to CSP.

`Refused to frame 'https://www.youtube-nocookie.com/' because it violates the following Content Security Policy directive: "frame-src 'self' data:".`

### Actual Behavior

Preview image is blocked due to CSP and thus not shown.

### Expected Behavior

As configuring YouTube in video field is a core functionality it should not require project specific configuring such as:
```yaml
pimcore_admin:
    admin_csp_header:
        additional_urls:
            frame-src:
                - 'https://www.youtube-nocookie.com/'
```

Instead these external video services should be allowed by default in `ContentSecurityPolicyHandler`.
