### ISSUE TITLE
[Feature]: Add way to get tracebacks from the `pimcore` logging channel

### ISSUE THREAD

**Issue by mattviasat** [pimcore/pimcore#17645]
### Feature description

I would like to be able to get stacktraces from errors that originate within `pimcore`, `pimcore_api` or `session` channels using the `include_stacktraces: true` option.

### More information

I am on [2024.1](https://github.com/pimcore/platform-version/tree/v2024.1) aka Pimcore 11.2.7

I am using the monolog logger inside my application according to the [docs provided by pimcore](https://pimcore.com/docs/platform/Pimcore/Development_Tools_and_Details/Logging/#writing-your-own-log-files)  and the [symfony docs](https://symfony.com/doc/6.2/logging/channels_handlers.html#configure-additional-channels-without-tagged-services). I create my own logger
```php
class SomeService {
    public function __construct(\Psr\Log\LoggerInterface $myloggerLogLogger)
    {
        $myloggerLogLogger->error('Test Message');
    }
}
```

I can get stacktraces from `mylogger` using `include_stacktraces: true`.
The problem is that errors on the `pimcore` channel do not include stacktraces. So I will get an error log from the `pimcore` like `Version: cannot read version data with storage type: fs`... and that is it. I don't know where it comes from because I cannot get a trace. 

here is the `config/packages/prod/config.yaml`
```yaml
imports:
    - { resource: ../../config.yaml }

# Logging is configured differently depending on the environment.
# See https://symfony.com/doc/current/configuration.html#selecting-the-active-environment
monolog:
    # Pimcore creates 3 default channels.
    # https://pimcore.com/docs/platform/Pimcore/Development_Tools_and_Details/Logging#envlog
    # We create the mylogger channel.
    # https://symfony.com/doc/6.2/logging/channels_handlers.html#configure-additional-channels-without-tagged-services
    # https://kurozumi.github.io/symfony-docs/logging.html#handlers-that-modify-log-entries
    channels: ['mylogger']
    handlers:
        # Log JSON in prod to stdout only.
        main:
            type: stream
            path: "php://stdout"
            level: info
            channels: [ '!event', '!doctrine', '!cache' ]
            formatter: monolog.json_formatter
            # Include stack as a json field if errors.
            # https://github.com/Seldaek/monolog/blob/bc3e507096f1defbb703d2dcf92aa872bab71321/src/Monolog/Formatter/JsonFormatter.php#L49
            include_stacktraces: true
```

and the output of `php bin/console debug:config MonologBundle --env=prod --resolve-env`
```yaml

# Current configuration for "MonologBundle"
# =========================================

monolog:
    handlers:
        usage:
            type: stream
            path: /var/www/html/var/log/usage.log
            level: debug
            channels:
                type: inclusive
                elements:
                    - admin_statistics
            priority: 0
            bubble: true
            app_name: null
            fill_extra_context: false
            include_stacktraces: false
            process_psr_3_messages:
                enabled: null
            file_permission: null
            use_locking: false
            filename_format: '{filename}-{date}'
            date_format: Y-m-d
            ident: false
            logopts: 1
            facility: user
            max_files: 0
            action_level: WARNING
            activation_strategy: null
            stop_buffering: true
            passthru_level: null
            excluded_404s: {  }
            excluded_http_codes: {  }
            accepted_levels: {  }
            min_level: DEBUG
            max_level: EMERGENCY
            buffer_size: 0
            flush_on_overflow: false
            exchange_name: log
            message_format: text
            api_version: null
            channel: null
            bot_name: Monolog
            use_attachment: true
            use_short_attachment: false
            include_extra: false
            icon_emoji: null
            notify: false
            nickname: Monolog
            use_ssl: true
            title: null
            host: null
            port: 514
            config: {  }
            members: {  }
            time: 60
            deduplication_level: 400
            store: null
            hub_id: null
            client_id: null
            auto_log_stacks: false
            release: null
            environment: null
            message_type: 0
            parse_mode: null
            disable_webpage_preview: null
            disable_notification: null
            split_long_messages: false
            delay_between_messages: false
            factor: 1
            tags: {  }
            console_formatter_options: {  }
            nested: false
            index: monolog
            document_type: logs
            ignore_error: false
            to_email: {  }
            content_type: null
            headers: {  }
            mailer: null
            lazy: true
        redirect:
            type: stream
            path: /var/www/html/var/log/redirect.log
            level: debug
            channels:
                type: inclusive
                elements:
                    - redirect
            priority: 0
            bubble: true
            app_name: null
            fill_extra_context: false
            include_stacktraces: false
            process_psr_3_messages:
                enabled: null
            file_permission: null
            use_locking: false
            filename_format: '{filename}-{date}'
            date_format: Y-m-d
            ident: false
            logopts: 1
            facility: user
            max_files: 0
            action_level: WARNING
            activation_strategy: null
            stop_buffering: true
            passthru_level: null
            excluded_404s: {  }
            excluded_http_codes: {  }
            accepted_levels: {  }
            min_level: DEBUG
            max_level: EMERGENCY
            buffer_size: 0
            flush_on_overflow: false
            exchange_name: log
            message_format: text
            api_version: null
            channel: null
            bot_name: Monolog
            use_attachment: true
            use_short_attachment: false
            include_extra: false
            icon_emoji: null
            notify: false
            nickname: Monolog
            use_ssl: true
            title: null
            host: null
            port: 514
            config: {  }
            members: {  }
            time: 60
            deduplication_level: 400
            store: null
            hub_id: null
            client_id: null
            auto_log_stacks: false
            release: null
            environment: null
            message_type: 0
            parse_mode: null
            disable_webpage_preview: null
            disable_notification: null
            split_long_messages: false
            delay_between_messages: false
            factor: 1
            tags: {  }
            console_formatter_options: {  }
            nested: false
            index: monolog
            document_type: logs
            ignore_error: false
            to_email: {  }
            content_type: null
            headers: {  }
            mailer: null
            lazy: true
        main:
            type: stream
            path: 'php://stdout'
            level: info
            channels:
                type: exclusive
                elements:
                    - event
                    - doctrine
                    - cache
            formatter: monolog.json_formatter
            include_stacktraces: true
            priority: 0
            bubble: true
            app_name: null
            fill_extra_context: false
            process_psr_3_messages:
                enabled: null
            file_permission: null
            use_locking: false
            filename_format: '{filename}-{date}'
            date_format: Y-m-d
            ident: false
            logopts: 1
            facility: user
            max_files: 0
            action_level: WARNING
            activation_strategy: null
            stop_buffering: true
            passthru_level: null
            excluded_404s: {  }
            excluded_http_codes: {  }
            accepted_levels: {  }
            min_level: DEBUG
            max_level: EMERGENCY
            buffer_size: 0
            flush_on_overflow: false
            exchange_name: log
            message_format: text
            api_version: null
            channel: null
            bot_name: Monolog
            use_attachment: true
            use_short_attachment: false
            include_extra: false
            icon_emoji: null
            notify: false
            nickname: Monolog
            use_ssl: true
            title: null
            host: null
            port: 514
            config: {  }
            members: {  }
            time: 60
            deduplication_level: 400
            store: null
            hub_id: null
            client_id: null
            auto_log_stacks: false
            release: null
            environment: null
            message_type: 0
            parse_mode: null
            disable_webpage_preview: null
            disable_notification: null
            split_long_messages: false
            delay_between_messages: false
            factor: 1
            tags: {  }
            console_formatter_options: {  }
            nested: false
            index: monolog
            document_type: logs
            ignore_error: false
            to_email: {  }
            content_type: null
            headers: {  }
            mailer: null
            lazy: true
        error:
            type: stream
            path: /var/www/html/var/log/php.log
            level: error
            priority: 0
            bubble: true
            app_name: null
            fill_extra_context: false
            include_stacktraces: false
            process_psr_3_messages:
                enabled: null
            file_permission: null
            use_locking: false
            filename_format: '{filename}-{date}'
            date_format: Y-m-d
            ident: false
            logopts: 1
            facility: user
            max_files: 0
            action_level: WARNING
            activation_strategy: null
            stop_buffering: true
            passthru_level: null
            excluded_404s: {  }
            excluded_http_codes: {  }
            accepted_levels: {  }
            min_level: DEBUG
            max_level: EMERGENCY
            buffer_size: 0
            flush_on_overflow: false
            exchange_name: log
            message_format: text
            api_version: null
            channel: null
            bot_name: Monolog
            use_attachment: true
            use_short_attachment: false
            include_extra: false
            icon_emoji: null
            notify: false
            nickname: Monolog
            use_ssl: true
            title: null
            host: null
            port: 514
            config: {  }
            members: {  }
            time: 60
            deduplication_level: 400
            store: null
            hub_id: null
            client_id: null
            auto_log_stacks: false
            release: null
            environment: null
            message_type: 0
            parse_mode: null
            disable_webpage_preview: null
            disable_notification: null
            split_long_messages: false
            delay_between_messages: false
            factor: 1
            tags: {  }
            console_formatter_options: {  }
            nested: false
            index: monolog
            document_type: logs
            ignore_error: false
            to_email: {  }
            content_type: null
            headers: {  }
            mailer: null
            lazy: true
        console:
            type: console
            process_psr_3_messages:
                enabled: false
            priority: 0
            level: DEBUG
            bubble: true
            app_name: null
            fill_extra_context: false
            include_stacktraces: false
            path: /var/www/html/var/log/prod.log
            file_permission: null
            use_locking: false
            filename_format: '{filename}-{date}'
            date_format: Y-m-d
            ident: false
            logopts: 1
            facility: user
            max_files: 0
            action_level: WARNING
            activation_strategy: null
            stop_buffering: true
            passthru_level: null
            excluded_404s: {  }
            excluded_http_codes: {  }
            accepted_levels: {  }
            min_level: DEBUG
            max_level: EMERGENCY
            buffer_size: 0
            flush_on_overflow: false
            exchange_name: log
            message_format: text
            api_version: null
            channel: null
            bot_name: Monolog
            use_attachment: true
            use_short_attachment: false
            include_extra: false
            icon_emoji: null
            notify: false
            nickname: Monolog
            use_ssl: true
            title: null
            host: null
            port: 514
            config: {  }
            members: {  }
            time: 60
            deduplication_level: 400
            store: null
            hub_id: null
            client_id: null
            auto_log_stacks: false
            release: null
            environment: null
            message_type: 0
            parse_mode: null
            disable_webpage_preview: null
            disable_notification: null
            split_long_messages: false
            delay_between_messages: false
            factor: 1
            tags: {  }
            console_formatter_options: {  }
            nested: false
            index: monolog
            document_type: logs
            ignore_error: false
            to_email: {  }
            content_type: null
            headers: {  }
            mailer: null
            lazy: true
    channels:
        - pimcore
        - pimcore_api
        - session
        - mylogger
    use_microseconds: true
```
