### ISSUE TITLE
[Bug]: asset fronend_prefixes appear in backend editables

### ISSUE THREAD

**Issue by tobiashelmervalantic** [pimcore/pimcore#17694]
### Pimcore version

Core Version: v11.3.1

### Steps to reproduce

Add a prefix in a config.yaml file like this:

```
assets:
    frontend_prefixes:
        # Prefix used for the original asset files
        source: https://test-link.com
        # Prefix used for all generated image & video thumbnails
        thumbnail: https://test-link.com
```

### Actual Behavior

After adding the prefix all asset links in editables are not prefixed as well and will disapear in frontend after saving as Pimcore can't find the assets anymore.

**After inserting the assets:**

![image](https://github.com/user-attachments/assets/d8fcbd63-87d7-4c42-8dd9-e4d33c55599d)

**After clicking on the edit button:**

![image](https://github.com/user-attachments/assets/9867f2d0-d495-41aa-856f-b41ebe0742ab)

As you can see the frontend_prefixes from the config are added to the editable and if you save then the content is lost.

### Expected Behavior

Only the links in frontend should be prefixed and not in backend editables.

![image](https://github.com/user-attachments/assets/b1b45232-b58a-46d8-bc21-d25ca9be7039)
