### ISSUE TITLE
[Bug]: Assets: rename and move not working when using Cloudflare R2 (S3 compatible storage)

### ISSUE THREAD

**Issue by kovinet** [pimcore/pimcore#18492]
### Pimcore version

v2024.3

### Steps to reproduce

I tried to setup Assets using external storage - Cloudflare R2, which should be compatible with AWS S3 adapter, but there are several issues:

1. when renaming folder in assets all images inside the folder get broken
2. drag and drop of asset to new folder results in broken image
3. upload is super slow and laggy

All these issues make remote file storage useless for Assets. 

Is there something that can be done to avoid these isssues?

Following is my flysystem configuration

```yaml
services:
    assets_r2:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: 'https://c5d60f58fd00695a37765a78708ba139.r2.cloudflarestorage.com'
               region: 'auto'
               version: 'latest'
               credentials:
                   key: '%env(S3_STORAGE_KEY)%'
                   secret: '%env(S3_STORAGE_SECRET)%'


pimcore:
    assets:
        frontend_prefixes:
            # Prefix used for the original asset files
            source: https://pub-f0c4c630b36545b69ec6703fe346620f.r2.dev/assets
            # Prefix used for all generated image & video thumbnails
            thumbnail: https://pub-f0c4c630b36545b69ec6703fe346620f.r2.dev/thumbnail
            # Prefix used for the deferred thumbnail placeholder path.
            # Thumbnails are usually generated on demand (if not configured differently), this
            # prefix is used for thumbnails which were not yet generated and therefore are not
            # available on the thumbnail storage yet. Usually it's not necessary to change this config.
            # However, a possible use case would be to point to a specific host that handles generating
            # the thumbnails and takes the load from the main application server(s)
            # thumbnail_deferred: https://thumbnail-generator-node.example.com

flysystem:
    storages:
        pimcore.asset.storage:
            # Storage for asset source files, directory structure is equal to the asset tree structure
            adapter: 'aws'
            visibility: public
            #directory_visibility: public
            options:
                client: 'assets_r2'
                bucket: 'bucket_name'
                prefix: 'assets'
        pimcore.asset_cache.storage:
            # Storage for cached asset files, e.g. PDF and image files generated out of Office files or videos
            # which are then used by the thumbnail engine as source files
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/public/var/tmp/asset-cache'
        pimcore.thumbnail.storage:
            # Storage for image and video thumbnails, directory structure is equal to the source asset tree
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_r2'
                bucket: 'bucket_name'
                prefix: 'thumbnail'
        pimcore.version.storage:
            # Storage for serialized versioning data of documents/asset/data objects
            adapter: 'aws'
            visibility: private
            options:
                client: 'assets_r2'
                bucket: 'bucket_name'
                prefix: 'versions'
```

### Actual Behavior

Assets get broken when moved or renamed when using remote storage with AWS S3 adapter.

### Expected Behavior

Asset rename and move should work with S3 adapter.
