### ISSUE TITLE
[Improvement]: improve instructions for setting up private asset storages

### ISSUE THREAD

**Issue by FabioKlmnt** [pimcore/pimcore#18507]
### Improvement description

Assets that have no thumbnails can't be served when using private storages. I have crafted a short section that can be added to https://github.com/pimcore/pimcore/blob/5e069f55b26607a32cd0237da8f76cc7eb1dae6e/doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Storage_Setup.md?plain=1#L85

Handling source assets when your storage is not publicly accessible:
 ```yaml
pimcore:
    assets:
        frontend_prefixes:
            # Prefix used for the original asset files
            source: https://your.domain/asset-stream
```    
```php
<?php

declare(strict_types=1);

namespace App\Controller;

use Pimcore\Model\Asset;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Attribute\Route;

class AssetStreamController
{
    #[Route('/asset-stream{uri}', requirements: ['uri' => '.+'])]
    public function stream(string $uri): Response
    {
        if (!empty($asset = Asset::getByPath($uri)) && $stream = $asset->getStream()) {
            return new StreamedResponse(function () use ($stream) {
                fpassthru($stream);
            }, 200, [
                'Content-Type' => $asset->getMimeType(),
                'Access-Control-Allow-Origin', '*',
            ]);
        }

        return new Response('', Response::HTTP_NOT_FOUND);
    }
}

```
