### ISSUE TITLE
Always "Checkout not finished yet", when committing order and handling order payment 

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#2114]
In my config I added one "confirm" checkout step ( one-page-checkout ): 
```
 tenants:
        _defaults:
          # Define used commit order processor
          commit_order_processor:
              id: AppBundle\Ecommerce\Order\Processor
          # Because we have a one-page checkout there is only on checkout
          # step to commit
          steps:
            confirm:
              class: \AppBundle\Ecommerce\Checkout\Confirm
``` 
Then in my CheckoutController I am committing the complete form data to the checkout step: 
```
           $data = $form->getData(); // this comes from a symfony form 

            // set the current checkout tenant to the environment
            $environment = Factory::getInstance()->getEnvironment();
            $environment->setCurrentCheckoutTenant('default'); // TODO: Remove hardcoded tenant id

            // commit this step right away
            $checkoutManager = Factory::getInstance()->getCheckoutManager($cart);
            $confirmStep = $checkoutManager->getCheckoutStep('confirm');
            $checkoutManager->commitStep($confirmStep, $data);
            $cart->save();
```

Now in my PaymentController i got the confirmationAction. This a endpoint for the payment service to send me data about the payment. 

```
  $cart = $this->getCart();
        $checkoutManager = Factory::getInstance()->getCheckoutManager($cart);


        // merge body and query params
        $params = $request->query->all();
        ApplicationLogger::getInstance()->info("mPayData: " . json_encode($params));

        try{
            $order = $checkoutManager->handlePaymentResponseAndCommitOrderPayment($params);

            if( $order && $order->getOrderState() == $order::ORDER_STATE_COMMITTED){
                ApplicationLogger::getInstance()->info("Order is committed. Payment is okay");
                return Response::create('OK');
            }
            else{
                // order is not commited so there has been an error in the process
                ApplicationLogger::getInstance()->info("Payment error.");
                return Response::create('ERROR');
            }

        }
        catch (\Exception $e){

            ApplicationLogger::getInstance()
                ->error("mPAY24 Confirmation Error: {$e->getMessage()}");

            return Response::create('ERROR');
        }
```

Now the problem is that everytime the checkout manager throws an exception that the checkout is not finished yet, but I have committed all steps ( it is just one step ). 
I tried to debug and everything, but I am having no idea what the mistake is..

**Comment by fashxp** [comment]
hi,
could you try to debug these lines here? 
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php#L497

I have somehow the feeling, that this doesn't work properly with one step only ... :-(

**Comment by davidhoeck** [comment]
@fashxp What about overriding this method with a custom method, that just sets `finished` to `true` ? Not the best practice but it would do the job when just using one step .. ?

**Comment by fashxp** [comment]
you could do that, but I don't wanna know about it ;-) 

no seriously, I would love to see it working with only one step also...

**Comment by davidhoeck** [comment]
@fashxp the MasterPassProcessor in the ecommerce demo also just uses one confirm step ? 
```
            masterpass:
                steps:
                    confirm:
                        class: \AppBundle\Ecommerce\Checkout\Confirm

                payment:
                    provider: qpay

                commit_order_processor:
                    id: AppBundle\Ecommerce\Order\MasterpassProcessor
                    options:
                        confirmation_mail: /en/emails/order-confirmation
```
How is that working ... :-D
