### ISSUE TITLE
[Assets] Config option to set low quality image preview generator

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2721]
```yml
pimcore: 
    assets:
        image:
            low_quality_image_preview:
                enabled: false
                generator: imagick
```
