### ISSUE TITLE
[Cache] Allow Redis to be configured with env variables

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3227]
`pimcore.cache.pools.redis.connection.database` is defined as `IntegerNode` which results in an exception when defining the value through an env var. 

```yml
pimcore:
    cache:
        pools:
            redis:
                enabled: true
                connection:
                    server: '%env(REDIS_HOST)%'
                    database: '%env(REDIS_DB)%'
```
