### ISSUE TITLE
Allow element notes 'Type' selector to be customised

### ISSUE THREAD

**Issue by cleggypdc** [pimcore/pimcore#331]
Some feedback from a client is it would be nice to be able to configure note types to save them having to type in each time.

I'm thinking perhaps fetch them from ElementController i.e
/admin/element/note-types

but where would be a good place to specify the note types:
- Website Settings?
- System Settings?
- A predefined Note types tab?  

![image](https://cloud.githubusercontent.com/assets/1098498/11658491/d8eeb020-9dba-11e5-8287-4277145c0606.png)

**Comment by brusch** [comment]
Hmm, ... maybe a topic that can be solved by using the newly introduced system flags (stored in system.php): 
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Config.php#L292

![image](https://cloud.githubusercontent.com/assets/142037/13060000/8d315ba6-d42e-11e5-92b7-b0cf20c4e513.png)

**Comment by brusch** [comment]
example:

    "flags" => [ 
        "notesTypePresetValues" => ["one","two","three"], 
        "useZendDate" => false,
        // ...
    ]

**Comment by brusch** [comment]
Proposed solution: 
Introducing new configurations in `config.yml` to customize the types of notes & events based on the source-type (object, asset, document). 

### Example 
```yaml 
pimcore: 
    documents: 
        notes_events: 
            types: 
                - My Custom Type 1
                - Another Custom Type
                - ...
    assets: 
        notes_events: 
            types: 
                - My Custom Type 1
                - Another Custom Type
                - ...
    objects: 
        notes_events: 
            types: 
                - My Custom Type 1
                - Another Custom Type
                - ...
```
