### ISSUE TITLE
[Version] Allow to override `Version` model

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3342]
```yml
pimcore: 
    models:
        class_overrides:
            'Pimcore\Model\Version': 'AppBundle\Model\Version'
```
