### ISSUE TITLE
Unable to create index for object relations

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#3377]
# Bug Report
 

### Expected behavior 
Indexing and filtering should be able to understand multiple relations.

### Actual behavior  
 Indexing cannot do this.

### Steps to reproduce  
Object relations contains a column for `index` (the order things are sorted in the relation). For example this can be used to categorise a Product in one or more Categories.

This relation can be found in the DB table object_relations_*ID* where *ID* is the numeric id of the class. In our case Products have ID 4 and Categories ID 7.

When creating an ecommerce index these multiple relations does not work out as expected:

### Code example 

```yml
pimcore_ecommerce_framework:
  price_systems:
    custom:
      id: custom.price.system

  index_service:
    tenants:
      _defaults:
        config_id: AppBundle\Ecommerce\IndexService\DefaultConfig
        worker_id: AppBundle\Ecommerce\IndexService\MysqlWorker
        attributes:
          listOrder:
            type: varchar(255)
...
```

```php
    public function getListOrder() :string
    {
        $relations = ",";
        $productId = $this->getId();

        $categories = $this->getCategories();
        foreach ($categories as $category) {
            foreach ($category->getRelationData('products', true, $category->getClassId()) as $product) {
                if ($productId == $product['id']) {
                    $relations .= "{$category->getId()}:{$product['index']},";
                }
            }
        }

        return $relations;
    }
```

```php
        $factory = EcommerceFrameworkBundle\Factory::getInstance();
        $list = $factory
            ->getIndexService()
            ->getProductListForCurrentTenant()
            ->addQueryCondition("REGEXP '," . $category->getId() . ":\d+,'", "listOrder"); // This does not work, tried lots of variations
```
