### ISSUE TITLE
[Document] Extending Document\Tag\* classes

### ISSUE THREAD

**Issue by Zamralik** [pimcore/pimcore#3603]
To improve our code quality, we tried to add methods to `Pimcore\Model\Document\Tag\*` classes.
We added in the bundle `Resources/config/pimcore/config.yml` file
```yml
pimcore:
    models:
        class_overrides:
            'Pimcore\Model\Document\Tag\Link': 'AppBundle\Pimcore\Model\Document\Tag\Link'
```
With `AppBundle\Pimcore\Model\Document\Tag\Link` inheriting from `Pimcore\Model\Document\Tag\Link`.
Unfortunately, it was ignored by Pimcore as the document still uses the standard class.
