### ISSUE TITLE
[Asset] Thumbnails: possibility to turn of auto-clearing of temp. files (on save)

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3606]
Currently Pimcore does clear the thumbnails of a certain configuration on save/delete. 
Under certain circumstances (e.g. when having billions of temp. files) this can harm the system health, so there should be an option to turn off this behavior.

**Comment by brusch** [comment]
2 new config options: 

```yml
pimcore: 
    assets:
        image:
            thumbnails:
                auto_clear_temp_files: false
        video:
            thumbnails:
                auto_clear_temp_files: false
```
