### ISSUE TITLE
[Asset] Possibility to define a custom preview thumbnail

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3742]

**Comment by brusch** [comment]
```yml
picmore: 
    assets:
        preview_image_thumbnail: "custom-preview-thumbnail"
```
