### ISSUE TITLE
[Ecommerce] Wrong type in documentation for elasticsearch

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4076]
Hello,

On this page, it seems type is not in good format :
https://pimcore.com/docs/5.x/Development_Documentation/E-Commerce_Framework/Index_Service/Product_Index_Configuration/Elastic_Search.html

I had to change it to `text` or `keyword` to make it work
`string` don't seems to exist (i didn't check for mapping...).
Please see: https://www.elastic.co/guide/en/elasticsearch/reference/6.6/mapping-types.html

Thanks.

PS: concerned part
```
pimcore_ecommerce_framework:
    index_service:
        tenants:
            MyEsTenant:
                attributes:
                    name:
                        locale: '%%locale%%'
                        type: string
                        options:
                            mapping:
                                type: string
                                store: true
                                index: not_analyzed
                                fields:
                                    analyzed:
                                        type: string
                                        analyzer: german
                                    analyzed_ngram:
                                        type: string
                                        analyzer: my_ngram_analyzer
```
