### ISSUE TITLE
[ecommerce] On ES6, filters based on number return errors.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4090]
Hello,

We are trying the ecommerce to switch from mysql to elasticsearch 6.
Indexation work great, filters too, but the two numeric filters send errors.
Using mysql for the same filters there was no errors.

Config of the index for ES6 for this field is:

```
                    number_unit:
                        type: double
                        options:
                            store: true
                        filter_group: double
```

We tried with different type (integer, float, long) same errors are returned.

Using "Filter Numberrange Selection", we get the following error on the frontend during generation of the html for the filter:

![image](https://user-images.githubusercontent.com/9025839/54555168-765a0f80-49b6-11e9-819e-9058cdd5163b.png)

Using "Filter Numberrange", we get this one:

![image](https://user-images.githubusercontent.com/9025839/54555258-a2759080-49b6-11e9-95c8-069266ee0e8c.png)

Thanks.
