### ISSUE TITLE
Element::getByPath() doesn't work properly with class overrides

### ISSUE THREAD

**Issue by SmashingQuasar** [pimcore/pimcore#4103]
Hello,

I noticed the addition of this method in file `vendor\pimcore\pimcore\models\Asset.php`.

```php
<?php
    /**
     * @param Asset $asset
     *
     * @return bool
     */
    protected static function typeMatch(Asset $asset)
    {
        $staticType = get_called_class();
        if ($staticType != Asset::class) {
            if (!$asset instanceof $staticType) {
                return false;
            }
        }
        return true;
    }
```

This new method is used in getById of the same class to check the integrity of the fetched asset.

This breaks the currently allowed [class overrides of Pimcore](https://pimcore.com/docs/5.x/Development_Documentation/Extending_Pimcore/Overriding_Models.html) because it evaluates the called class to the default Pimcore asset class. This means if you call the `getByPath` method through an override class it will return `false` as the called class is not explicitly the default one.

**Comment by brusch** [comment]
Imho the current behavior is correct ... it's the same as for Data Objects and Documents. 
Just did a test: 

```yml
pimcore:
    models:
        class_overrides:
            'Pimcore\Model\Asset\Image': 'AppBundle\Model\Asset\Image'
```

```php
\Pimcore\Model\Asset::getById(78) ==> true
\Pimcore\Model\Asset\Image::getById(78) ==> true
\Pimcore\Model\Asset\Folder::getById(78) ==> false
\AppBundle\Model\Asset\Image::getById(78); ==> true
```

So I don't see any problem ...

**Comment by SmashingQuasar** [comment]
We have a class override as follows:

```yml
    models:
        class_overrides:
            'Pimcore\Model\Asset\Folder': 'Senzo\PimcoreBundle\Model\Asset\Folder'
```

This override does not affect the `getByPath` and `getById` methods.

This is what happens:

```php
$folder = \Pimcore\Model\Asset\Folder::getByPath('/'); // This properly gets the root asset folder
$folder = \Senzo\PimcoreBundle\Model\Asset\Folder::getByPath('/'); // This returns null with the current code
```

I don't know if you had a chance to check my pull request but the addition of `is_sublcass_of()` fixes this issue since it takes inheritance in account.
