### ISSUE TITLE
Overriding Object Datatypes

### ISSUE THREAD

**Issue by bebuecherl** [pimcore/pimcore#4679]
# Bug Report / Discussion

I'm currently working on overriding a Pimcore default Object Datatype (Localizedfields), as a customer of ours needs #2958 and we wanted to have it configurable (which Languages are mandatory and which are not). So I followed the [instructions in the docs](https://pimcore.com/docs/6.x/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Adding_Object_Datatypes.html) to override the Datatype.

### Expected behavior
Using either
```yaml
pimcore:
    objects:
        class_definitions:
            data:
                map:
                    localizedfields: \AppBundle\Model\DataObject\ClassDefinition\Data\Localizedfields
```
or
```yaml
pimcore:
    objects:
        class_definitions:
            data:
                prefixes:
                    - \AppBundle\Model\DataObject\ClassDefinition\Data\
```

results in registering/overriding the Datatype.

### Actual behavior

Still uses the Pimcore Datatype when editing/saving ClassDefinitions in the backend.

As it looks to me, in [PimcoreCoreExtension](https://github.com/pimcore/pimcore/blob/232bd0d9cf806277d5f3c03de37821e54110d227/bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php#L200-L224) the prefixes are added as second loader to the ImplementationLoader. Since ImplementationLoader does *reverse* the array of loaders, it will start by using the PrefixLoader. This loads the prefixes *in order*. This means he will load all classes from `\Pimcore\Model\DataObject\ClassDefinition\Data\` ([config/default.yml](https://github.com/pimcore/pimcore/blob/232bd0d9cf806277d5f3c03de37821e54110d227/bundles/CoreBundle/Resources/config/pimcore/default.yml#L145)) first; no matter what is defined in `pimcore.objects.class_definitions.data.map`.

I think this should be the other way arround, so the direkt mapping (`pimcore.objects.class_definitions.data.map`) is loaded before the glob mapping (`pimcore.objects.class_definitions.data.prefixes`). And maybe additionally reverse the prefixes, so custom configuration will be used before default (Pimcore) configuration

### Steps to reproduce

(see description & expected behavior)

### Current workaround

Inside my `\AppBundle\DependencyInjection\AppExtension` `load`-Method:
```php
$prefixes = [ '\\AppBundle\\Model\\DataObject\\ClassDefinition\\Data\\' ];

$container->setDefinition(
    'pimcore.implementation_loader.object.data.prefix_loader',
    new Definition(PrefixLoader::class, [ $prefixes ])
);

$config = $container->getParameter('pimcore.config');

$config['objects']['class_definitions']['data']['prefixes'] = $prefixes;

$container->setParameter('pimcore.config', $config);
```
this will override the internal PrefixLoader when Containers are merged. (Also ensuring that the container configuration is correct).
