### ISSUE TITLE
[Feature/bug] More flexible Object layout in Workflow

### ISSUE THREAD

**Issue by prugala** [pimcore/pimcore#4747]
# Bug Report
The bug was reported in issue: #3934
When we open object, for example as a user with a custom layout after the workflow transition object opens with the master layout. We can set permission `objectLayout` for workflow places to fix it. Problem is that this option must be defined as an integer value. In a system with few groups with different custom layouts, we can't specific custom layout it in permissions.

# Feature Request
What do you think about allowing to expression same as in `guard` option or allow: int or service with method which returns int?

When we choose the best option I can make it. :)

**Comment by fashxp** [comment]
hmm, shouldn't we fix the issue it self first? If I understand you correctly, when in combination with workflows, user can open objects in master-layout even if they normally don't have access to master layout? That is a proper bug in my point of view.

Besides that, you could define permissions depending on a condition expression - so should be already possible right now. 
But in general, I can imagine that defining a service that returns the custom layout can be useful sometimes.

**Comment by prugala** [comment]
Yes, I have groups with own custom layouts. When I'm changing the workflow state, object tab is reloaded and I see a master layout.
I will investigate it tomorrow. Probably problem is because here: https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Resources/public/js/pimcore/object/object.js#L56 `this.options.layoutId` is undefined or is empty. I saw that an object is loaded after changing workflow state ajax request is with param `?layoutId=`. 


> Besides that, you could define permissions depending on a condition expression - so should be already possible right now.

Ok but `objectLayout` is per place. Few groups with different layouts can have access to an object in the same place, so how can I set different layouts per group? 
Of course, when the above bug will be fixed it isn't important but still can be a good feature.

**Comment by fashxp** [comment]
object layout is per place and condition: 
so you could to things like that....
```
                    permissions:
                        - condition: "is_fully_authenticated() and 'ROLE_PIMCORE_ADMIN' in roles"
                          modify: true
                          objectLayout: 2

                        - objectLayout: 1
                          modify: false
```
