### ISSUE TITLE
Pimcore page cache cannot be disabled by config if data cache is enabled

### ISSUE THREAD

**Issue by pmuskovac** [pimcore/pimcore#5369]
Tested on Pimcore 6.3.3

### Expected behavior
Both caches can be enabled/disabled individually as was possible in Pimcore 5

### Actual behavior
The data cache config overwrites the page cache config

### Steps to reproduce
- Configure e.g. a redis cache as explained on https://pimcore.com/docs/6.x/Development_Documentation/Development_Tools_and_Details/Cache/index.html
```
pimcore:
    cache:
        enabled: true
        pool_service_id: null
        default_lifetime: 2419200
        pools:
            redis:
                enabled: true
```
- under Settings > System Settings > Full Page Cache, disable the cache. This leads to these contents in the system.yml:
```
pimcore:
    cache:
        enabled: false
        lifetime: null
        exclude_patterns: ''
        exclude_cookie: ''
```
- reload Pimcore and open the Full Page Cache settings again, and you will see that the cache is still enabled.

### More information
It looks like pimcore is merging all the config structures together, which, using the examples posted above, gives this data structure at lib/Config.php line 101 (getSystemConfiguration()):
```
pimcore:
    cache:
        enabled: true
        pool_service_id: null
        lifetime: null
        exclude_patterns: ''
        exclude_cookie: ''
        default_lifetime: 2419200
        pools:
            redis:
                enabled: true
```
containing both cache configurations in one config key, with some values from system.yml overwritten by the values from config.yml
