### ISSUE TITLE
[Workflows] Vague documentation about configuration

### ISSUE THREAD

**Issue by msphn** [pimcore/pimcore#5686]
# Discussion
I probably missunderstand some configurations and behaviours of the workflow definition.
@fashxp asked me to discuss here what is right and what needs to be improved.

Considering a workflow with 3 steps like Todo, Processed, Done.
Following transitions: Todo -> Processed, Processed to Done and Processed/Done -> Todo.

I expected to be able to write like this:
```
  move_to_todo:
    from: [done, processed]
    to: todo
    options:
      label: 'Move back to ToDo'
      changePublishedState: force_unpublished
    name: move_to_todo
```
As I found out, even when using single_state the from declaration is connected with an and operator which I didn't understand first. That makes the transition disappear in the menu if the object is not in both steps done and processed.

For workflows which allows multiple steps at once it makes sense but for a single_state I guess it would be helpful to allow multiple from steps.

What confused me was the proper graph it generated, if I write the from as an array it actually shows 2 arrows from both steps towards the action and back to todo.

If you could clarify what is the expected behaviour I'd be glad to update the docs and clarify it with more examples.
