### ISSUE TITLE
[Workflows] Initial place of single_state workflows does not get saved in database

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#6013]
Steps to reproduce:
1. Create Class ABC with input field `workflowState`
2. Create workflow which supports `Pimcore\Model\DataObject\ABC` and has initial place `started`, and set
```yml
marking_store:
      type: single_state
      arguments:
         - workflowState
```
3. Create object of class ABC and publish it

Expected behaviour: Field `workflowState` should contain `started`
Current behaviour: Field `workflowState` is empty

Tested in Pimcore 6.3.3
