### ISSUE TITLE
[Ecommerce] Out-of-the-Box support for Elastic Search Synonyms

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#6490]
# Feature Suggestion 
This issue provides a out-of-the-box solution suggestion for the synchronization of elastic search (ES) synonyms, by the ecommerce framework.

## History
- PR #5744 suggested a native reindexing approach for the elastic search (ES) ecommerce product index. 
- It also contained a suggestion on how to support ES synonym updates out-of-the-box.
- PR #5744 has been closed by #6437, which is a more radical approach. 
- The synonym feature, which was part of #5744 is not included in #6437 anymore, as the approach was not convenient for multiserver-environments, where ES is not installed on the same server as the web application.

## Requirements
The suggested solution depends on the native reindexing approach, so basically the following workflow has to be executed: 
- Merge PR #5744 
- create another PR on top of #5744 and based on the discussed solution in this approach
- approve PR.

### Update Synonyms 
Introduce a new method  in the ``AbstractElasticSearch`` worker to just update the synonym filters in the settings, nothing else.
This approach works quite well and does not require reindexing. The only disadvantage is that the index needs to be closed and reopened, which will case the index to be inavaible for some milliseconds. 
```php
   /**
     * Perform a synonym update "live". Attention: the index will be closed and opened,
     * so it might not be available for a moment (typically some milliseconds).
     */
    public function updateSynonyms() {
        try {
            $this->activateIndexLock(); //lock all other processes

            $currentIndexName = $this->getIndexNameVersion();
            $settings = $this->tenantConfig->getIndexSettings();

            $filters = @$settings['analysis']['filter'];
            if ($filters) {
                $indexPart = [
                    'analysis' =>
                        [
                            'filter' => []
                        ]
                ];

                foreach ($filters as $name => $filter) {
                    if (in_array($filter['type'],['synonym'])) {
                        $indexPart['analysis']['filter'][$name] = $filter;
                    }
                }
            }

            $esClient = $this->getElasticSearchClient();

            $esClient->indices()->close(['index' => $currentIndexName]);
            $esClient->indices()->putSettings([
                'index' => $this->getIndexNameVersion(),
                'body' => [
                    'index' => $indexPart
                ]
            ]);
            $esClient->indices()->open(['index' => $currentIndexName]);

        } finally {
            $this->releaseIndexLock();
        }
    }
```

#### EsSyncCommand
- see https://github.com/andreas-gruenwald/pimcore/blob/44904e7cd6f2662584ecd6184d9f51eda6332ccd/bundles/EcommerceFrameworkBundle/Command/IndexService/EsSyncCommand.php. 
 - Essentially the ``refresh-synonyms`` mode from PR #5744 needs to be restored.
 - instead of copying the synonym files, the newly introduced method ``$elasticWorker->updateSynonyms()`` should be called.

#### TODOs
- refine filtering of relevant synonym filters.
- only update the index if the settings actually changed (compare settings from server with current settings).
- in future versions, even ``_reload_search_analyzers`` (https://www.elastic.co/guide/en/elasticsearch/reference/7.x/indices-reload-analyzers.html) could be applied, but this feature is only available since ES 7.x and is basically a technical optimization.

### Support Synonym Synchronisation on Multi-Server Environments
The approach in PR #5744 was based on synonyms that are stored in a local file.

Example:
```yaml
pimcore_ecommerce_framework:
index_service:
        tenants:
           mytenantName:
               config_options:
                    index_settings:
                        analysis:
                          filter:
                                my_synonyms:
                                    type: synonym
                                    synonyms_path: "ele_elasticsearch/synonyms_%%tenant%%.txt" # must reside in local /etc/elasticsearch/
```

Now the idea is to add the synonyms directly to the index instead of putting them to a local file, because then the local synonym file does not need to be transmitted to a remote file system.

This is the proof of concept:

### ElasticSearch-Config
``Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\ElasticSearch``

```php

    /**
     * @return array
     */
    public function getIndexSettings()
    {
        $indexSettings = $this->preparseIndexSettings($this->indexSettings);
        return $indexSettings;
    }

    /**
     * @param array $indexSettings
     * @throws \Exception
     */
    protected function preparseIndexSettings(array $indexSettings) {
        if (isset($indexSettings['analysis']['filter'])) {
            $filters = $indexSettings['analysis']['filter'];
            foreach ($filters as $filterName => $filter) {
                if ('synonym' === $filter['type']) {
                    if (array_key_exists('synonyms_path', $filter)) {
                        $path = $filter['synonyms_path'];
                        $filename = array_pop(explode_and_trim('/', $path));
                        $localHome = '/home/my-project/www/web/var/assets/System/Webshop/Search/';
                        $fullPath = $localHome.$filename;
                        if (!file_exists($fullPath)) {
                            throw new \Exception(sprintf('Synonym path "%s" does not exist.', $fullPath));
                        }
                        $content = file_get_contents($fullPath);
                        $synonymLines = explode_and_trim(PHP_EOL, $content);

                        $rewrittenFilter = $filter;
                        unset($rewrittenFilter['synonyms_path']);
                        $rewrittenFilter['synonyms'] = $synonymLines;

                        $indexSettings['analysis']['filter'][$filterName] = $rewrittenFilter;
                    }
                }
            }
        }

        //p_r($indexSettings['analysis']['filter']); exit;

        return $indexSettings;
    }
```
Basically the synonyms are parsed from the local synonym file and are then added to the index directly. The index configuration may look like this:

```yaml
pimcore_ecommerce_framework:
index_service:
        tenants:
           mytenantName:
               config_options:
                    index_settings:
                        analysis:
                          filter:
                                my_synonyms:
                                    type: synonym
                                    synonyms_path: "%kernel.root_dir%/var/web/var/assets/System/Webshop/Search/synonyms_%%tenant%%.txt"
```

#### TODOs
- while the solution is very simple, it still requires a local file, which is a small disadvantage. Instead of parsing the synonyms from a local file, a synonym-provider service could be introduced which can provide synonyms from a specific location. This needs some discussion.
- the right way to parse the synonyms and modify the index settings needs to be defined. Do we need some kind of ``getIndexSettingsModified()``, or ``getIndexSettingsOriginal()``?
