### ISSUE TITLE
[UI] Disabled toolbar buttons are hard to see

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#6501]
By default the toolbar buttons are hard to see when disabled.

Proposal
```css
.pimcore_main_toolbar .x-btn.x-btn-disabled {
    background-color: #484B4E;
    opacity: 1;
}

.pimcore_main_toolbar .x-btn.x-btn-disabled .x-btn-inner {
    color: #8e8e8e;
}
```
![image](https://user-images.githubusercontent.com/7206334/83517877-f4320a00-a4d9-11ea-8a32-fa0d76d48ad5.png)
