### ISSUE TITLE
Proper documentation on how to create custom editables

### ISSUE THREAD

**Issue by Blackbam** [pimcore/pimcore#7191]
Trying to create my first custom Editable i stumbled upon certain issues. First of all the documentations seems to be outdated:

Instead of:

```
# src/AppBundle/Resources/config/pimcore/config.yml

pimcore:
    documents:
        editables:
            map:
                markdown: \AppBundle\Model\Document\Editable\Markdown
```

One should use:

```
pimcore:
    documents:
        tags:
            map:
                # @TODO: BC layer, to be removed in v7
                markdown: \Pimcore\Model\Document\Tag\Markdown
```

And in general use the tag namespace instead the editable:

```
namespace AppBundle\Model\Document\Tag;

use Pimcore\Model;
use Pimcore\Model\Document\Tag\TagInterface;

class Markdown extends Model\Document\Tag
```

Now I would have updated this and made a merge request but then I realized the deprecation notice within the config files (to be removed in V7) - so I wonder what is the correct way  now to create custom editables?
