### ISSUE TITLE
[Bug] [Ecommerce] [IndexService] The TagsGetter returns wrong values

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#7306]
Config in YAML file:

```yaml
imports:
  - { resource: '@PimcoreEcommerceFrameworkBundle/Resources/config/v7_configurations.yml' }

pimcore_ecommerce_framework:
  ...
  index_service:
    tenants:
      default:
        ...
        attributes:
          ...
          tags:
            type: varchar(255)
            getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\TagsGetter
            getter_options:
              includeParentTags: true
            filter_group: multiselect
```

If you save the DataObject with defined tags, they will be saved in the index table as `Array` (just string).

![Bildschirmfoto 2020-10-13 um 12 17 32](https://user-images.githubusercontent.com/12817320/95848252-13755980-0d4e-11eb-95d7-57745e65812d.png)
