### ISSUE TITLE
Workflow with changePublishedState force_unpublished will create new version instead of unpublishing the object

### ISSUE THREAD

**Issue by mugge6** [pimcore/pimcore#7586]
# Bug Report

### Expected behavior

Workflow with two simple transitions (publish and unpublish) on DataObject:
```yaml
type: 'state_machine'
    marking_store:
        type: 'single_state'
        arguments: [ workflowState ]
```
...

```yaml
into_inactive:
into_unpublished:
    guard: is_fully_authenticated()
    from: [ published ]
    to: unpublished
    options:
        label: 'Unpublish'
        notes:
            commentEnabled: false
            commentRequired: false
        changePublishedState: force_unpublished
into_published:
    guard: is_fully_authenticated()
    from: [ unpublished ]
    to: publish
    options:
        label: 'Publish'
        notes:
            commentEnabled: false
            commentRequired: false
        changePublishedState: force_published
```
These transitions should toggle between publish and unpublish the DataObject.

### Actual behavior

Publishing is working fine. But unpublishing the DataObject will create a new version and leaves the object published. I expect, that the DataObject is unpublished afterwards.
