### ISSUE TITLE
"Public URL" in Assets not displayed correctly in latest Pimcore version

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#8184]
Just reproduced on the demo. The "Public URL" should show the full URL, including the domain:
![image](https://user-images.githubusercontent.com/13643455/108050748-515ef300-704a-11eb-8458-f9976f5b28bb.png)

**Comment by davidhoeck** [comment]
@brusch your fix messes up with AWS S3 integrations for example. When using a CDN then the Scheme and HTTP Host are not needed. I think this should only be prepended when there are no listeneres attached.

**Comment by brusch** [comment]
@davidhoeck well I think this was broken before as well, because it was just the path :) But I agree, that should be fixed for remote filesystems/CDNs as well. Can you provide a PR?

**Comment by bramalho** [comment]
this fix: https://github.com/pimcore/pimcore/commit/c86ce948b59be4eb53b3f32a60023a00891ac6ee
does not work when you want to override the public URL

ie:
if we change the config:
```
pimcore:
    assets:
        frontend_prefixes:
            source: 'https://storage.googleapis.com/%env(GCP_BUCKET_NAME)%'
```

the result will be something like this: `url: "http://localhoshttps://storage.googleapis.com/....`
