### ISSUE TITLE
[Documents] Headless CMS

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#8197]
It should be possible to define a content structure without the need of specifying a template. 
The concept could be similar to the one we're using already in a minimal version for the [Editable Dialog](https://pimcore.com/docs/pimcore/current/Development_Documentation/Documents/Editables/Areablock/Bricks.html#page_Editable-Dialog-since-6-8). 

Possible approach: 
- Defining the content-structure in a YAML file
- The YAML file is then specified as the "template" on a page/snippet
- If a YAML file is provided as a template, then Pimcore knows it's a headless content strucure
- The editing interface is generated according to the content structure defined in the YAML

Additionally it would be nice to have a preview generator, that is used to generate the preview URL (see also [Link Generators for Objects](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Class_Settings/Link_Generator.html) )

### Example YAML

Could be stored in `/config/pimcore/headless-definitions/example.yaml`

```yaml
content:
    headline:
        type: input
        config:
            placeholder: 'Headline'
            required: true

    selectTest:
        type: select
        config:
            store:
                - ["one-month", "One month"]
                - ["three-months", "three-months"]
                - ["unlimited", "unlimited"]
    mainContent:
        type: wysiwyg
        config:
            height: 200

    contentBlocks:
        type: areablock
        bricks:
            teasers:
                teaser_1:
                    type: snippet
                teaser_2:
                    type: snippet
            gallery:
                imagesBlock:
                    type: block
                    items:
                        image:
                            type: image
                            width: 200
                            height: 200
                            thumbnail: gallery
            video:
                video:
                    type: video
            productListing:
                products:
                    type: relations
                    types: ["object"]
                    classes: ["Product"]
```
