### ISSUE TITLE
[Configuration] Pimcore configuration tree not validated properly

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#8270]
Following configuration should result in compile error, but it does not... thus potential wrong configurations are very hard to find. 

```yml
pimcore:
   xyz:
      xyz:
```
