### ISSUE TITLE
[Ecommerce] PricingManager custom rule_class not applied

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#8367]
# Bug Report

The configured `rule_class` option is not applied to rule listings, so the hardcoded classname in https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/PricingManager/Rule/Listing/Dao.php#L29 cant be changed.

```
pimcore_ecommerce_framework:
    pricing_manager:
        tenants:
            _defaults:
                pricing_manager_options:
                    rule_class: AppBundle\Ecommerce\PricingManager\Rule
```

This is especially fatal in the `getPricingManagerTokenInformationDetails()` method, which calls `getValidRules()` in https://github.com/pimcore/pimcore/blob/master/bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php#L217.
