### ISSUE TITLE
[Workflows] Error when adding elements via CLI when workflow with supports strategy is active

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9030]
having a workflow with supports strategy as follows

```yml 
            support_strategy:
                type: "expression"
                arguments:
                    - \Pimcore\Model\Asset
                    - 'is_fully_authenticated()'
```

results in following error, when importing elements (in this case assets) via CLI script

```
The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL. 
```

To reproduce, just create an asset via CLI script in the demo application.
