### ISSUE TITLE
Check E-Mail-Settings and documentation

### ISSUE THREAD

**Issue by aKugler** [pimcore/pimcore#9126]
Today I set up a new Pimcore X project. I added comments to the mailing in `config.yaml` and filled it in in a meaningful way. Afterwards, I noticed that the admin still displays the message that the mail settings are incomplete. I suspect that this was overlooked during refactoring (https://github.com/pimcore/pimcore/issues/8754). Furthermore, the documentation should be adapted here. There is still talk here of a setting via Admin (https://pimcore.com/docs/pimcore/current/Development_Documentation/Tools_and_Features/System_Settings.html#page_E-Mail-Settings). I found the place for the message in the code. There and in the check for the maintenance cron, there is still a link to the 6.9 documentation. https://github.com/pimcore/pimcore/blob/4550a053fac47a1d2c0406bf15c9799ef078bbb7/bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js#L1083

- [X] This is not a security issue / vulnerability
- [X] Behavior is reproducible on https://demo.pimcore.fun/admin/ (admin/demo)
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...)

**Comment by Nikolayya** [comment]
Hi aKugler: 

Try following things in the config/config.yaml

```
pimcore:
    email:
        sender:
            name: 'Your Name'
            email: 'no-replay@yourproject.at'
        return:
            name: 'Your Name'
            email: 'no-replay@yourproject.at'
    newsletter:
        use_specific: false 
        sender:
            name: 'Your Name'
            email: 'no-replay@yourproject.at'
        return:
            name: 'Your Name'
            email: 'no-replay@yourproject.at'
framework:
    mailer:
        transports:
            main: smtp://YOURDSNSTRING
            pimcore_newsletter: smtp://YOURDSNSTRING
```

YOURDSNSTRING take a look to [Sending Emails with Mailer](https://symfony.com/doc/current/mailer.html)

Hope this could help :-)
