### ISSUE TITLE
Send Newsletter alltime message "Newsletter sending already in progress, need to finish first."

### ISSUE THREAD

**Issue by mediafant** [pimcore/pimcore#9258]
# Bug Report

### Actual behavior
Sending Test-newsletter works
Sending real newsletter breaks with message that there is one in progress. But there is no.
If I comment out 
./vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
Line 359 the job works

Pimcore Version 10.0.1

**Comment by dvesh3** [comment]
Fixed by #9317

**Comment by lohitpereira** [comment]
Hi, I have not understood where the change is. I am using pimcore 10 on windows 10 system with WAMP server. I am able to "Send a Test-Newsletter" from the "Newsletter Sending Panel".

The ISSUE I have is that I am unable to send a newsletter document using the "Send Newsletter Now" after selecting the below settings in the "Newsletter Sending Panel".
Address Source Adapter: Default object List, 
Class: valid class, 
Object Filter (SQL): valid query.  _Pimcore displays "OK 1 recipient" in the tooltip._

I have the following fields configured
```
pimcore:
    email:
        sender:
            name: 'lohitpereira'
            email: lohitpereira@service.com
        return:
            name: 'lohitpereira'
            email: lohitpereira@service.com

framework:
    mailer:
        transports:
            main: smtp://<user:pass>@smtp.postmarkapp.com:port
            pimcore_newsletter: smtp://<user:pass>@smtp.postmarkapp.com:port
```

is there any cron like job to be run for this ?
