### ISSUE TITLE
Workflow marking_store arguments are not compatible with Symfony 5.x anymore

### ISSUE THREAD

**Issue by mugge6** [pimcore/pimcore#9525]
# Bug Report

### Expected behavior

Symfony 4.3 configuration:
```
   marking_store:
      type: single_state
      arguments:
         - workflowState
```

Symfony 4.4 and 5.x configuration:
```
            marking_store:
                type: 'method'
                property: 'currentPlace'
```

Since Pimcore X property value is always default "marking" and is not configurable with "arguments" setting from Pimcore over configuration.
